### ISSUE TITLE
Cannot get this to work?

### ISSUE THREAD

**Issue by Lord-Menes** [acacha/adminlte-laravel#11]
Really i cannot get this to work. I follow step by step however whenever i run the php artisan serve command it just displays the standard "Laravel with AdminLTE" page and not the AdminLTE template page? Any ideas?

**Comment by dondanidang** [comment]
That is it!! You did it well. Now:
 1- Run the migration to create users users table
 2- Add the route for "auth/login" (just look at the top before the installation instructions)
 3- To see the login page go to "my-page.com/auth/login" 
 4- You can create a user with seeder class or directly from the login page

I hope it helps

**Comment by Lord-Menes** [comment]
Excellent! Thanks for your help!

**Comment by Lord-Menes** [comment]
Hello again,

Thanks for your help before.

I am trying to get this up and running on a LEMP stack i have setup however when i attempt to run the php artisan migrate command it brings up the following error: "[PDOException] could not find driver" however the driver is enabled in my php.ini file? I think i am going wrong somewhere when installing to my VPS? Any help would be much appreciated.
