### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by Sogl** [acacha/adminlte-laravel#12]
Hi!

Sorry, I'm new in Laravel... I already did these steps (using vagrant):
* `laravel new laravel.app`
* `composer require "acacha/admin-lte-template-laravel:0.*"`
* Added to config.php:
```
// AdminLTE template provider         
Acacha\AdminLTETemplateLaravel\app\Providers\AdminLTETemplateServiceProvider::class,
```
* `php artisan vendor:publish --force --provider="Acacha\AdminLTETemplateLaravel\app\Providers\AdminLTETemplateServiceProvider"`
* My `/home/vagrant/Code/` folder mapped to `C:\projects\Laravels\`. This app lines:
```
map: laravel.app
to: /home/vagrant/Code/laravel.app/public
```
* I go to `http://laravel.app` and see message `Laravel 5 with AdminLTE`.

But what next? How to see AdminLTE login form?
I tried to add routes in `routes.php`, but url `http://laravel.app/home` give me error:
```
ErrorException in 645ddd92044e80ef67faf70852c9c41a line 118:
Trying to get property of non-object (View: /home/vagrant/Code/laravel.app/resources/views/partials/mainheader.blade.php) (View: /home/vagrant/Code/laravel.app/resources/views/partials/mainheader.blade.php) (View: /home/vagrant/Code/laravel.app/resources/views/partials/mainheader.blade.php)
```

**Comment by acacha** [comment]
Which version of Laravel are you using?

Did you added routes as proposed in section "Laravel 5.1 notes" of README file https://github.com/acacha/adminlte-laravel/blob/master/README.md ?

**Comment by acacha** [comment]
Or you can try new version 1.0 . Now README file is updated for this version

**Comment by Sogl** [comment]
>Which version of Laravel are you using?
5.1

>Did you added routes as proposed in section "Laravel 5.1 notes" of README file
Yep.

>Or you can try new version 1.0 . Now README file is updated for this version
How to update from previous version? with `composer update`?

**Comment by acacha** [comment]
Change version in composer.json to 1.0 and  then run composer update. Then there's no need of routes in routes.php

**Comment by Sogl** [comment]
Thx! It works now.
But my `routes.php` file not changed:
```
<?php

Route::get('/', function () {
    return view('welcome');
});

```
Where I can find new routes?

Also some icons missing:
![screenshot_24](https://cloud.githubusercontent.com/assets/7556290/9984210/081ad7d0-6057-11e5-9126-24b281fab0b2.jpg)
Screen from template preview:
![screenshot_25](https://cloud.githubusercontent.com/assets/7556290/9984225/493fb6c2-6057-11e5-824c-2b7503ce1a2a.jpg)

Now if I go to `http://adminlte.lar/` then see standard Laravel 5 welcome page. How to route it to `http://adminlte.lar/home` by default?

**Comment by acacha** [comment]
I added two issues for your requests. I close this one:

https://github.com/acacha/adminlte-laravel/issues/13
