### ISSUE TITLE
Can not publish language files

### ISSUE THREAD

**Issue by felorodri** [acacha/adminlte-laravel#126]
Hi there!

I have been using AdminLTE for a while with L5.2 without any issue at all, but now, I have started a new project using L5.3. I succesfully installed AdminLTE on this new L5.3 project a few days ago, but now and for first time I need to publish the language files to make some changes to the existing messages.

When I run "php artisan vendor:publish --tag=adminlte_lang --force" command, I receive "Nothing to publish for tag [adminlte_lang]" message.

As I said, I succefully instaled AdminLTE on this project and I have already tested it. Am I missing something? How can I publish those files?

**Comment by acacha** [comment]
Solved in last commit https://github.com/acacha/adminlte-laravel/issues
