### ISSUE TITLE
Modal behind backdrop

### ISSUE THREAD

**Issue by Aterbonus** [acacha/adminlte-laravel#127]
bootstrap-less has the modal z-index equals to 1040. In new versions of bootstrap the z-index is 1050.
Adminlte is using two version of bootstrap, the less and the sass. The sass version has a z-index for the backdrop (1040). This causes an issue where the backdrop is above the modal.

If we remove the bootstrap import in the ```resources/assets/sass/app.scss``` the problem is solved.

**Comment by vandyroyy** [comment]
![modal-issue](https://cloud.githubusercontent.com/assets/15111433/20311077/f8553554-ab80-11e6-89b7-c096b423ffbd.png)

i have a same problem

**Comment by acacha** [comment]
Could you please popose a PR?

**Comment by Aterbonus** [comment]
No problem, give me some time ;)

**Comment by acacha** [comment]
Thanks!

**Comment by acacha** [comment]
Done https://github.com/acacha/adminlte-laravel/pull/140
