### ISSUE TITLE
Icons at login and registration pages not works

### ISSUE THREAD

**Issue by acacha** [acacha/adminlte-laravel#13]
Maybe is a problem with bootstrap version? 

Original adminlte version at web https://almsaeedstudio.com/themes/AdminLTE/pages/examples/login.html#

 - Bootstrap v3.3.4 (http://getbootstrap.com)

Also use minified versions?

TODO

**Comment by hellzakk** [comment]
Hi, i have this problem too, maybe there are some setting to change?
Seems that the location of the glyphicon are not set in the project...
