### ISSUE TITLE
Error amb la URL : http://localhost:8000/sergi

### ISSUE THREAD

**Issue by OscarDuranX** [acacha/adminlte-laravel#130]
ErrorException in Gravatar.php line 245:
Please specify a valid email address (View: /home/oscar/Code/clones/pullrequest/resources/views/vendor/adminlte/layouts/partials/mainheader.blade.php) (View: /home/oscar/Code/clones/pullrequest/resources/views/vendor/adminlte/layouts/partials/mainheader.blade.php) (View: /home/oscar/Code/clones/pullrequest/resources/views/vendor/adminlte/layouts/partials/mainheader.blade.php)

**Comment by acacha** [comment]
This errors occurs when using layout for protected resources (middleware auth) with a not protected route. Add route to middleware auth and error doesn't occurs.

**Comment by MatiCand** [comment]
> This errors occurs when using layout for protected resources (middleware auth) with a not protected route. Add route to middleware auth and error doesn't occurs.

and how can i do that?

**Comment by maruhgar** [comment]
I see the same error - it works for one view but not for another.   Using the latest composer version of dependencies with laravel 5.4.

**Comment by maruhgar** [comment]
Ok,  the fix was

```
-   <img src="{{ Gravatar::get($user->email) }}" class="user-image" alt="User Image"/>
+   <img src="{{ Gravatar::get(Auth::user()->email) }}" class="user-image" alt="User Image"/>
```

And the reason why it was only happening for a specific page (http://..../users/) was because, I had a $user variable to display list of users.
