### ISSUE TITLE
How to disable GuestUser Middleware

### ISSUE THREAD

**Issue by underdpt** [acacha/adminlte-laravel#132]
Hi,

I'm trying to integrate this (great) package with [Cartalyst Sentinel](https://github.com/cartalyst/sentinel) which I'm familiar with.

So far I have completed all auth system, but I found that GuestUser Middleware is pushing a $user variable to all views, which I think should be optional (that's a very common variable name).

Take this scenario (which I'm dealing with): I'm making an user create/edit form, which is linked to a model, $user. If the form founds a $user variable, it fills the form with the attributes of the $user variable, and if no $user variable, all the inputs are blank.
But when GuestUser Middleware creates a $user for you, a lot of problems can arise (when you try to call a Eloquent relationship, or use some function from the model that clearly doesn't exists).

So, I think there should be a way to disable this GuestUser Middleware, but I didn't found any (the middleware is pushed from a GuestUserProvider which is registered via AdminLTETemplateServiceProvider. If I overload this file i'll have to manually track the updates to that provider... almost no useable :-(

Is there any way to disable or override this GuestUser Middleware?

**Comment by acacha** [comment]
Some options:
- You can use another variable name for you user ;-)
- Use a custom service provider extended from mine but whithout registering GuestUserProvider
- Create your custom Middleware or custom ViewComposer, execute it after mine and put what you want as user variable in views

**Comment by underdpt** [comment]
Hi @acacha 

Thanks for your answer. 

>     You can use another variable name for you user ;-)
Sure, but that's going to generate problems on the future. When I or another dev takes the project and sees an $user variable on his view, I/he/she will make wrong assumptions (Is this my $user or acacha's guest $user?)
Also, that would be a mess when using resources.
>     Use a custom service provider extended from mine but whithout registering GuestUserProvider
Yes, that's the way I'm taking, but will have to track down changes to your service provider, because it's registering the GuestUserProvider on register() function which registers other providers.
I would be a good option:
- To register GuestUserProvider on a separate function inside AdminLTETemplateServiceProvider, so overloading this separate function (registerGuestUserProvider() ?) would suffice.
- To make it optional via a config option.
>     Create your custom Middleware or custom ViewComposer, execute it after mine and put what you want as user variable in views
No, that won't work. I don't want an $user variable when no user has logged in.

Also, this applies to the GravatarServiceProvider, which is now mandatory.

Thanks anyway for your great package and support!

**Comment by acacha** [comment]
HI @underdpt I agree with you to make this last features as optional only thinking about how to implement that... fill you free to propose a PR if you have any useful idea! Thanks!

**Comment by acacha** [comment]
Anywat some easy proposed changes are being implemented. See https://github.com/acacha/adminlte-laravel/commit/03a2b9ada39cc5edb75948ffbb1d20ee5b7f1acb

**Comment by acacha** [comment]
Added config variables to allow disabling extra providers at https://github.com/acacha/adminlte-laravel/commit/8be5bb1d4a8c386de7bccad55f656f6bf5454556

**Comment by underdpt** [comment]
Thanks!  That's very helpful
