### ISSUE TITLE
Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers not found

### ISSUE THREAD

**Issue by fede91it** [acacha/adminlte-laravel#138]
Hello,

I've installed adminlte-laravel with on a fresh Laravel installation.

I have an issue with the auth controller generated by adminlte-laravel, because in the file  `App\Http\Controllers\Auth\AuthController` a trait cannot be found: `Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers` doesn't exists.

This cause me some issues with other packages like barryvdh/laravel-ide-helper.

**Comment by fede91it** [comment]
Anyone can help me?

**Comment by acacha** [comment]
Ok now reading some possible changes in new Laravel versions https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0

**Comment by acacha** [comment]
@fede91it which version of adminlte-laravel are you using? Lasts versions doesn't use AuthController because authentication is splitted in more basic parts since Laravel 5.3.

**Comment by fede91it** [comment]
"acacha/admin-lte-template-laravel": "2.*"

**Comment by acacha** [comment]
As you can see at https://github.com/acacha/adminlte-laravel/tree/master/src/stubs there is no stub for AuthController maybe you are using a previuos Laravel version? Maybe you can provide me the steps to follow to reproduce this problem because I wasn't able to reproduce it by myself.

**Comment by fede91it** [comment]
My mistake. I used the versione 2.* instead of the version 3.*
