### ISSUE TITLE
adminlte_less.css not chaning

### ISSUE THREAD

**Issue by Waguilar33** [acacha/adminlte-laravel#139]
I have tried everything but I can't change the adminlte_less css file. Any help will be appreciated.

**Comment by acacha** [comment]
Sorry could you provide more info or maybe and example? Why do you mean by "can't change"?

**Comment by Waguilar33** [comment]
Can't modify the adminlte_less css styles... For example, `<footer class="main-footer">` has the following styles being applied...

```
.main-footer {
    background: #fff;
    padding: 15px;
    color: #444;
    border-top: 1px solid #d2d6de;
}
```
I want to modify the padding to be 5px, for example, but I haven't been able to do so. 

I have found two files with the name adminlte_less.css one being inside the public/css and the other in vendor/acacha/admin-lte-template-laravel/public/css. However, I have made changes to both files but they are not being reflected.

**Comment by acacha** [comment]
This package is using Laravel Elixir https://laravel.com/docs/5.3/elixir . Did you try to compile after modificacion using gulp?

**Comment by nadyarizka** [comment]
how do you compile using gulp after modify the adminlte.less.css?

**Comment by andreich1980** [comment]
@nadyarizka try it
```
// Run all tasks...
gulp
```
or
```
// Run all tasks and minify all CSS and JavaScript...
gulp --production
```
