### ISSUE TITLE
error when running composer update

### ISSUE THREAD

**Issue by morgothx** [acacha/adminlte-laravel#147]
Hi:

I just run composer update and:

> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize

                                                             
  [Symfony\Component\Debug\Exception\FatalThrowableError]    
  Class 'Acacha\User\Providers\GuestUserProvider' not found  
                                                             

Script php artisan optimize handling the post-update-cmd event returned with error code 1

It also return the same error when trying to do any php artisan migrate operation

I'm on Laravel 5.3, i aprecciate any help with this problem.

thank you

**Comment by morgothx** [comment]
the class that i found on that namespace is called "GuestUserServiceProvider" no "GuestUserProvider"
I change the use stament and it works, but every time i run composer update the changes will gone so, can you please fix that name

**Comment by acacha** [comment]
Changed in last commit https://github.com/acacha/adminlte-laravel/blob/master/src/Providers/AdminLTETemplateServiceProvider.php

**Comment by acacha** [comment]
Solved at 3.1.10
