### ISSUE TITLE
Problem with routes L5.3 and adminlte-laravel

### ISSUE THREAD

**Issue by ssheduardo** [acacha/adminlte-laravel#151]
The integration is good, all components is perfect.
Now, when show all routes:

![captura de pantalla 2016-12-08 a las 10 07 12](https://cloud.githubusercontent.com/assets/1160138/21003930/3f6ee106-bd2e-11e6-8a04-480b788aaff1.png)

The version 5.3 not have routes.php (this is the new structure)
![captura de pantalla 2016-12-08 a las 10 11 51](https://cloud.githubusercontent.com/assets/1160138/21004062/caba8936-bd2e-11e6-88df-0b604fe385b0.png)

Your ServiceProvider have this:
![captura de pantalla 2016-12-08 a las 10 13 35](https://cloud.githubusercontent.com/assets/1160138/21004096/00b6f790-bd2f-11e6-8386-139a4ae062a4.png)

**I need create my custom routes for example:**
 * Not need Register 
 * Need change names for login, password, etc.
Question, what is the best way for customize the routes?

**My system:**
* PHP 5.6
* Ubuntu 14.04
* Laravel 5.3
* Adminlte-laravel 3.1.11

Sorry for my english is very bad.

**Comment by acacha** [comment]
@ssheduardo you can disable adminlte service provider in config/app.php and create your own custom routes.php file (you can start with mine). You can also override/extend my ServiceProvider and override method defineRoutes.
