### ISSUE TITLE
How to insert components from https://almsaeedstudio.com/themes/AdminLTE/pages/forms/advanced.html

### ISSUE THREAD

**Issue by felipe-correia** [acacha/adminlte-laravel#162]
I was able to install adminlte with laravel but I can`t use the components which have Select2, for example. I am copying the code from https://almsaeedstudio.com/themes/AdminLTE/pages/forms/advanced.html 
to my project and the page gets messed up. What do I have to do?

I`ve been trying for some time with no success.

After a lot of research I have no idea of how to acomplish this.

I attached a photo of what was supposed to be a multiple select. 

![15556592_1051777324944187_965260011_o](https://cloud.githubusercontent.com/assets/24629571/21291035/151ad89a-c4b0-11e6-8c5e-427075754c95.jpg)

**Comment by acacha** [comment]
Hi. This package use Laravel Elixir to compile assets so please adapt gulpfile to add extra css/js files to your compilation and then run $gulp.

Also if you want you can change the default layout to avoid using Laravel Elixir and adapt to your needs.

**Comment by felipe-correia** [comment]
I changed the layout manually. It is better than before but something is missing. Could you help me little bit more? What am I doing wrong? Console is clean.
![screen shot 2016-12-18 at 20 44 19](https://cloud.githubusercontent.com/assets/24629571/21297698/2383610a-c563-11e6-8b98-2951a95035ae.png)

**Comment by felipe-correia** [comment]
After removing all the <span> tags it gets better but the quality of the elements are inferior than the template. See:

![screen shot 2016-12-18 at 20 54 50](https://cloud.githubusercontent.com/assets/24629571/21297763/6b757844-c564-11e6-9ea1-175b1ab9d9bb.png)

**Comment by acacha** [comment]
Sorry but without any code example I don't know how to help you...
