### ISSUE TITLE
ReflectionException: Class AdminUserSeeder does not exist

### ISSUE THREAD

**Issue by acacha** [acacha/adminlte-laravel#164]
After fresr installation give this error for example running:

```php
phpunit
```

The problem is solved with:

```bash
$ composer dumpautoload
```

So maybe run composer dumpautoload after installation?

**Comment by acacha** [comment]
Some times this problem reappears but solves after executing $ composer dumpautoload again

**Comment by irfan88** [comment]
i have some issue, how resolve?
