### ISSUE TITLE
Commands make:mvc and make:vc complete MVC creating all need (model, view, route, controller)

### ISSUE THREAD

**Issue by acacha** [acacha/adminlte-laravel#167]
Using new commands. Which command name?

**Comment by acacha** [comment]
Command:
```bash
php artisan make:mvc name
```
Executes:

```bash
php artisan make:model Name
php artisan make:route name --type=controller -a --menu
```

Where -a add view and Controller and --menu adds menu entry

**Comment by acacha** [comment]
Command:
```bash
php artisan make:vc name
```
Executes:

```bash
php artisan make:route name --type=controller -a --menu
```

By default type controller. Use optional type to use other type of routes (regular, resource)

Where -a add view and Controller and --menu adds menu entry

**Comment by brunopinha** [comment]
When executing the command: `php artisan make:vc name`

The model is created, the migration also, however the following error occurs:

  [Acacha \ AdminLTETemplateLaravel \ Filesystem \ FileDoesNotExists]
  File does not exist

How to solve?

**Comment by miguelcamargo9** [comment]
+1

**Comment by acacha** [comment]
@brunopinha I think this issue is solved for me it works all ok. Feel free to reopen the issue an please provide steps to reproduce the problem (user php artisan -vvv to provide more info please)

**Comment by CamiloValencia** [comment]
Hi, if i use the comman make:vc or make:mvc i optain an error: file does not exists
![imagen](https://cloud.githubusercontent.com/assets/292653/22744476/7a515d24-edeb-11e6-95bb-aca4f6e805bc.png)

**Comment by reiter777** [comment]
@CamiloValencia i have the same problem man, do you know how to solve it?

**Comment by phuasteven09** [comment]
@CamiloValencia  Any fix on this problem?

**Comment by kiminya-raphael** [comment]
Traced problem to the `getPath()` function of `Acacha\Filesystem\Filesystem` which prepends the `$root` variable (`\`) and `\` to the file path. So you end up with something like `\\C:\project\file` which explains why it doesn't work in windows.
