### ISSUE TITLE
make adminLTE theme default for entire site

### ISSUE THREAD

**Issue by bjaysheel** [acacha/adminlte-laravel#17]
Hi, I am new to Laravel, and adminLTE.  How do I setup/install adminLTE-laravel theme such that I see all parts of adminLTE without logging in.  I want to create an app with adminLTE theme, if user logs in few features and enabled, and private information is visible. 

Hope this makes sense 

Thanks for your help

**Comment by webkingashu** [comment]
dude,

just run composer upddate :D

On Fri, Oct 2, 2015 at 1:49 AM, Jaysheel Bhavsar <notifications@github.com>
wrote:

> Hi, I am new to Laravel, and adminLTE. How do I setup/install
> adminLTE-laravel theme such that I see all parts of adminLTE without
> logging in. I want to create an app with adminLTE theme, if user logs in
> few features and enabled, and private information is visible.
>
> Hope this makes sense
>
> Thanks for your help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acacha/adminlte-laravel/issues/17>.
>



-- 

Ashutosh Bhardwaj
+91-7208360339, +919713910439

**Comment by acacha** [comment]
I think this is solved no?
