### ISSUE TITLE
Can't make changes on home.blade.php 

### ISSUE THREAD

**Issue by quetool** [acacha/adminlte-laravel#174]
I can not make changes on my adminlte site. For example, I edit the home.blade.php file but nothing changes on site, always showing the You are logged in! message!

this is the file
![captura de pantalla 2016-12-19 a las 12 33 54](https://cloud.githubusercontent.com/assets/14978705/21318501/314bf0d8-c5e8-11e6-8837-5714ed6194f0.png)

**Comment by GianNipitella** [comment]
did you try clearing the view:cache? 
what version of acacha/Adminlte  and laravel  are you using?
did you try to change the message on the adminlte_lang::message.logged?
what do you spect to get instead of the you are logged in message?
