### ISSUE TITLE
Modal need set data-backdrop="false"

### ISSUE THREAD

**Issue by haidang** [acacha/adminlte-laravel#179]
I did make a modal:

				<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
				  Launch demo modal
				</button>

				
				<div id="myModal"  class="modal fade" role="dialog" tabindex="-1" data-backdrop="false">
				  <div class="modal-dialog">
				    <div class="modal-content">
				      <div class="modal-header">
				        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				        <h4 class="modal-title">Modal title</h4>
				      </div>
				      <div class="modal-body">
				        <p>One fine body...</p>
				      </div>
				      <div class="modal-footer">
				        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				        <button type="button" class="btn btn-primary">Save changes</button>
				      </div>
				    </div>
				  </div>
				</div>
I just install and testing modal, please give me some suggestion! Thank you.

**Comment by acacha** [comment]
Solved in last commits/tag. Please read also https://github.com/acacha/adminlte-laravel/issues/188
