### ISSUE TITLE
Add token in reset.blade

### ISSUE THREAD

**Issue by emirodriguez** [acacha/adminlte-laravel#18]
Add
`<input type="hidden" name="token" value="{{ $token }}">` 
in reset.blade view

**Comment by acacha** [comment]
Can you do a pull request please?

**Comment by acacha** [comment]
Um sorry a question? Why do you need to hidden files _token and token?

**Comment by emirodriguez** [comment]
Without the hidden token, the following validation error is displayed:
![GitHub Logo](http://k46.kn3.net/B8A9E8279.png)

This is taken from official documentation:

![GitHub Logo](http://k46.kn3.net/28E7E9E36.png)
http://laravel.com/docs/5.1/authentication#resetting-views

**Comment by acacha** [comment]
@emirodriguez Thanks for the explanation I understand this but sorry my question is about if we need to mantain both hidden fields or substitute _token by token. I'm not sure if in previous laravel version or any case woul be necessary to have _token?

Meanwhile I will aplly the patch and with more time search for more info
