### ISSUE TITLE
Can you provide some help for putting a chart in adminlte-laravel.

### ISSUE THREAD

**Issue by psm1963** [acacha/adminlte-laravel#181]
https://almsaeedstudio.com/themes/AdminLTE/pages/charts/chartjs.html

I know adminlte-laravel only shows a minimum page...can you please detail the steps to add a chart like the one above to this project..thanks for any help

**Comment by acacha** [comment]
You can compare adminlte demo pages with current provided files and customize to your needs adding css/js and html code. So compare adminlte demo files with acacha adminlte files to find the differences. Maybe in the future this package will provide adminlte demo pages too.
