### ISSUE TITLE
are adminlte plugins compiled with app.js?

### ISSUE THREAD

**Issue by jhawas** [acacha/adminlte-laravel#182]
datatable js doesn't work on me and some of the plugins.

how can i add those adminlte plugins in my laravel?

**Comment by acacha** [comment]
As any other Javascript file you can add .js files at html header section. Also (I prefer this option) you can use Larave Elixir/Laravel mix to compile assets and add your needed css/js files to a bundle css/js file. 

See https://laravel.com/docs/5.3/elixir

and current configuration at file gulpfile.js https://github.com/acacha/adminlte-laravel/blob/master/gulpfile.js

**Comment by jhawas** [comment]
ok, thanks a lot. i found it.
