### ISSUE TITLE
about using trans {{ trans('adminlte_lang::message.xxx') }}

### ISSUE THREAD

**Issue by Mahdi-Sahib** [acacha/adminlte-laravel#183]
how I can move message.php from vendor to resources 
its very important cos I can't push vendor to git

**Comment by Mahdi-Sahib** [comment]
I do it by make a copy of message.php in resources   
 and remove adminlte_lang 
just change 
{{ trans('adminlte_lang::message.xxx') }}
to
{{ trans('message.xxx') }}

**Comment by acacha** [comment]
You can user publish command with tag "adminlte_lang" to publish (and then you can override) messages.

See https://github.com/acacha/adminlte-laravel/blob/master/src/Providers/AdminLTETemplateServiceProvider.php
