### ISSUE TITLE
Registering auth routes is intrusive

### ISSUE THREAD

**Issue by rwngallego** [acacha/adminlte-laravel#184]
The AdminLTE package should not register any route inside the package itself. It's intrusive and makes it really difficult to customize the auth routes:

````
    Route::auth();
    Route::get('/home', 'HomeController@index');
````

## Detailed description
The following code makes it really difficult to customize the auth routes (disabling, protecting or modifying them):

https://github.com/acacha/adminlte-laravel/blob/24cdb0a338133c7de39c7c902c011c8e03a9b447/src/Http/routes.php#L9-L11

Some users had problems trying to customizing them:
https://github.com/acacha/adminlte-laravel/issues/69

https://github.com/acacha/adminlte-laravel/issues/151

Also, from my own when trying to disable the provider I get this error:

````
Whoops, looks like something went wrong.
2/2
ErrorException in FileViewFinder.php line 112:
No hint path defined for [adminlte]. (View: /home/vagrant/Code/project/resources/views/admin/home/index.blade.php)
````

## Possible implementation

It's better to tell the package users that they should add the following code to their routes/web.php file in the AdminLTE-laravel installation steps:

````
    Route::auth();
    Route::get('/home', 'HomeController@index');
````

## Your environment

````
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "acacha/admin-lte-template-laravel": "^3.1"
    },
````

**Comment by acacha** [comment]
@rwngallego For me is ok the actual behaviour (of course it have advantatges and disadvantages).  Feel free to propose a PR that use config or any other option to support your needs and my (and probably other ) needs.

Also there are many ways you can make litle changes in code to customize the routes.
