### ISSUE TITLE
Input fields do not work look properly in fresh installation

### ISSUE THREAD

**Issue by clebersa** [acacha/adminlte-laravel#188]
Hi!
I have a bug to report. When I just install Acacha AdminLTE Laravel in my machine, the input fields do not show correctly. The color of the content for every input shows with the same color of the placeholder (light gray), which makes difficult to read the input text.

## Detailed description

I created a new Laravel project using `laravel new test-project`. Then I did a `cd test-project` and ran `adminlte-laravel install`, then I opened the URL for the project using `http://192.168.0.252/test/public/`.

The input fields, like the one in the footer of the welcome page ("Drop Us A Line" section) does not show like the in the demo. The inputs have their placeholder on the right color, but when you type there, the input content keeps the same color of the placeholder, which makes difficult to read. 

Also, the labels, by default, should be bold like in the demo and the original AdminLTE demo, but they do not show as bold.

It is possible to see that the downloaded version is not the same of the living demo you have because some static text looks different on both versions, the menu "Features" on the top only appears for the living demo, etc.

## Possible implementation

I believe that this is a problem in the CSS. I can fix it here, but as I just installed it and it is not working like in the demo, maybe that is something to be solved in your repository.

## Your environment
I am using a Linux VM (Ubuntu 16.04) with Vagrant (v1.9.1). The VM has Apache (v2.4.7) and PHP (v2.6.29). I did not set up apache to look just for the public folder so far. That's why I have to specify the public folder in the URL.

Thank you for your time.
I look forward for your feedback.

Have a good day.

**Comment by fede91it** [comment]
Same for me

![image](https://cloud.githubusercontent.com/assets/346224/22284034/9a6baa62-e2e5-11e6-85c8-ecd99897faab.png)

**Comment by acacha** [comment]
I confirm this bug the original one example doesn't have this problem https://almsaeedstudio.com/themes/AdminLTE/pages/examples/login.html

**Comment by fede91it** [comment]
CSS diversity is also with select2 plugin

**Comment by acacha** [comment]
@fede91it Sorry CSS diversity? I don't understand if you could explain to me please...

**Comment by fede91it** [comment]
Pardon, language barriers 😋

This is how a Select2 input is displayed in acacha/laravel:

![image](https://cloud.githubusercontent.com/assets/346224/22348990/046860c6-e40e-11e6-975e-098103d0ba58.png)

And this is how a Select2 input appears in original AdminLTE2 theme, see this [example page](https://almsaeedstudio.com/themes/AdminLTE/pages/forms/advanced.html).
The select is shown with the same style of other inputs:



![image](https://cloud.githubusercontent.com/assets/346224/22349021/2ca2cdec-e40e-11e6-8c5c-1a304ba31608.png)

**Comment by acacha** [comment]
Ok @fede91it thanks for the example. Are you sure you manually (or using Laravel Elixir) css and javascripts for select 2? Acacha/adminlte-laravel package does not provide all css/js necessary to run all demo pages...

**Comment by acacha** [comment]
TODO to continue it seem problem with laravel styles i left seek for color:     /* color: #d2d6de; */

**Comment by fede91it** [comment]
Sure, in the page I included the required assets:

```html
<script src="{{ asset('plugins/select2/select2.full.min.js') }}"></script>
<link rel="stylesheet" href="{{ asset('plugins/select2/select2.min.css') }}"/>
```

**Comment by acacha** [comment]
Ok it seems to be resolved in last commit/tag I push to repository. Please prove in a new installation.

For no new fresh projects please run gulp watch. If still not works remove public/css folder, update gulpfile.js and re-run gulp.

**Comment by fede91it** [comment]
CSS style for texts is fixed.

What about Select2's style that differs from standard input's style?
