### ISSUE TITLE
Make compatible with Laravel 5.4

### ISSUE THREAD

**Issue by acacha** [acacha/adminlte-laravel#189]
First error found:

Illuminate\Console\AppNamespaceDetectorTrait  not found in /home/sergi/Code/borrar2/vendor/acacha/admin-lte-template-laravel/src/Providers/AdminLTETemplateServiceProvider.php on line 17

**Comment by jake-harris** [comment]
Looks like the name of the trait was [changed](
https://github.com/illuminate/console/commit/64d796bde4063f522fd5c7bc3c73484abccd79a8#diff-14f0b0d42154de56006d363cea4d7c45). 

I went to submit a PR but trying to run the tests went... not great, so I think I'd just end up generating more work than I'd save.

**Comment by Mahdi-Sahib** [comment]
when we see the new installation Gide for laravel 5.4

**Comment by acacha** [comment]
https://laravel.com/docs/5.4/upgrade

**Comment by acacha** [comment]
Last commit solved the issues. Test are also changed to by adapted to laravel 5.4 but you have to use dev-master version of package  https://github.com/laravel/browser-kit-testing till they create a new release/tag. see
