### ISSUE TITLE
Javascript not loading on auth view.

### ISSUE THREAD

**Issue by lmvalenzuela** [acacha/adminlte-laravel#191]
## Detailed description
BUG 
In a fresh laravel 5.4 installation, after running the 
````
php artisan make:adminUserSeeder
File /home/sergi/Code/AdminLTE/acacha/adminlte-laravel_test/database/seeds/AdminUserSeeder.php created.

php artisan adminlte:admin
File /home/sergi/Code/AdminLTE/acacha/adminlte-laravel_test/database/seeds/AdminUserSeeder.php created
User Sergi Tur Badenas(sergiturbadenas@gmail.com) with the environemnt password (env var ADMIN_PWD) created succesfully!
php artisan vendor:publish --tag=adminlte --force
...
````
The resulting view doesn't load the javascript scripts

## Context

Easily fixed by adding:

```
    @section('scripts')
        @include('adminlte::layouts.partials.scripts')
    @show
```
Before:
```
    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });
    </script>
```
In `resources/views/vendor/auth/logon.blade.php``

## Possible implementation

Guess the same code addition might be done to `vendor/acacha/admin-lte-template-laravel/login.blade.php` so when `php artisan vendor:publish --tag=adminlte --force` is runned the resulting file would load `app.js` script.

## Your environment

* Version used laravel 5.4:
* Operating system and version (e.g. Ubuntu 16.04, Windows 7):MacOSX Sierra

**Comment by acacha** [comment]
Sorry I cannot reproduce the problem and I don't understan how commands make:adminUserSeeder and adminlte:admin are related to the bug? 

And as you can see at https://github.com/acacha/adminlte-laravel/blob/master/resources/views/auth/login.blade.php

Auth views use a custom partial script file:

    @include('adminlte::layouts.partials.scripts_auth')

So I don't understan how to reproduce the problem. 

As I said i follow the steps:

```bash
laravel new testCSSPROBLEMSAdminLTE
cd testCSSPROBLEMSAdminLTE
llum boot
adminlte-laravel install
```
