### ISSUE TITLE
Suport Laravel mix - before (when you will use webpack.mix instead of gulp)

### ISSUE THREAD

**Issue by Mahdi-Sahib** [acacha/adminlte-laravel#194]

**Comment by acacha** [comment]
As soon as I can. Feel free to open a PR if you have a solution

**Comment by acacha** [comment]
Issue submmited at laravel/mix: https://github.com/JeffreyWay/laravel-mix/issues/212

**Comment by acacha** [comment]
Done https://github.com/acacha/adminlte-laravel/commit/ecc0af404f4a3290098f088d430bdcbe400d9282
