### ISSUE TITLE
select multiple show only the last option selected

### ISSUE THREAD

**Issue by lcfc** [acacha/adminlte-laravel#200]
when I edit a form with a multiple select and multiple options are selected, only the last is show as selected (but in the source the options are selected correctly). For a moment i see all the options correctly, but then it seems reload an select only the last.
This when I use the app.js; if I use jquery and bootstrap js from their cdn, it works as aspected.

**Comment by acacha** [comment]
Could you provide us an example code?

**Comment by hlebarovLuckylabz** [comment]
<select class="form-control" id="operatorWebsiteLangs" name="websiteLangsID[]" multiple="multiple">
    <option selected="selected" value="1">opt1</option>
    <option selected="selected" value="2">opt2</option>
</select>

There you go... Its quite annoying

**Comment by v10dynamite** [comment]
I have the same issue, any ideas?
