### ISSUE TITLE
Test for php7 before recommending Spatie menu.

### ISSUE THREAD

**Issue by raarts** [acacha/adminlte-laravel#201]
## Detailed description

I ran `php artisan make:mvc mvctest`. The last line printed was:

`Spatie menu is not installed. Use command php artisan adminlte:menu to install.`

But I'm not running php 7. I ran `php artisan adminlte:menu` and later I saw that indeed printed an error (which I missed), but in spite of that error it still continued. Which resulted in a botched-up system. 

## Context

It will save other people like me time.

## Possible implementation

Either check for php 7 or spell out it depends on it.

## Your environment

PHP 5.6.x

**Comment by acacha** [comment]
But this is documented on README no? 

https://github.com/acacha/adminlte-laravel/blob/master/README.md#adminltemenu--adminlte-laravelmenu

So what you propose exactly? Maybe could you make a PR?

Thanks!

**Comment by raarts** [comment]
Yes, I missed that too. And when thinking about it, my request is probably over the top. 
Let's just close this issue.
