### ISSUE TITLE
i got "npm run dev" error

### ISSUE THREAD

**Issue by batty211** [acacha/adminlte-laravel#204]
## Update!!!!!  i fixed it
i copied /font from public to /resourse/assets
and 
/resources/assets/less/adminlte-app.less
before

```
@import "../../../node_modules/admin-lte/build/less/AdminLTE.less";

> @boxed-layout-bg-image-path: "../../dist/img/boxed-bg.jpg";

```
after

```
> @boxed-layout-bg-image-path: "../../dist/img/boxed-bg.jpg";

@import "../../../node_modules/admin-lte/build/less/AdminLTE.less";
```

i moved @boxed-layout-bg-image-path before imort ...AdminLTE.less

## But i've got

Login and Register Page have no style

Look this images
![Alt tag](http://i.imgur.com/A0QMY2e.png)
[](http://imgur.com/a/Mesle)

but i can fix it by run
`php artisan vendor:publish --tag=adminlte --force`
again

##  Description
when i run `npm run dev` in project root i got error

![Alt tag](http://i.imgur.com/LiBiQAl.png)

[](http://imgur.com/a/Tz63S)

```
ERROR  Failed to compile with 12 errors

These dependencies were not found in node_modules:

* ../img/boxed-bg.jpg
* ../fonts/ionicons.eot?v=3.0.0-alpha.3
* ../fonts/ionicons.woff2?v=3.0.0-alpha.3
* ../fonts/ionicons.woff?v=3.0.0-alpha.3
* ../fonts/ionicons.ttf?v=3.0.0-alpha.3
* ../fonts/ionicons.svg?v=3.0.0-alpha.3
* ../fonts/fontawesome-webfont.eot?v=4.7.0
* ../fonts/fontawesome-webfont.eot
* ../fonts/fontawesome-webfont.woff2?v=4.7.0
* ../fonts/fontawesome-webfont.woff?v=4.7.0
* ../fonts/fontawesome-webfont.ttf?v=4.7.0
* ../fonts/fontawesome-webfont.svg?v=4.7.0
```
before run dev i installed dependencies file font-awesome 4.7.0 , ionicons,...

## environment
* PHP 5.6 Laravel 5.4
* OS Windows 10(64 bit)

**Comment by acacha** [comment]
Sorry for the inconvenience thuis bug is solved in last tagged version so update your package or try with a new fresh installation.
