### ISSUE TITLE
Fresh Installation has Layout Problem

### ISSUE THREAD

**Issue by clebersa** [acacha/adminlte-laravel#209]
Hi,

I am trying to create a fresh installation for Acacha/AdminLTE-Laravel and something is not right. The page does not have the layout like in the demo and the icons do not work.

## Detailed description

I have a project with Acacha/AdminLTE-Laravel and I would like to update it as the version I have has some bugs that were fixed recently. Instead of updating the project without a new installation, which **I do not know how to do and I would appreciate if someone tells me how to do that**, I am creating a new installation of Acacha/AdminLTE-Laravel and moving my files to the new project. I do not have a lot of files, so, this is not very difficult to do.

The problem is that the page for a fresh installation is not working properly due to some CSS issues, probably. I follow the tutorial on the README and run the following commands:
```
laravel new laravel-with-admin-lte
cd laravel-with-admin-lte
adminlte-laravel install
```
When I go to the login page, the icons do not show (only a blank square). When I log in, the home page looks weird, with the footer close to the navbar and the icons do not show again. (__I tried to upload screenshots, but Github did not recognize the files__).

When I run `adminlte-laravel install`, this is the output:
```
/home/vagrant/.config/composer/vendor/bin/llum package  AdminLTE
Running composer require acacha/admin-lte-template-laravel
Using version ^4.1 for acacha/admin-lte-template-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 7 installs, 0 updates, 0 removals
  - Installing symfony/dom-crawler (v3.2.4) Loading from cache
  - Installing laravel/browser-kit-testing (v1.0.3) Loading from cache
  - Installing creativeorange/gravatar (1.0.10) Loading from cache
  - Installing acacha/user (0.2.2) Loading from cache
  - Installing acacha/helpers (0.1.3) Loading from cache
  - Installing acacha/filesystem (0.1.1) Loading from cache
  - Installing acacha/admin-lte-template-laravel (4.1.2) Loading from cache
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
The compiled services file has been removed.
sed: couldn't flush stdout: Broken pipe
File /vagrant/www/html/laravel-with-admin-lte/config/app.php updated correctly
File /vagrant/www/html/laravel-with-admin-lte/config/services.php updated correctly
Adding Acacha\AdminLTETemplateLaravel\Providers\AdminLTETemplateServiceProvider::class to Laravel config app.php file
Adding Acacha\AdminLTETemplateLaravel\Facades\AdminLTE::class to Laravel config app.php file
Copied File [/vendor/acacha/admin-lte-template-laravel/src/stubs/HomeController.stub] To [/app/Http/Controllers/HomeController.php]
Copied File [/vendor/acacha/admin-lte-template-laravel/src/stubs/RegisterController.stub] To [/app/Http/Controllers/Auth/RegisterController.php]
Copied File [/vendor/acacha/admin-lte-template-laravel/src/stubs/LoginController.stub] To [/app/Http/Controllers/Auth/LoginController.php]
Copied File [/vendor/acacha/admin-lte-template-laravel/src/stubs/ForgotPasswordController.stub] To [/app/Http/Controllers/Auth/ForgotPasswordController.php]
Copied File [/vendor/acacha/admin-lte-template-laravel/src/stubs/ResetPasswordController.stub] To [/app/Http/Controllers/Auth/ResetPasswordController.php]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/public/img] To [/public/img]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/public/css] To [/public/css]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/public/js] To [/public/js]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/public/plugins] To [/public/plugins]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/public/fonts] To [/public/fonts]
Copied File [/vendor/acacha/admin-lte-template-laravel/public/mix-manifest.json] To [/public/mix-manifest.json]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/resources/views/auth] To [/resources/views/vendor/adminlte/auth]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/resources/views/auth/emails] To [/resources/views/vendor/adminlte/auth/emails]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/resources/views/errors] To [/resources/views/vendor/adminlte/errors]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/resources/views/layouts] To [/resources/views/vendor/adminlte/layouts]
Copied File [/vendor/acacha/admin-lte-template-laravel/resources/views/home.blade.php] To [/resources/views/vendor/adminlte/home.blade.php]
Copied File [/vendor/acacha/admin-lte-template-laravel/resources/views/welcome.blade.php] To [/resources/views/welcome.blade.php]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/resources/assets/css] To [/resources/assets/css]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/resources/assets/img] To [/resources/assets/img]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/resources/assets/less] To [/resources/assets/less]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/resources/assets/sass] To [/resources/assets/sass]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/resources/assets/js] To [/resources/assets/js]
Copied File [/vendor/acacha/admin-lte-template-laravel/webpack.mix.js] To [/webpack.mix.js]
Copied File [/vendor/acacha/admin-lte-template-laravel/package.json] To [/package.json]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/tests] To [/tests]
Copied File [/vendor/acacha/admin-lte-template-laravel/phpunit.xml] To [/phpunit.xml]
Copied File [/vendor/creativeorange/gravatar/config/gravatar.php] To [/config/gravatar.php]
Copied File [/vendor/acacha/admin-lte-template-laravel/config/adminlte.php] To [/config/adminlte.php]
Copied File [/vendor/acacha/admin-lte-template-laravel/routes/web.php] To [/routes/web.php]
Copied File [/vendor/acacha/admin-lte-template-laravel/routes/api.php] To [/routes/api.php]
Publishing complete.
```
As you can see, on the line 21, there is an error. Maybe that is the problem.

I already tried to `php artisan vendor:publish --tag=adminlte --force` and update composer (`composer global update`), but the problem remains.

## Your environment
I am using a Linux VM (Ubuntu 16.04) with Vagrant (v1.9.1). The VM has Apache (v2.4.7) and PHP (v2.6.29). I did not set up apache to look just for the public folder so far. That's why I have to specify the public folder in the URL.

Thank you for your time.
I look forward for your feedback.

Have a good day.

**Comment by acacha** [comment]
I'm not sure to understand your problem. A completely new fresh installation does not works? I try it now a new fresh installation and no errors occurs to me.

About the error:

sed: couldn't flush stdout: Broken pipe

It seems a problem with llum which is using sed but I need more info to reproduce the error...

If your are migrating and existing project you have to take into care a Lot os things for example are you migrating from Laravel 5.3 to 5.4? 

If you have errors with assets (css, icons, fonts, js, etc) you have to be sure to use a public folder exactly the same in this github repo. You can also try using laravel mix:

```
npm run dev
```

To re-create assets in public folder. But before be sure you have the correct/new files in resources folder.

**Comment by clebersa** [comment]
Hi Sergi,

> I'm not sure to understand your problem. A completely new fresh installation does not works? I try it now a new fresh installation and no errors occurs to me.

Yes, a new fresh installation is not working for me. It has layout issues. I finally can upload images here. So, my login screen looks like this:
![1](https://cloud.githubusercontent.com/assets/7107733/23226323/e8c54116-f913-11e6-9479-68964711ec43.png)

And the home screen (after logged), look like this:
![3](https://cloud.githubusercontent.com/assets/7107733/23226477/6b48830a-f914-11e6-95e3-5a0ed2415fbb.png)

For comparison, the login page of my current application, which is not to the latest version of acacha repository and does not have the problems, looks like this:
![2](https://cloud.githubusercontent.com/assets/7107733/23226519/9d0bf200-f914-11e6-88e2-a837e9621d21.png)

Just to make sure, I created the new installation using the following commands:
```
composer global require "acacha/adminlte-laravel-installer=~3.0"
laravel new laravel-with-admin-lte
cd laravel-with-admin-lte
adminlte-laravel install
```

This is the output for the version of some of the software I am using:
`laravel --version` => `Laravel Installer version 1.3.5`
`adminlte-laravel --version` => `Acacha AdminLTE Installer version 3.1.11`
`php artisan --version` => `Laravel Framework 5.4.13`
`composer --version` => `Composer version 1.3.1 2017-01-07 18:08:51`

> It seems a problem with llum which is using sed but I need more info to reproduce the error...

I ran `adminlte-laravel install -vvv` to get a more verbose output, but no additional details could be seen. What would you recommend me to do to get more details for you to reproduce the error?

> If your are migrating and existing project you have to take into care a Lot os things for example are you migrating from Laravel 5.3 to 5.4?

I am not migrating my application now, in the first moment. I am trying to create a new application from the commands I said before. My old application, which uses Laravel 5.3, only has views so far. So, migrating it would not require a lot of effort, once I have only some Blades files in the `resources/views` folder.

> If you have errors with assets (css, icons, fonts, js, etc) you have to be sure to use a public folder exactly the same in this github repo. You can also try using laravel mix:
> ```
> npm run dev
> ```
> To re-create assets in public folder. But before be sure you have the correct/new files in resources folder.

I am trying to run the command, but I am getting some errors when I get it working wthout errors, I will post more information here.

Thanks, Sergi.

**Comment by acacha** [comment]
Seeing the images it seems a problem with icon fonts... Could you open Chrome developer Tools inspection and show us if any files are not found (maybe 404 not found errors?)

**Comment by acacha** [comment]
Also npm run dev will not thown any errors (after npm install of course) so if you can show us the errors it would help.

**Comment by acacha** [comment]
To debug error:

```
sed: couldn't flush stdout: Broken pipe
```

In your case adminlte-laravel it seems to use llum so the command executed is:

/home/vagrant/.config/composer/vendor/bin/llum package  AdminLTE

First try to update llum:

```
composer global update
```

or:

```
composer global update
```

lum is a symfony command. Package subcommand command code could be found at:

```
/home/sergi/.composer/vendor/acacha/llum/src/Console/PackageCommand.php
```

LLum package is simple a command to do the three common steps in Laravel package installation

1) composer require
2) Add service provider to config/app.ph (and optionally facades)
3) (optional) run additional commands

In your case if you see file:

https://github.com/acacha/llum/blob/master/src/config/packages.php

The steps are:

```

    'AdminLTE' => [
        'name'      => 'acacha/admin-lte-template-laravel',
        'providers' => ['Acacha\AdminLTETemplateLaravel\Providers\AdminLTETemplateServiceProvider::class'],
        'aliases'   => ['AdminLTE' => 'Acacha\AdminLTETemplateLaravel\Facades\AdminLTE::class'],
        'after'     => 'php artisan adminlte-laravel:publish --force',
    ],
```

Sed command is only used in step 2. Can you show us your config/app.php file? This file is modified by this package to include #llum_providers and #llum_aliases (placeholder to assist package installing aliases and providers)

See https://github.com/acacha/adminlte-laravel/blob/master/src/stubs/app.php.stub

**Comment by clebersa** [comment]
Hi Sergi! Thank you for your help. I am going through your messages and doing what you asked. I appreciate your help!

> Seeing the images it seems a problem with icon fonts... Could you open Chrome developer Tools inspection and show us if any files are not found (maybe 404 not found errors?)

![screenshot from 2017-02-28 10-47-47](https://cloud.githubusercontent.com/assets/7107733/23407717/115d2e6a-fda4-11e6-8b4d-5fbac1afba98.png)


As you can see in the screenshot, I get the error 404 for some components. I am working to fix the problem, which I believe can be solved when `npm run dev` runs successfully. 

> Also npm run dev will not thown any errors (after npm install of course) so if you can show us the errors it would help.

I will struggle a little more to fix the errors thrown by `npm run dev`. Then I will let you know the result.

Thanks.

**Comment by clebersa** [comment]
Hi again,

I have some good news. I got `npm run dev` with no errors. I realized my npm was out of date and after updating it to version 4.3.0 (latest), I was able to run `npm install` and `npm run dev` with no errors. However, I had to perform my commands in the following order:
```
laravel new test4
cd test4
npm install
adminlte-laravel install
npm install
npm run dev
```

When I ran the first `npm install`, I got the following WARN messages, though:
```
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global node-gyp@3.5.0 should be installed with -g
...
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

When I ran the second `npm install`, I got the following WARN messages as well:
```
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
...
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

About `llum`, thanks to your message, I was able to perform the command `adminlte-laravel install` with no errors. That `sed: couldn't flush stdout: Broken pipe` error do not happen anymore. My llum was out of date.

About my `config/app.php` file, It looks like below:
```php
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Application Name
    |--------------------------------------------------------------------------
    |
    | This value is the name of your application. This value is used when the
    | framework needs to place the application's name in a notification or
    | any other location as required by the application or its packages.
    */

    'name' => 'Laravel',

    /*
    |--------------------------------------------------------------------------
    | Application Environment
    |--------------------------------------------------------------------------
    |
    | This value determines the "environment" your application is currently
    | running in. This may determine how you prefer to configure various
    | services your application utilizes. Set this in your ".env" file.
    |
    */

    'env' => env('APP_ENV', 'production'),

    /*
    |--------------------------------------------------------------------------
    | Application Debug Mode
    |--------------------------------------------------------------------------
    |
    | When your application is in debug mode, detailed error messages with
    | stack traces will be shown on every error that occurs within your
    | application. If disabled, a simple generic error page is shown.
    |
    */

    'debug' => env('APP_DEBUG', false),

    /*
    |--------------------------------------------------------------------------
    | Application URL
    |--------------------------------------------------------------------------
    |
    | This URL is used by the console to properly generate URLs when using
    | the Artisan command line tool. You should set this to the root of
    | your application so that it is used when running Artisan tasks.
    |
    */

    'url' => env('APP_URL', 'http://localhost'),

    /*
    |--------------------------------------------------------------------------
    | Application Timezone
    |--------------------------------------------------------------------------
    |
    | Here you may specify the default timezone for your application, which
    | will be used by the PHP date and date-time functions. We have gone
    | ahead and set this to a sensible default for you out of the box.
    |
    */

    'timezone' => 'UTC',

    /*
    |--------------------------------------------------------------------------
    | Application Locale Configuration
    |--------------------------------------------------------------------------
    |
    | The application locale determines the default locale that will be used
    | by the translation service provider. You are free to set this value
    | to any of the locales which will be supported by the application.
    |
    */

    'locale' => 'en',

    /*
    |--------------------------------------------------------------------------
    | Application Fallback Locale
    |--------------------------------------------------------------------------
    |
    | The fallback locale determines the locale to use when the current one
    | is not available. You may change the value to correspond to any of
    | the language folders that are provided through your application.
    |
    */

    'fallback_locale' => 'en',

    /*
    |--------------------------------------------------------------------------
    | Encryption Key
    |--------------------------------------------------------------------------
    |
    | This key is used by the Illuminate encrypter service and should be set
    | to a random, 32 character string, otherwise these encrypted strings
    | will not be safe. Please do this before deploying an application!
    |
    */

    'key' => env('APP_KEY'),

    'cipher' => 'AES-256-CBC',

    /*
    |--------------------------------------------------------------------------
    | Logging Configuration
    |--------------------------------------------------------------------------
    |
    | Here you may configure the log settings for your application. Out of
    | the box, Laravel uses the Monolog PHP logging library. This gives
    | you a variety of powerful log handlers / formatters to utilize.
    |
    | Available Settings: "single", "daily", "syslog", "errorlog"
    |
    */

    'log' => env('APP_LOG', 'single'),

    'log_level' => env('APP_LOG_LEVEL', 'debug'),

    /*
    |--------------------------------------------------------------------------
    | Autoloaded Service Providers
    |--------------------------------------------------------------------------
    |
    | The service providers listed here will be automatically loaded on the
    | request to your application. Feel free to add your own services to
    | this array to grant expanded functionality to your applications.
    |
    */

    'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        /*
         * Acacha Llum Service Providers...
         *
         * See: https://github.com/acacha/llum
         */
        Acacha\AdminLTETemplateLaravel\Providers\AdminLTETemplateServiceProvider::class,
        #llum_providers

        /*
         * Package Service Providers...
         */
        Laravel\Tinker\TinkerServiceProvider::class,

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,

    ],

    /*
    |--------------------------------------------------------------------------
    | Class Aliases
    |--------------------------------------------------------------------------
    |
    | This array of class aliases will be registered when this application
    | is started. However, feel free to register as many as you wish as
    | the aliases are "lazy" loaded so they don't hinder performance.
    |
    */

    'aliases' => [

        'App' => Illuminate\Support\Facades\App::class,
        'Artisan' => Illuminate\Support\Facades\Artisan::class,
        'Auth' => Illuminate\Support\Facades\Auth::class,
        'Blade' => Illuminate\Support\Facades\Blade::class,
        'Broadcast' => Illuminate\Support\Facades\Broadcast::class,
        'Bus' => Illuminate\Support\Facades\Bus::class,
        'Cache' => Illuminate\Support\Facades\Cache::class,
        'Config' => Illuminate\Support\Facades\Config::class,
        'Cookie' => Illuminate\Support\Facades\Cookie::class,
        'Crypt' => Illuminate\Support\Facades\Crypt::class,
        'DB' => Illuminate\Support\Facades\DB::class,
        'Eloquent' => Illuminate\Database\Eloquent\Model::class,
        'Event' => Illuminate\Support\Facades\Event::class,
        'File' => Illuminate\Support\Facades\File::class,
        'Gate' => Illuminate\Support\Facades\Gate::class,
        'Hash' => Illuminate\Support\Facades\Hash::class,
        'Lang' => Illuminate\Support\Facades\Lang::class,
        'Log' => Illuminate\Support\Facades\Log::class,
        'Mail' => Illuminate\Support\Facades\Mail::class,
        'Notification' => Illuminate\Support\Facades\Notification::class,
        'Password' => Illuminate\Support\Facades\Password::class,
        'Queue' => Illuminate\Support\Facades\Queue::class,
        'Redirect' => Illuminate\Support\Facades\Redirect::class,
        'Redis' => Illuminate\Support\Facades\Redis::class,
        'Request' => Illuminate\Support\Facades\Request::class,
        'Response' => Illuminate\Support\Facades\Response::class,
        'Route' => Illuminate\Support\Facades\Route::class,
        'Schema' => Illuminate\Support\Facades\Schema::class,
        'Session' => Illuminate\Support\Facades\Session::class,
        'Storage' => Illuminate\Support\Facades\Storage::class,
        'URL' => Illuminate\Support\Facades\URL::class,
        'Validator' => Illuminate\Support\Facades\Validator::class,
        'View' => Illuminate\Support\Facades\View::class,

        /*
         * Acacha Llum Aliases...
         *
         * See: https://github.com/acacha/llum
         */
        'AdminLTE' => Acacha\AdminLTETemplateLaravel\Facades\AdminLTE::class,
        #llum_aliases

    ],

];
```
Is the `packages.php` file suppose to exist inside my project by the end of the execution of the commands I listed above? I tried to find it (`find . -name packages.php`) and I did not find it.

Anyways, even after not getting errors from npm and llum anymore, my application still does not get the icons and layout correctly. The original problem remains. I looked to the landing page, and some files are not found as well (404).

Thanks.

**Comment by riquerolim** [comment]
I have the same problem
![image](https://cloud.githubusercontent.com/assets/25722819/23705772/bb110dbc-03e1-11e7-9654-5f0fed45f324.png)

Help me please

**Comment by clebersa** [comment]
Hi guys, 

I found and solved the problem. For the `app-landing.js` and `app.js`, the problem is caused by the `mix` function in the `./vendor/laravel/framework/src/Illuminate/Foundation/helpers.php` file. This funcion receives the URL for those `js` files but it does not return a valid URL to the browser, generating the 404 error. Instead of using the `mix` function, I used the `asset` function and removed the first slash of the URL passed to the function. The changes I made are:

- `./vendor/acacha/admin-lte-template-laravel/resources/views/layouts/landing.blade.php`:

From:
```html
<script src="{{ mix('/js/app-landing.js') }}"></script>
```
To:
```html
<script src="{{ asset('js/app-landing.js') }}"></script>
```

- `./vendor/acacha/admin-lte-template-laravel/resources/views/layouts/partials/scripts.blade.php`:

From:
```html
<script src="{{ mix('/js/app.js') }}" type="text/javascript"></script>
```
To
```html
<script src="{{ asset('js/app.js') }}" type="text/javascript"></script>
```

- `./resources/views/vendor/adminlte/layouts/partials/scripts.blade.php`:

From:
```html
<script src="{{ mix('/js/app.js') }}" type="text/javascript"></script>
```
To:
```html
<script src="{{ asset('js/app.js') }}" type="text/javascript"></script>
```

For the icons and fonts, the problem was a bit different. I noticed that previous versions of AdminLTE Laravel were using something like:
```css
src: url('../fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('../fonts/glyphicons-halflings-regular.woff') format('woff'), url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
```
and now they are using something like this:
```css
src: url(/fonts/glyphicons-halflings-regular.eot?f4769f9bdb7466be65088239c12046d1) format("embedded-opentype"), url(/fonts/glyphicons-halflings-regular.woff2?448c34a56d699c29117adc64c43affeb) format("woff2"), url(/fonts/glyphicons-halflings-regular.woff?fa2772327f55d8198301fdb8bcfc8158) format("woff"), url(/fonts/glyphicons-halflings-regular.ttf?e18bbf611f2a2e43afc071aa2f4e1512) format("truetype"), url(/fonts/glyphicons-halflings-regular.svg?89889688147bd7575d6327160d64e760) format("svg");
```
So, I fixed the 404 error by specifying the URL for the icons and font like they used to be, using `url(../fonts/...)` instead of `url(/fonts/...)`. The single quote does not seem to have effect here. By the end of my action, I changed it in the following files:
- `./vendor/acacha/admin-lte-template-laravel/public/css/all-landing.css`
- `./vendor/acacha/admin-lte-template-laravel/public/css/bootstrap.css`
- `./vendor/acacha/admin-lte-template-laravel/public/css/all.css`
- `./vendor/acacha/admin-lte-template-laravel/public/css/app.css`

Then republish your files through the command `php artisan vendor:publish --tag=adminlte --force` and it should work.

So, @acacha, should I submit those changes as a pull request for the AdminLTE Laravel project?

Have a good night, guys.

**Comment by acacha** [comment]
Thanks @clebersa for you explanation very nice! Feel free to create a PR but I'm not sure why mix helper is not working i used it because I think is needed to support hot reload see https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/helpers.php

So I think we have to investigate a litle more about the problem....

**Comment by kingofswing** [comment]
Your environment

I am using a Linux VM (Ubuntu 16.04) with Vagrant (v1.9.1). The VM has Apache (v2.4.7) and PHP (v2.6.29). I did not set up apache to look just for the public folder so far. That's why I have to specify the public folder in the URL.


Is it because of the 'wrong' documentRoot of Apache ? I'm new to acacha , hope to find more tutorial to learn after the installation of this great package , thanks for your work @acacha , 
and don't know to how to in the next step (just modified  email field of  the password-resets migration php file, and can register new user and login .)

**Comment by clebersa** [comment]
Hello guys!

Well, I have some news about this thread.

So, after our friend @kingofswing commented about setting Apache to serve the application using the `public` folder, I decided to do the same for my application as I would need to do that sometime before deploying it in the production server. In case @kingofswing want some help about that, here it comes some details:
>If you change the DocumentRoot on Apache to the `public` folder of your project, which can be done by editing the file `/etc/apache2/sites-available/000-default.conf` (in my case), you will access your application through the server name or IP of your server. Restart Apache after that and it's done.
> In my case, though, I needed my application to accessible through a specific name after the server name or IP, like `192.168.0.10/myapp/`. In order to achieve that, I 
> - placed the laravel project in the folder `/var/www`;
> - created an alias for my project folder by adding the line `Alias /myapp "/vagrant/var/www/myapp/public"` in the file `/etc/apache2/apache2.conf`;
> - added the line `RewriteBase /myapp/` right before the line `RewriteEngine On` in the file `public/.htaccess` of my project;
> - restarted Apache.

Okay, back to the original problem, as I reported in my last comment on this thread, I would remove the `mix` function to fix part of the problem. However, I found out that serving my application using the `public` folder in the URL was making things work bad for the `mix` function. After fixing the way my application was being server (as shown above), I found a way to keep the `mix` function, as @acacha said it is important. Instead of removing it, it is enough to use it with a `./` before the URL itself:
```html
<script src="./{{ mix('/js/app.js') }}" type="text/javascript"></script>
```

For the fonts resources in the CSS files, the solution was the same I proposed in my last comment.

This works for both ways of serving the application (through the server name only or with an alias). Thus, I think it won't bring problems for people who already use Acacha AdminLTE Laravel.

I will submit my PR soon. I hope @acacha accepts it!

Bye.
