### ISSUE TITLE
Social login on demo page not working

### ISSUE THREAD

**Issue by exwizzard** [acacha/adminlte-laravel#212]
## Detailed description

I went to your demo page and I tried to login with my github account and I get this error:

QueryException in Connection.php line 647: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null (SQL: insert into `users` (`name`, `email`, `updated_at`, `created_at`) values (, myemail@email.com, 2017-03-11 18:17:00, 2017-03-11 18:17:00))

**Comment by acacha** [comment]
Agh ok I see Github allows users without name so I've to check that
