### ISSUE TITLE
Need more details for installing on existing project.

### ISSUE THREAD

**Issue by cojocaru3** [acacha/adminlte-laravel#213]
Hello, can you please provide some more details on Installing AdminLTE over an existing Laravel 5.4 Project ?
I see I should use Llum, but it still feels like lot of details are lacking.
If you could make a short tutorial, that would be fantastic.
Thank you !

**Comment by acacha** [comment]
@cojocaru3 It depends on what means "Existing project"... the problem will be files/code adminlte Laravel will overwrite so you ahve to be carefull.

My recommendation: create a copy of your project and the install there adminlte laravel using adminlte-laravel install command. If you use git you can use git status to check wich files adminlte overwrites.
