### ISSUE TITLE
Problem integration with yajaira datatable 

### ISSUE THREAD

**Issue by adrianlaraperez88** [acacha/adminlte-laravel#214]
## Detailed description

Problem integration with yajaira datatable . Problem with bootstrap or Jquery in laravel 5.4

* Version used (e.g. PHP 5.6, HHVM 3):
*  Ubuntu 16.04

**Comment by acacha** [comment]
Sorry but I need more info, which problem do you have?

**Comment by adrianlaraperez88** [comment]
When I try to integrate with datatable yajra it stops working some components since I have add jquery and boostrap because the one you put in the package does not work for me. I use laravel 5.4

**Comment by adrianlaraperez88** [comment]
I need to know what version of jquery boostrap (to use) since it gives me problems

**Comment by karmendra** [comment]
Basically, how do we make `yajra/laravel-datatables` work with `acacha/adminlte-laravel`?
where do I place the `<script src="/vendor/datatables/buttons.server-side.js"></script>` and `{!! $dataTable->scripts() !!}`. 

When I place these scripts in `resources/views/vendor/adminlte/layouts/partials/scripts.blade.php` I get following error

    users:389 Uncaught TypeError: $(...).DataTable is not a function
    
I need to place these scripts after adminlte loads datatables plugin.

Any help appreciated.
