### ISSUE TITLE
Migrate Causes Syntax error or access violation: 1071

### ISSUE THREAD

**Issue by mayconfsbrito** [acacha/adminlte-laravel#215]
## Detailed description
When I try to migrate a adminlte-laravel fresh install, some mysql errors and pdo exceptions happen:

[maycon@localhost sicae]$ php artisan migrate
Migration table created successfully.
                                                                                                        
  [Illuminate\Database\QueryException]                                                                  
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length i  
  s 767 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))                       
                                                                                                        
  [PDOException]                                                                                        
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length i  
  s 767 bytes 

## Your environment

* Version used (e.g. PHP 7.1 with Docker):
* Operating system and version (Fedora 24):

**Comment by kingofswing** [comment]
I modified the .env  and tried to use mysql as users db, and found the same error during migaration. 
you'll find that after migration  , the password-resets table was not created . so ,  for me , I just 
tried to modified the second migration....php file : remove ->index() after email FIELD:

class CreatePasswordResetsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('password_resets', function (Blueprint $table) {
            $table->string('email');
            $table->string('token');
            $table->timestamp('created_at')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('password_resets');
    }
}

=== then php artisan migration would be ok

**Comment by kingofswing** [comment]
after I checked this article : https://laravel-news.com/laravel-5-4-key-too-long-error

php artisan migrate
Migration table created successfully.
Migrated: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_100000_create_password_resets_table
myMBPro:laravel-with-admin-lte shenwenchang$ 

migration is finally ok. hope it is helpful.

**Comment by mayconfsbrito** [comment]
Yes! 

The problem was solved just like the guide that you showed. 
I've changed the boot() method of the AppServiceProvider.

```
use Illuminate\Support\Facades\Schema;

public function boot()
{
    Schema::defaultStringLength(191);
}
```

Thank you!
