### ISSUE TITLE
installation doesnot work

### ISSUE THREAD

**Issue by manhag** [acacha/adminlte-laravel#216]
i am trying to install this packge using composer

steps :
1- open SSH 
2- browse to specific folder
3- execute this  `composer global require "acacha/adminlte-laravel-installer=~3.0"`

> Changed current directory to /root/.composer
> Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Nothing to install or update
> Generating autoload files
> 
  
> Nothing to install or update

what i have to do ?
is there any missing steps ?

**Comment by acacha** [comment]
See the Readme please at https://github.com/acacha/adminlte-laravel section Installation an Use.

**Comment by manhag** [comment]
first step i did
3- execute this composer global require "acacha/adminlte-laravel-installer=~3.0"

and the result AS shown 

then i tried to do this  `laravel` new laravel-with-admin-lte

but larvel is not defined

**Comment by clebersa** [comment]
Hi @manhag,

It seems like you do not have laravel installed on your computer yet. Try installing it based on this page: https://laravel.com/docs/5.4/installation

Also, it seems like you were using root to create your projects. This is not recommended. You should use a regular user and not use `sudo` for the commands like `laravel new my-project`. Make sure to set the folder permissions if necessary.

Let us know if that works for you.
Good luck!

**Comment by acacha** [comment]
Ok @manhag now I see as @clebersa say it seems you don't have laravel installed (or may you installed it but have to configure path to bin laravel file)
