### ISSUE TITLE
Executing artisan make:menu fails

### ISSUE THREAD

**Issue by philip** [acacha/adminlte-laravel#217]
## Detailed description

Executing `make:menu` is failing. Following the README I end up doing this:

`$ php artisan make:menu /contact`

And see:

```
sed: can't read /path/to/laravel-with-admin-lte/config/menu.php: No such file or directory`
Menu /contact added to /path/to/laravel-with-admin-lte/config/menu.php.`
```
I'm a laravel newbie so am likely doing something wrong, but the error is confusing because the menu is not added as that file does not exist (nor is it created).

Note: creating the route/view worked fine e.g., `php artisan make:route contact`. Also, after seeing the error, I blindly installed laravel-menu via `composer require spatie/laravel-menu` but it didn't change matters.

## Possible implementation

This might be a simple documentation issue for laravel newbies like myself.

## Your environment
* PHP 7.0.14
* macOS 10.12.4 beta
* Brand new project
* llum boot
* `brew install gnu-sed --with-default-names` was executed, and `sed --v` shows `sed (GNU sed) 4.4`

**Comment by philip** [comment]
Update: seems executing `php artisan adminlte:menu` is required first to allow `make:menu` to work. At least, now `config/menu.php` exists and is being updated. That said, it's still loading `resources/views/vendor/adminlte/layouts/partials/sidebar.blade.php` instead of `config/menu.php` but at least I'm inching closer. 

I'll pause now and instead spend time learning laravel.

**Comment by acacha** [comment]
Hi Philip, It seems you don't have file config/menu.php. This file is installed using:

 $ php artisan adminlte:menu

But this command will not work if you already installed spatie/laravel-menu package. So uninstall and remove this package for config/app.php file and run command.

You can also configure all manually without adminlte:menu option:

- Install and configure spatie/laravel-menu (remember to register serviceprovider)
- Manually copy new menu and sidebar files:
- Sidebar from package  /resources/views/layouts/partials/sidebar_with_spatie_menu.blade.php' to you app resources/views/vendor/adminlte/layouts/partials/sidebar.blade.php
- Menu config from package config/menu.php to config/menu.php

You could see what comamands does at:
- https://github.com/acacha/adminlte-laravel/blob/master/src/Console/AdminLTEMenu.php
- https://github.com/acacha/adminlte-laravel/blob/master/src/AdminLTE.php

**Comment by philip** [comment]
@acacha Thank you for the detailed response, much appreciated. All is working now :)
