### ISSUE TITLE
Bug sidebar menu.php

### ISSUE THREAD

**Issue by moreiraandre** [acacha/adminlte-laravel#223]
Hello, I'm new here.

## Detailed description

I could notice that after running the php artisan adminlte: menu or adminlte-laravel: menu the view that is copied to the resource/view folder presents a problem when I click on the top to minimize the menu, where the links do not fit the bar minimized.

**Comment by acacha** [comment]
Sorry for the delay @moreiraandre . Could you please provide us with more info? Do you think is a problem with this package or maybe is a general problem with adminlte? see https://github.com/almasaeed2010/AdminLTE

**Comment by moreiraandre** [comment]
Hello, it's a problem with the package! I did some tests and realized that the package does not generate the menu with the HTML formatting that AdminLTE needs, the menu does not involve the text in the span tag nor does it use an icon to signal the link when the menu is minimized.

**Comment by acacha** [comment]
Please could you provide us with a code example with the correct format for menu? I will try to fix this issue . Also if you wish you could make a PR.

**Comment by moreiraandre** [comment]
AdminLTE example:
`<a href="#"><i class="fa fa-link"></i> <span>Home</span></a>`

Html Menu Generator for Laravel  example:
`<a href="#">Home</a>`

I found a function in the menu that makes it possible to add raw html:
Html :: raw ('`<a href="#"><i class="fa fa-link"></i> <span>Home</span></a>`')
However the artisan command generates as I have exemplified before, it is necessary each time I run the command manually change the menu file to leave it in the default of AdminLTE.
I believe that to solve this the command of the artisan should generate a predefined icon of the awesome font and wrap the pure text in the span tags like in the first example.

I still do not know how to do a PR, but I will study to be able to help.

**Comment by acacha** [comment]
Ok thansk @moreiraandre for the example. So i think icon would be optional but If I understand it seems the only think I need to add is span so I Will try to solve asap.

**Comment by acacha** [comment]
Aghh ok now I see the icon is mandatory for menu when menu is collapsed! Working on a solution...

**Comment by acacha** [comment]
Solved https://github.com/acacha/adminlte-laravel/commit/fa9c16cc0245aae41fc11498110099e4aaa2bc5a
