### ISSUE TITLE
/js/app-landing.js file is a compiled file! Before: how to deal with 'Uncaught ReferenceError: jQuery is not defined     at pinterest_grid.js:157'

### ISSUE THREAD

**Issue by kingofswing** [acacha/adminlte-laravel#226]
## Detailed description

sorry for disturbing you all , maybe it's an easy step  , but I can't find how to do with it . 
after download a third party js file ,  include it at the end of `landing.blade.php`, after the 
`<script src="{{ URL::to('/') . mix('/js/app-landing.js') }}" type="text/javascript"></script>` line. 

`<script src="{{asset('/js/pinterest_grid.js')}}"></script>`

`<script type="text/javascript">`
    `$(document).ready(function(){`
        `$('#demo').pinterest_grid({`
           ` no_columns: 4,`
           ` padding_x: 10,`
           ` padding_y: 10,`
           ` margin_bottom: 50,`
           ` single_column_breakpoint: 700`
      `  });`
   ` });`
`</script>`

when loading the page,  the error arise in console. another error is 

`Uncaught TypeError: $(...).pinterest_grid is not a function`
    `at HTMLDocument.<anonymous> ((index):646)`
    `at mightThrow (app-landing.js:682)`
    `at process (app-landing.js:701)`

also , previously  tried to intergrate `Isotope` with the site, all the same error.  so I ask for help how to add third party js files or third javascript plugin correctly. (`pinterest_grid.js` is even not on the npm's repository, just search and download it from other sites).

any help would be greatly appreciated ! 

## Your environment

Laravel 5.4 w/ acacha adminlte
mac os x 10.11.x
using valet park or share 
php 7 is 7.x

**Comment by kingofswing** [comment]
I modified `jQuery`of `pinterest_grid.js`   to `$` , then no errors in console. 
`;(function ($, window, document, undefined) {`
`...`
`})( jQuery --> $, window, document);`

all the previous js file loading order still be the same as usual.

`<!-- Bootstrap core JavaScript`
`================================================== -->`
`<!-- Placed at the end of the document so the pages load faster -->`

`<script src="{{ URL::to('/') . mix('/js/manifest.js') }}" type="text/javascript"></script>`
`<script src="{{ URL::to('/') . mix('/js/vendor.js') }}" type="text/javascript"></script>`
`<script src="{{ URL::to('/') . mix('/js/app-landing.js') }}" type="text/javascript"></script>`

`<!-- pinterest-style grid layout -->`
`<script src="{{asset('/js/pinterest_grid.js')}}"></script>`

 so why the` jQuery` variable is still not available when loading `pinterest_grid.js`?

in resources/assets/js/bootstrap.js , we have : 

`window.$ = window.jQuery = require('jquery');`

**Comment by clebersa** [comment]
Hi @kingofswing,

Well, I did not create a test for your problem so I could replicate it. However, did you check if you have a variable with a name in the form `jQuery+<random number>` in your console?

Maybe your problem is similar to the one I described here: https://github.com/acacha/adminlte-laravel/issues/219#issuecomment-288767088. If that is the case, I would recommend you to solve the problem by adding your `pinterest_grid.js` to your project by using the `webpack.mix.js` file.

I hope that works for you.
Good luck!

**Comment by kingofswing** [comment]
I do find jquery object is a one with random number, see attached pics, but I don't have experience in how to integrate a thirty party javascript file into the bundle. could you explain a little bit in detail? cause I tried yesterday doing so but failed, the `pinterest_grid.js` even has even no version number, and it is not on the npm repositories. how to modify `wepack.mix.js` and other config files (maybe package.json if needed) 
<img width="516" alt="2017-04-018 28 05" src="https://cloud.githubusercontent.com/assets/16315386/24573540/e9d5e7e8-16b6-11e7-856f-ca6266a7fa59.png">

`jQuery+random number` object in Scope-Local-&-Global section of debug variable inspection window:

<img width="578" alt="2017-04-018 28 32" src="https://cloud.githubusercontent.com/assets/16315386/24573541/f1bead0a-16b6-11e7-88bd-2489dc24695c.png">
<img width="537" alt="2017-04-018 25 39" src="https://cloud.githubusercontent.com/assets/16315386/24573543/f6915076-16b6-11e7-8740-3b388be6465d.png">

**Comment by acacha** [comment]
Sorry for the delay! It has been very difficult to me to find/understand the problem until I see that file:

https://github.com/acacha/adminlte-laravel/blob/master/resources/assets/js/app-landing.js

is the compiled one not the original one so webpack is compiling an already compiled file so I think this is the reason for strange $jquery variable values. Today it was too late let me find some time to recover the original file

**Comment by acacha** [comment]
Personal note for myself:

It seems I have a local file with "correct" version? (please remember to check)

<pre>
$ head /home/sergi/Code/scool/curriculum_test/resources/assets/js/app-landing.js
/**
 * First we will load all of this project's JavaScript dependencies which
 * includes Vue and other libraries. It is a great starting point when
 * building robust, powerful web applications using Vue and Laravel.
 */

window.$ = window.jQuery = require('jquery');

require('bootstrap-less');
</pre>

**Comment by acacha** [comment]
Solved in last commits
