### ISSUE TITLE
Do you plan on keeping up with AdminLTE releases?

### ISSUE THREAD

**Issue by jpmurray** [acacha/adminlte-laravel#24]
Just curious, since there is a new version over at almasaeed2010/AdminLTE/releases if you plan on updating your package to new releases of AdminLTE ?

**Comment by acacha** [comment]
Yes as soon as I have a moment ;-) I accept Pull request too ;-)

**Comment by jpmurray** [comment]
I might look into it this weekend then! :)

**Comment by acacha** [comment]
Done! It will be available soon on new 2.0 release or in dev-master now!
