### ISSUE TITLE
username instead of email

### ISSUE THREAD

**Issue by exwizzard** [acacha/adminlte-laravel#243]
I have ran the command provided by instructions:

php artisan adminlte:username

The command was executed successfully and I can see in my auth.php file that  'field' => 'username'
The problem is that I still cannot login with a username, the reason is that the username field in database is empty. When registering a new account on the register page, it does not ask for a username to be entered. Is this something that I manually need to edit on the register page code?

**Comment by acacha** [comment]
Command:

php artisan adminlte:username

Works ok or give you any errors?

**Comment by exwizzard** [comment]
works ok
