### ISSUE TITLE
/js/app.js is too large 1.2MB

### ISSUE THREAD

**Issue by fbens** [acacha/adminlte-laravel#247]
After the file is generated, the size has exceeded 1.2MB, loading is particularly slow.
```
bash-3.2$ ls -lh
total 3672
-rw-r--r--  1 soul  staff   584K  4 19 23:21 app-landing.js
-rw-r--r--  1 soul  staff   1.2M  4 19 23:29 app.js
bash-3.2$ 

```

**Comment by acacha** [comment]
![image](https://user-images.githubusercontent.com/4015406/37416259-97eef7c2-27ad-11e8-9c4e-d67f6e32df58.png)

**Comment by acacha** [comment]
Solved using https://medium.com/@joeclever/three-simple-ways-to-inspect-a-webpack-bundle-7f6a8fe7195d
