### ISSUE TITLE
Can't locate path: /vendor/acacha/admin-lte-template-laravel/resources/views/auth/emails

### ISSUE THREAD

**Issue by esoriams** [acacha/adminlte-laravel#249]
## Detailed description

Since last week and after updating composer whenever i want to publish tag adminlte y get the error in the title, looks like this file has been removed from the repository or something is missing. 

I execute: php artisan vendor:publish --tag=adminlte
(lack --force option, i already has some routes declared don't want to lose them)

then i get:

Copied Directory [/vendor/acacha/admin-lte-template-laravel/public/img] To [/public/img]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/public/css] To [/public/css]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/public/js] To [/public/js]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/public/plugins] To [/public/plugins]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/public/fonts] To [/public/fonts]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/resources/views/auth] To [/resources/views/vendor/adminlte/auth]
**Can't locate path: </Users/enrique.martinez/Sites/i4tools/vendor/acacha/admin-lte-template-laravel/resources/views/auth/emails>**
Copied Directory [/vendor/acacha/admin-lte-template-laravel/resources/views/errors] To [/resources/views/vendor/adminlte/errors]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/resources/views/layouts] To [/resources/views/vendor/adminlte/layouts]
Copied File [/vendor/acacha/admin-lte-template-laravel/resources/views/welcome.blade.php] To [/resources/views/welcome.blade.php]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/resources/assets/css] To [/resources/assets/css]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/resources/assets/img] To [/resources/assets/img]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/resources/assets/less] To [/resources/assets/less]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/resources/assets/sass] To [/resources/assets/sass]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/resources/assets/js] To [/resources/assets/js]
Copied Directory [/vendor/acacha/admin-lte-template-laravel/tests] To [/tests]
Copied File [/vendor/creativeorange/gravatar/config/gravatar.php] To [/config/gravatar.php]
Copied File [/vendor/acacha/admin-lte-template-laravel/config/adminlte.php] To [/config/adminlte.php]
Copied File [/vendor/acacha/admin-lte-template-laravel/.env.dusk.local] To [/.env.dusk.local]
Copied File [/vendor/acacha/admin-lte-template-laravel/.env.dusk.testing] To [/.env.dusk.testing]
Publishing complete.

## Context

I'm actually learning to use this adminlte  and is frustrating being stopped by this issue, i can't log in neither register new users :(

This file affects login and register forms because user and password components missed.

## Possible implementation

I guess in any of the last commits this file has been removed by accident, isn't it?

## Your environment

* Version used  PHP 7, Laravel Framework 5.4.19:
* Operating system Mac OS sierra:

**Comment by acacha** [comment]
yes the file is not necessary but publish command still try to still i will solve as soon as possible. But i dont't understand why this is a problem. I think you don't see missing components not because this bug it have to be something else...

**Comment by acacha** [comment]
Last commit solves this problem. https://github.com/acacha/adminlte-laravel/commit/faf711ac17080d7fff33e85984bfc9bf75991722

**Comment by esoriams** [comment]
Thanks for the answer acacha, now it works. I just uninstall the package and reinstall it again, by the way that error message is still showing out:

Can't locate path: <˜/vendor/acacha/admin-lte-template-laravel/resources/views/auth/emails>

Anyway the forms are working well.  

Regards.

**Comment by acacha** [comment]
@esoriams the change is only applied in master branch so you have to wait for new release/tag.
