### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by cilas** [acacha/adminlte-laravel#25]
Hi!
The installation is done but when I access home, the browser show me this:
```
ErrorException in 01a5c44060f2b0cd2ee959ab8629faa0 line 118: 
Trying to get property of non-object (View: ...\resources\views\partials\mainheader.blade.php) (View: ...\resources\views\partials\mainheader.blade.php) (View: ...\resources\views\partials\mainheader.blade.php)

```
My routes:
```
Route::get('/', function () {
    return view('home');
});
```

Thanks a lot.

**Comment by jakesyl** [comment]
I'm having the same issue!

**Comment by SturmDrangAltaar** [comment]
Most likely the vars needed there is not present. For instance:
```html
<!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="/img/user2-160x160.jpg" class="img-circle" alt="User Image" />
                            <p>
                                {{ Auth::user()->firstname.' '.Auth::user()->lastname }}
                                <small>User since {{ date('d M Y', strtotime(Auth::user()->created_at)) }}</small>
                            </p>
                        </li>
```

**Comment by marioene** [comment]
I had the same issue.

Solution:
Run 'composer update' in your project root.

**Comment by acacha** [comment]
Use $ composer update

**Comment by getcrud** [comment]
@if (Auth::check())

    <li class="user-header">
        <img src="/img/user2-160x160.jpg" class="img-circle" alt="User Image" />
            <p>
                {{ Auth::user()->firstname.' '.Auth::user()->lastname }}
                <small>User since {{ date('d M Y', strtotime(Auth::user()->created_at)) }}</small>
            </p>
     </li>
@endif
