### ISSUE TITLE
 Facebook\WebDriver\Remote\curl_init error in Laravel Dusk

### ISSUE THREAD

**Issue by acacha** [acacha/adminlte-laravel#251]
TODO:

All tests return:

22) Tests\Browser\ExampleTest::testBasicExample
Error: Call to undefined function Facebook\WebDriver\Remote\curl_init()

/home/sergi/Code/testAdminLTE/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:125
/home/sergi/Code/testAdminLTE/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:83
/home/sergi/Code/testAdminLTE/tests/DuskTestCase.php:32
/home/sergi/Code/testAdminLTE/vendor/laravel/dusk/src/TestCase.php:209
/home/sergi/Code/testAdminLTE/vendor/laravel/framework/src/Illuminate/Support/helpers.php:652
/home/sergi/Code/testAdminLTE/vendor/laravel/dusk/src/TestCase.php:210
/home/sergi/Code/testAdminLTE/vendor/laravel/dusk/src/TestCase.php:116
/home/sergi/Code/testAdminLTE/vendor/laravel/dusk/src/TestCase.php:88
/home/sergi/Code/testAdminLTE/tests/Browser/ExampleTest.php:21

**Comment by carusogabriel** [comment]
Hello @acacha 

I had this problem, and solve it by installing php-curl in my Ubuntu. [Here's the stackoverflow answer](http://stackoverflow.com/a/36935239/4595097) that helped me.

**Comment by acacha** [comment]
Thanks @carusogabriel it woks ok now.
