### ISSUE TITLE
How to disable gravatar in a laravel installation with adminlte

### ISSUE THREAD

**Issue by jbauza1984** [acacha/adminlte-laravel#256]
I need to disable the complete gravatar module in my laravel installation with adminlte.

I already tried setting false to the "gravatar" option in the /config/adminlte.php file, but I still have exceptions related to the plugin, for example "Please specify a valid email address".

Perhaps you could check the scope of setting the option gravatar in the file /config/adminlte.php

* PHP Version 7.0.18
* Operating system and version Debian 8.6

Thank you in advance.

**Comment by acacha** [comment]
As I say at comments in file https://github.com/acacha/adminlte-laravel/blob/master/config/adminlte.php you can disable gravatar but then you have to do litle changes to the views.

Search for Gravatar Facade at files like (and maybe others) https://github.com/acacha/adminlte-laravel/blob/master/resources/views/layouts/partials/mainheader.blade.php to completely disable Gravatar.
