### ISSUE TITLE
Customize css and js

### ISSUE THREAD

**Issue by lcfc** [acacha/adminlte-laravel#258]
What is the best place to customize css and js?
I found only the /resources/assets/sass/_variables.scss; all other files in sass (or less) folder, include files from node_modules folder; I think it is not correct to change that files. Is it correct?

**Comment by acacha** [comment]
You can use tje tipical laravel workflow using Laravel Mix (old Laravel Elixir) or user any other aproachment you wish. https://laravel.com/docs/5.4/mix.

For adminlte this package is using Less version of adminlte so you can modify source less files. I'm not an expert in CSS so maybe you will prefer to ask to https://github.com/almasaeed2010/AdminLTE

**Comment by lcfc** [comment]
Perfect, thanks!
