### ISSUE TITLE
How can i change the default route of /home?

### ISSUE THREAD

**Issue by intositeme** [acacha/adminlte-laravel#26]
I would like to change the default route of /home after login without changing the src. How can i do that?

**Comment by marioene** [comment]
Have you try to modify routes.php?
    
    Route::get('home', '......Controller@method');

**Comment by intositeme** [comment]
Yup i did, but the postLogin keeps going to home

**Comment by acacha** [comment]
See http://laravel.com/docs/5.1/authentication#included-authenticating you can set:

```php
protected $redirectPath = '/dashboard';
```
