### ISSUE TITLE
adminlte-laravel install not working

### ISSUE THREAD

**Issue by rvabrazaldo** [acacha/adminlte-laravel#266]
## Command Line Log

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\The Daughters>cd C:/

C:\>cd laravel

C:\laravel>cd hris

C:\laravel\hris>adminlte-laravel install
llum package AdminLTE
Running composer require acacha/admin-lte-template-laravel
Using version ^4.1 for acacha/admin-lte-template-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
The compiled services file has been removed.
'C:\Users\The\' is not recognized as an internal or external command,
operable program or batch file.
Adding Acacha\AdminLTETemplateLaravel\Providers\AdminLTETemplateServiceProvider:
:class to Laravel config app.php file
'sed' is not recognized as an internal or external command,
operable program or batch file.
Adding Acacha\AdminLTETemplateLaravel\Facades\AdminLTE::class to Laravel config
app.php file
The filename, directory name, or volume label syntax is incorrect.

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "adminlte-laravel" namespace.

C:\laravel\hris>

**Comment by webstractions** [comment]
It appears that you have already ran the installation already. No need to run it again.

**Comment by acacha** [comment]
I'm not sure acacha/llum will work with Windows because it uses sed command for file manipulation but you could manually install package using the tipical manual Laravel package installation:

1) composer require package
2) Add service provider to config/App.php
3) Publish package files

**Comment by acacha** [comment]
I don't have Windows Operating System and I don't want/can support the operating system but you can create a PR in https://github.com/acacha/llum if you wish.
