### ISSUE TITLE
make:view fails with error "File does not exists", view.stub seems to be missing

### ISSUE THREAD

**Issue by Fluxlicious** [acacha/adminlte-laravel#267]
After quite some work to get AdminLTE to work on windows (llum not working as it should) i discovered an issue with the php artisan make:view command. Whatever view i try to create, i get the error "File does not exists". Tracing back in the code it requires a file "/stubs/view.stub", but it appears to be missing form the package.

**Comment by acacha** [comment]
Hi @Fluxlicious

About llum not working as it should please could you give me more info or please open and issue:

https://github.com/acacha/llum/issues/

About the issue I don't have any problems with a **fresh installation** of this package. The file you mention already exists in package:

https://github.com/acacha/adminlte-laravel/tree/master/src/Console/stubs

Please could you try with a fresh package? If you are using and old installation please manually update your project.

**Comment by Fluxlicious** [comment]
Oh i was looking in the wrong stubs dir. The view file is actually there, but i traced down the problem to the Filesystem class.

I'm not sure if this is a windows only issue, but the Filesystem->getPath() method does not make sense.
```php
    public function get($file)
    {
        echo $file . "\n"; // result: D:\Www\laravel\fluxticket\vendor\acacha\admin-lte-template-laravel\src\Console/stubs/view.stub
        $path = $this->getPath($file);
        echo $path;        // result: //D:\Www\laravel\fluxticket\vendor\acacha\admin-lte-template-laravel\src\Console/stubs/view.stub

        if (! file_exists($path)) {
            throw new FileDoesNotExists;
        }

        return file_get_contents($path);
    }
```
Notice the // that are added because of the getPath() function. I can't seem to figure out why the getPath is even needed, just use the $file as it's passed in the parameters.

**Comment by acacha** [comment]
Ok I see the problem I don't know Windows does not support // and I don't have any windows to use to test it. As soon as I can (or maybe someone could propose a PR) I will try to do a multiplatform version.

**Comment by otipip90** [comment]
Then someone already has a truly proven answer to this problem
$ php artisan make: view about
File does not exist
I just do not want to alter the code without knowing, I've been a week with this problem and I have not been able to solve it

**Comment by otipip90** [comment]
I am working with
-Windowa 10 Pro
-Xamp v3.2.2
-PHP Version 7.0.5
-laravel 5.4
Adminlte (github)
-composer 1.4.2
Your answer would be very helpful to me, thank you

**Comment by nircode** [comment]
Found the solution for windows users!

Open Filesystem.php and replace the getpath() function with the following:

protected function getPath($file)
    {
        if(strtoupper(substr(PHP_OS, 0,3)) == "WIN")
            return $file;
        else
            return $this->root . '/' . $file;

    }

The function now checks whether the OS is windows or something else and provides with appropriate path information. In case of windows it just forwards the file which contains the full path, in case of linux, the function will add "//" as prefix to the file path.

**Comment by saidl14s** [comment]
Thanks Nircode (y)

**Comment by acacha** [comment]
Thanks @nircode if you wish you could propose a Pull Request!

**Comment by acacha** [comment]
Close this issue and open a new one to add possible PR to source code.
