### ISSUE TITLE
A grey Login/register page (No Fields)

### ISSUE THREAD

**Issue by seobegood** [acacha/adminlte-laravel#269]
Hello,

I have for 2 times installed the 'acacha/ adminlte-laravel theme' But i have some issues about the login/register pages. 

The main page is correct, everything is showing, but wen access the login/register button, i shows only a grey page (both login/register). 

I am very new to laravel, I followed the steps to install here, https://github.com/acacha/adminlte-laravel .

Hope somebody can help me with this,

Thank you

**Comment by acacha** [comment]
I definitely need more info to help you... Can you open your browser console an let us know if any errors appeard there? You can also look at laravel logs.

Also README file is so extensive and there are multiple variations in the way you can install the package. Please provide us with detailed instructions you follow and give us as much environment info as possible.

**Comment by seobegood** [comment]
Hi Acacha, Thanks for your response,

I have got tis error;

Uncaught TypeError: Cannot read property 'csrfToken' of undefined
    at Object.<anonymous> (app.js:25086)
    at __webpack_require__ (app.js:20)
    at Object.defineProperty.value (app.js:23570)
    at __webpack_require__ (app.js:20)
    at Object.<anonymous> (app.js:44338)
    at __webpack_require__ (app.js:20)
    at app.js:66
    at app.js:69

Seems there is missing something? >>> modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

About the README file i have start reading and following the instructions from;

**Laravel 5.4**

Laravel 5.4 is the default Laravel version supported. See section Installation & use for more info. See below for info about how to install this package in older Laravel versions

**Laravel 5.4 manual installation**

I hope this will help,

Thank you

**Comment by acacha** [comment]
Ok. Some version of this package have this error so in new versions you will don't have it. So I recommend you a new fresh installation.

To solve the problem check the "Laravel.csrfToken" (or Laravel javascript variable) is set. Normally is set at html header (see all repository versions):

Now:
https://github.com/acacha/adminlte-laravel/blob/master/resources/views/layouts/partials/htmlheader.blade.php

Old:
https://github.com/acacha/adminlte-laravel/blob/5d6c1165348e432f236576ee2118912b535efb5f/resources/views/layouts/partials/htmlheader.blade.php

Take into account Laravel has changed these (now csrf token is not saved in a Laravel Javascript global variable) in last version to maybe you have to change the code to adapt. So you have to use the new global token javascript variable so intead of changing htmlheader check for bootstrap.js file a refactor your code.

**Comment by RobertoRiera** [comment]
Yeee, that was the solution, I've been 4 hours with this! thanks Acacha for answer and Seobegood for asking!

**Comment by acacha** [comment]
@RobertoRiera You are welcome!
