### ISSUE TITLE
component with v-cloak not loading

### ISSUE THREAD

**Issue by SkyHK** [acacha/adminlte-laravel#271]
I am using a fresh install of latest version of laravel and adminlte-laravel.
The login page is not able to display because of the v-cloak in `<div id="app" v-cloak>`.
It seems that the VUE.js is not loading in this situation.

**Comment by acacha** [comment]
As you can see at:

https://vuejs.org/v2/api/#v-cloak

Vue put this directive on components to allow users avoid 

https://en.wikipedia.org/wiki/Flash_of_unstyled_content

This directive will dissapears once the vue instance is ready so I think you maybe have a problem tih vue not loading? Please could you show us an example? DO you have any javascript errors in Browser console?

**Comment by SkyHK** [comment]
Thank you Acacha. I finally figure out it is not a bug. I am new to VUE so I don't have any vue instance in my code  and the clean install also do not come with any vue instance in the login module and other v-cloak included module , thus the vue is never being loaded. 

I just initiate an empty vue instance and it will load and that the v-cloak will not hide the content any more.

I am not sure if only me being to green to this or you may want to add this as reminder for the new comers.

Anyway, thank you for making and managing such a good package!

**Comment by acacha** [comment]
I never have a problem like this because prepackaged public/js/app.js comes with vue instance defined so I don't know how you arrive to that problem...

You colud also recreate public files form resources using Laravel elixir and executing npm run dev

**Comment by Phil795** [comment]
Hello acacha,

I have the same problem, after a clean installation of laravel and adminlte, I cannot see the /register or /login form.

I fixed the problem for me, but I think this is a bug in your project. Vue isn't initialized by default...

**Comment by acacha** [comment]
Laravel has been changed how it exposes Token to javascript. I already changes this in source code but now I see I don't have published correctly compiled files. You can solve the problem with a new fresh installation (I released a new tag) or running npm run dev

**Comment by acacha** [comment]
https://github.com/acacha/adminlte-laravel/commit/22237bd3afbcbb7a07fa17c99fa17568e9da11fe
