### ISSUE TITLE
"Your requirements could not be resolved to an installable set of packages."

### ISSUE THREAD

**Issue by Gino** [acacha/adminlte-laravel#273]
Hello,

When I try to install the thing via composer, it gives me this big error:
https://pastebin.com/raw/nxawknaM

**Comment by acacha** [comment]
This project requires Laravel, have you checked:

https://laravel.com/docs/5.4/installation#server-requirements

Could you install an execute laravel project correctly using laravel new command?

See also for a possible duplicate bug.

**Comment by Gino** [comment]
Yes, I can use the "laravel new" command, and it just creates a Laravel project.
But when I run: "composer global require "acacha/adminlte-laravel-installer=~3.0", it fails.

**Comment by acacha** [comment]
I'm not able to reproduce the problem... Please could you try:

$ composer global require "acacha/adminlte-laravel-installer"

I don't understand why is trying to install a dev-master version of package see composer.json of package:

https://github.com/acacha/adminlte-laravel-installer/blob/3.1.15/composer.json

No references to dev-master!

Maybe is a problem with composer cache or something related? Maybe you could reinstall composer? Sorry I'm lost I don't understand which problem generates this error in some environments. Please provide environment info also...

**Comment by acacha** [comment]
Feel free to create new issue if somebody still have this problem
