### ISSUE TITLE
some routes are wrong

### ISSUE THREAD

**Issue by pmirandaarias** [acacha/adminlte-laravel#274]
When I try to register, or login, it point to my IP, not my root public folder

![image](https://cloud.githubusercontent.com/assets/20463330/26607689/bf7c56e8-4565-11e7-8255-6415427fab9b.png)
assets are ok, but those links are wrong. It's a fresh acacha install

**Comment by acacha** [comment]
I think this problem has been explained before at previous issues. If you are working with Alias instead of full domain apps I think you will have to adapt some files

**Comment by acacha** [comment]
See https://github.com/acacha/adminlte-laravel/issues/209
