### ISSUE TITLE
No hint path defined for [adminlte]

### ISSUE THREAD

**Issue by danegraphics** [acacha/adminlte-laravel#275]
I've installed adminlte-laravel on an existing (not new) laravel project but every time I try to go to the /home page, I get the error "No hint path defined for [adminlte]".

I'm also unable to use the artisan make:view command because the console is saying that it doesn't exist.

What can I do to make sure that adminlte is installed properly into the already existing laravel project?

Below is the install log when I ran the install command.

# Install log
adminlte-laravel install
/root/.composer/vendor/bin/llum package AdminLTE
Running composer require acacha/admin-lte-template-laravel
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Using version ^4.1 for acacha/admin-lte-template-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
\> Illuminate\Foundation\ComposerScripts::postUpdate
\> php artisan optimize
Generating optimized class loader
The compiled services file has been removed.
File /appdata/var/www/html/tracking/config/app.php already supports llum.
Llum is already installed. Skipping...
Adding Acacha\AdminLTETemplateLaravel\Providers\AdminLTETemplateServiceProvider::class to Laravel config app.php file
Adding Acacha\AdminLTETemplateLaravel\Facades\AdminLTE::class to Laravel config app.php file
Publishing complete.

**Comment by danegraphics** [comment]
Update! Something that should be included in the install instructions. Be sure to run this command after installation:

> php artisan config:cache

That command refreshed the configuration cache and I can now use the create views command. However, now, there is a different error (the multiple references appear to be a result of my trying to install multiple times): 
> The Mix manifest does not exist. (View: /appdata/var/www/html/tracking/vendor/acacha/admin-lte-template-laravel/resources/views/layouts/partials/scripts.blade.php) (View: /appdata/var/www/html/tracking/vendor/acacha/admin-lte-template-laravel/resources/views/layouts/partials/scripts.blade.php) (View: /appdata/var/www/html/tracking/vendor/acacha/admin-lte-template-laravel/resources/views/layouts/partials/scripts.blade.php) (View: /appdata/var/www/html/tracking/vendor/acacha/admin-lte-template-laravel/resources/views/layouts/partials/scripts.blade.php)

**Comment by acacha** [comment]
The installer is not intended for installation in existing packages (or at least is not always guaranted to work). You will have to manually adapt you app.

This package (as a lot of Laravel packages) modifies/add to your app:
- More source PHP code via composer: this works always with no problem when updating or installing Laravel packages in no fresh projects.
- Remember to add/check AdminLTE service provider (https://github.com/acacha/adminlte-laravel/blob/master/src/Providers/AdminLTETemplateServiceProvider.php) to you app (this package use acacha/llum to automate this but suppose config/app.ph has been altered and in some conditions will not always work ). Waiting for Package autodiscover in Laravel (https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518) in Laravel 5.5!! So check you config/app.php file
- Publish files from vendor yo your app with php artisan publish command: this is the tricky part! You can republish package files but be carefull about overwriting you code (use git to check changes).  So you have to manually mix your public/resources/src folder and compare with files in package

**Comment by acacha** [comment]
See also https://github.com/acacha/adminlte-laravel/issues/270

**Comment by yacinegithub** [comment]
adding "JeroenNoten\LaravelAdminLte\AdminLteServiceProvider::class, solved the probleme" to config/app.php solved it for me
