### ISSUE TITLE
New installation problem

### ISSUE THREAD

**Issue by niirii** [acacha/adminlte-laravel#28]
Hello,

I created a brand new laravel 5.1.11 project which doesn't come with pre-built authentication pages.  I found this product through packagist.

I followed the instructions and have adminlte installed.  When I attempt to register a user I get the following error :  TokenMismatchException in VerifyCsrfToken.php line 53

If I view the source of the registration page I see the "token" so I'm not sure what's happening.

I have a brand new CentOS 7 box with Apache 2.4.6, MariaDB 5.5.44, and PHP 5.6.15.

**Comment by marioene** [comment]
This solution worked for me:

Add {{ csrf_field() }} anywhere in the form.

**Comment by niirii** [comment]
Apparently I am having a problem with Sessions in my Laravel installation.  @marioene The adminlte package already includes the CSRF token in the form but thanks for the suggestion.

**Comment by acacha** [comment]
I cannot reproduce the problem. As @niirii say csfr is already in the register form. @marioene you should provide more info please to debug
