### ISSUE TITLE
Provider class not found during installation

### ISSUE THREAD

**Issue by isometriq** [acacha/adminlte-laravel#286]
## Detailed description

When running "adminlte-laravel.bat install", the dependencies are required correctly, but injected provider got the class path without separators "\\". It halts and the rest  (facade and what more?) does not execute.

This is clearly a bug, maybe platform related? (Windows 10)
You seem to be on linux/unix, so maybe you missed it.

## Context

Can't install properly, it's a small problem yet very annoying

## Possible implementation

Fix the class name, the class path separators "\\" are missing.

## Your environment

Latest composer using Windows 10.
Followed the procedure in the git repo readme
Did not used "llum".

**Comment by isometriq** [comment]
Ah! dammit, I had to use the `--no-llum` option ..as told in the readme
All working now

**Comment by acacha** [comment]
Good!
