### ISSUE TITLE
After running webpack Vue is broken

### ISSUE THREAD

**Issue by timo002** [acacha/adminlte-laravel#288]
When I install this package, all is working fine. If I run `npm run dev`, Vue is broken, login / register page nog showing forms.

> app.js:13218 [Vue warn]: Unknown custom element: <login-form> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
(found in <Root>)

I'm not sure, but it seems that the `webpack.mix.js` is not complete. 
First of all, [app.js does not exist](https://github.com/acacha/adminlte-laravel/blob/master/webpack.mix.js#L14) 

In the `public/js/app.js` you will find these lines:
```
// Laravel AdminLTE vue components
Vue.component('register-form', __webpack_require__(58));
Vue.component('login-form', __webpack_require__(57));
Vue.component('email-reset-password-form', __webpack_require__(56));
Vue.component('reset-password-form', __webpack_require__(59));
```
After running `npm run dev`, these are not in this file anymore.
They seem to be in `resources/assets/js/bootstrap.js`, but webpack does not use this file.
I've renamed `bootstrap.js` to `app.js`, but no succes either. Webpage remains blank.

So added
```
const app = new Vue({el: '#app'})
```
Page loads, but still no form showing and [Vue warn] (above) in console.

## environment
* Virtual machine: Ubuntu 16.04
* Host: MacOs Sierra
* PHP 7.0
* node: v6.10.2
* npm: 5.0.4

**Comment by acacha** [comment]
Maybe related with https://github.com/acacha/adminlte-laravel/issues/298

**Comment by acacha** [comment]
See also my answer at https://github.com/acacha/adminlte-laravel/issues/298

**Comment by acacha** [comment]
I don't understand which steps you follow to not having resources/assets/js/app.js in your Laravel project. Laravel offers a default one that is fine combined with this package (This package doesn't change this file). This file (see https://github.com/laravel/laravel/blob/master/resources/assets/js/app.js) is the one that includes bootstrap.js file (take into account that bootstrap.js is overwrited by this package)

Please consider giving the exact commands to reproduce this problem startin with a laravel new command

**Comment by CicciMTS** [comment]
I have the same problem: i solved by copying the content of resources/assets/js/bootstrap.js of the acacha repo into my local bootstrap.js.
It seems that, after running any set up of adminlte-laravel, this file is not correct.
