### ISSUE TITLE
tried login the demo site

### ISSUE THREAD

**Issue by sweggggg** [acacha/adminlte-laravel#289]
does the demo site not working?

i tried login as admin@example.com|123456 in http://demo.adminlte.acacha.org/login

**Comment by acacha** [comment]
Umm I will take a look. You can register any user you want until the issue was solved.

**Comment by shiroamada** [comment]
http://demo.adminlte.acacha.org/ not able to access. Server down.

**Comment by acacha** [comment]
Hello @shiroamada yes it seems I have some problem with demo server. I will close this issue and try to solve the problem at issue https://github.com/acacha/adminlte-laravel/issues/303
