### ISSUE TITLE
Trouble installing: Class 'Acacha\AdminLTETemplateLaravel...' not found

### ISSUE THREAD

**Issue by iampatrick** [acacha/adminlte-laravel#29]
Hi,

I have following the instructions on installing adminlte-laravel but am getting an error on the last step.
`php artisan vendor:publish --force --provider="Acacha\AdminLTETemplateLaravel\app\Providers\AdminLTETemplateServiceProvider"`

Is throwing the following error. 
`PHP Fatal error:  Class 'Acacha\AdminLTETemplateLaravel\app\Providers\AdminLTETemplateServiceProvider' not found in /var/www/project/laravel/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146`

I'm running this on Ubuntu with Apache 2, and PHP 5.6.
Thank you for any assistance.

**Comment by iampatrick** [comment]
Ok, I've figured it out for myself. 

I was having no problems installing Laravel via composer but the laravel command itself didn't work for me. I think resolving that cleared up the subsequent issues with installing Admin LTE via the provided instructions.

**Comment by acacha** [comment]
Ok

**Comment by ATSUsak** [comment]
I am getting the same error at the last step.Could anyone please suggest possible solution for that.Thanks in advance

**Comment by iampatrick** [comment]
@ATSUsak  I don't remember how I fixed it now but I was also stumbling through my first Laravel project. I think I had permission issues and files weren't written. If that's not the case, it could be a cache issue perhaps.

Here are the CLI commands for the cache.

`composer dump-autoload
php artisan clear-compiled
php artisan config:cache
`

Good luck!
