### ISSUE TITLE
CoreUI failed on composer install

### ISSUE THREAD

**Issue by devstevehowe** [acacha/adminlte-laravel#292]
When doing a fresh install we are presented with the following:

composer require "acacha/admin-lte-template-laravel:4.*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 43 installs, 0 updates, 0 removals
  - Installing mrholek/coreui-free-bootstrap-admin-template (1.0.0): Downloading (failed)    Failed to download mrholek/CoreUI-Free-Bootstrap-Admin-Template from dist: The "https://api.github.com/repos/mrholek/CoreUI-Free-Bootstrap-Admin-Template/zipball/tags/1.0.0" file could not be downloaded (HTTP/1.1 302 Found)
    Now trying to download from source
  - Installing mrholek/coreui-free-bootstrap-admin-template (1.0.0): Cloning tags/1.0.0 from cache
    tags/1.0.0 is gone (history was rewritten?)

Installation failed, reverting ./composer.json to its original content.

                                                                                      
  [RuntimeException]                                                                  
  Failed to execute git checkout 'tags/1.0.0' -- && git reset --hard 'tags/1.0.0' --  
  fatal: invalid reference: tags/1.0.0

**Comment by acacha** [comment]
Ummmmm... Maybe it's a local configuration problem only affecting you? Anyelse have the same problem? I don't remember any relationship between this project and and coreui-free-bootstrap-admin-template ...
