### ISSUE TITLE
Login Stuck

### ISSUE THREAD

**Issue by pr0ph0z** [acacha/adminlte-laravel#294]
Hi,
This is the first time i'm using ur library. I want to register and success. But when i try to log in, it stuck. 

![stuck](https://user-images.githubusercontent.com/17337978/28152176-421077bc-67c9-11e7-9e21-ec1073b4c083.png)

Am i missed something? Thank you.

Edit:
I've tried to inspect element on my browser, and it displays this
![inspect](https://user-images.githubusercontent.com/17337978/28152917-17ec2efa-67cd-11e7-9e6c-9ca2180e0e36.png)

**Comment by dbrw** [comment]
I think error code 500 is related to your server settings.

**Comment by pr0ph0z** [comment]
Update:
I tried to click 'login' hyperlink in internal error message, and it shows 'method validate doesn't exist'
i add this syntax 'use Illuminate\Foundation\Validation\ValidatesRequests;' and it fixed
