### ISSUE TITLE
webpack.mix.js question

### ISSUE THREAD

**Issue by shiroamada** [acacha/adminlte-laravel#298]
I check with your `webpack.mix.js` still included this line
`mix.js('resources/assets/js/app.js', 'public/js')`
but I can't find the source. 

Is it something to keep for allowing the user to add their own or can remove totally?

and the bootstrap.js seem like also didn't include in the `webpack.mix.js`, when I was running `npm run watch`, icheck is not initialize and the vue component is not loaded.

## Your environment

* Version used (e.g. PHP 5.6, HHVM 3): PHP 7.0.20
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): MacOS 10.12.6

**Comment by acacha** [comment]
@shiroamada take into account that npm run dev will be executed in a Laravel project where you have been installed this package. So app.js already exists in your project is the default one that Laravel provides see:

https://github.com/laravel/laravel/blob/master/resources/assets/js/app.js

So I think wbpack.mix.js is correct.
