### ISSUE TITLE
sed: 1: “/Applications/MAMP/htdo …”: invalid command code M

### ISSUE THREAD

**Issue by ni3handa** [acacha/adminlte-laravel#299]
getting this error on command : php artisan make:route about

mac:coconnect mac$ php artisan make:route about --type=controller
sed: 1: "/Applications/MAMP/htdo ...": invalid command code M
Route about added to /Applications/MAMP/htdocs/coconnect/routes/web.php.

It says Route about added but "web.php" is actually not modified, No changes were made in "web.php"

Also tried : brew install gnu-sed

Please suggest..

------- PHP version
PHP 7.1.1 (cli) (built: Jan 23 2017 15:09:57) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
------- OS
macOS Sierra
vesion 10.12.6

**Comment by JaimeVirrueta** [comment]
Hi, im think u need run "php artisan make::route about" use 2 ':' after type "make"

**Comment by mschakulat** [comment]
Did you solve this?
