### ISSUE TITLE
Login Auth.Failed - Routes does not working

### ISSUE THREAD

**Issue by guimadalozzo** [acacha/adminlte-laravel#300]
When I try login into app, return auth.failed message.

If I try register using google, facebook, etc, the routes are not found.

The login routes were changed?

**Comment by acacha** [comment]
Social Login is not active (links are only put here for convenience). You have to use/configure Laravel Socialiate to active this links. But if you read section:

https://github.com/acacha/adminlte-laravel#social-loginregister-with-acachalaravel-social

of README file you will see we have a command to help you configure social Login.

As for normal login let me confirm it works in my local install and please could you offer more info about the error?

**Comment by acacha** [comment]
Please test the last version of this package with Laravel 5.5 I think this could solve your problems.
