### ISSUE TITLE
Login Form remember me not working

### ISSUE THREAD

**Issue by shiroamada** [acacha/adminlte-laravel#302]
In the Login Form, the 'Remember Me' does not work. I use Vuejs to inspect the value, it seem like didn't update and didn't pass when submit the form. 

## Detailed description
LoginForm.vue below the code did not execute.
```
  watch: {
    'form.remember': function formRemember(value) {
      if (value) {
        $('input').iCheck('check');
//I added alert here also not working
      } else {
        $('input').iCheck('uncheck');
      }
    }
```

I am not familiar with Vue.js sorry can't really troubleshoot.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used (e.g. PHP 5.6, HHVM 3): PHP 7.0.22
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): MacOS 10.12.6

**Comment by acacha** [comment]
Please use 5.0.2 version of update your app.js file with the new one.
