### ISSUE TITLE
Demo link is broken

### ISSUE THREAD

**Issue by cagp-dev-mtl** [acacha/adminlte-laravel#303]
## Detailed description

The demo link in the README.MD is broken.

## Solution

The new AdminLTE demo is located at:
https://adminlte.io/themes/AdminLTE

**Comment by acacha** [comment]
Ok. Let me solve the problem with de demo server something is broken. The link you offer is Adminlte demo site but this project has is own demo page. Thanks!

**Comment by lguima** [comment]
Still not working.

**Comment by acacha** [comment]
I close this issue because there is another issue about that.
