### ISSUE TITLE
Phpunit never stops running: > Illuminate\Foundation\ComposerScripts::postAutoloadDump > @php artisan package:discover 

### ISSUE THREAD

**Issue by acacha** [acacha/adminlte-laravel#308]
Never ending running:

```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
```

**Comment by acacha** [comment]
Weird error! only happens at first execution of phpunit. Ctrl+c first execution and following executions works ok!

**Comment by krodo93** [comment]
Problem when upgrade Laravel 5.5

**Comment by lauri911** [comment]
Had same problem and thats occurs when PhpStorm is listening for PHP Debug Connections --- there it hangs. Stop listening and it works :)

**Comment by acacha** [comment]
Thanks @lauri911 for the info!

**Comment by acacha** [comment]
Ok is not a problem with Laravel or Phpunit: One of my tests (callAdminlteAdminCommand) in some cases runs infinitely. The test is related with a command I want to change completely so the problem will solve then.
