### ISSUE TITLE
Asset folder plugin is not flatted after run prod/dev

### ISSUE THREAD

**Issue by CicciMTS** [acacha/adminlte-laravel#321]
## Detailed description

Hello, after a fresh install of Laravel (both 5.5 and 5.4) and AdminLTE, when i run prod or dev of webmix, asset/plugins folder is replaced with a copy not flatted of structure ad AdminLTE can't find correct path of css, js and the other dependencies.
I searched online but I didn't find a solution.

## Environment

* PHP 7.0;
* Tested with Laravel both 5.4 and 5.5;
* MacOSX 10.12.6;

**Comment by acacha** [comment]
@CicciMTS latest commits solve this problem (use dev-master or wait for release 6.0). Thanks for the issue report!
