### ISSUE TITLE
 login component and register dont display the message on gui 

### ISSUE THREAD

**Issue by crosasga** [acacha/adminlte-laravel#322]
problem with laravel 5.5 on fresh installation on login component and register dont display the message on gui 

![image](https://user-images.githubusercontent.com/22960856/30218532-a200b270-948f-11e7-8b32-b5bedcb43abc.png)

![image](https://user-images.githubusercontent.com/22960856/30218483-8305b050-948f-11e7-839b-2f4c9f88da14.png)

![image](https://user-images.githubusercontent.com/22960856/30218564-b5edccaa-948f-11e7-8e0d-e195b58c5bfb.png)

**Comment by MrLoKids** [comment]
Yeah, i have the same problem. I get the error message but don't see him on display

**Comment by abolajibisiriyu** [comment]
I have this error also, and when i check my network tab, in the request section the email and password are empty
![screenshot from 2017-10-26 03-31-00](https://user-images.githubusercontent.com/8493924/32032268-20c7766e-b9fe-11e7-88ba-715d1666038b.png)
kindly look into this, but for now i'd default to the normal behavior which is a full page reload

**Comment by MrLoKids** [comment]
Please, @acacha Help us with laravel 5.5. What are we doing wrong? Can u help?

**Comment by alin-o** [comment]
I have the same problem.

this is because Laravel returns an object with message and errors properties as validation response.
now there is an this.form.errors.errors.errors object :(

quick&dirty fix: add this watcher in the `auth/*.vue` files:

```JS
        watch: {
            'form.errors': {
                handler: function (value) {
                    if(value.errors.hasOwnProperty('errors')) {
                        this.form.errors.set(value.errors.errors)
                    }
                },
                deep: true
            }
        }
```

**Comment by raidenghost** [comment]
Hola para solucionar este error debes crear el host virtual para xampp. Lo que pasa es que no encuentra las rutas por eso se bloquea.

Atte.

**Comment by Marpxz** [comment]
I have the same issue, please help to fix it!!

**Comment by Daniwenzel** [comment]
Any solution for this?

**Comment by acacha** [comment]
Error messages format changed in some previous verion of Laravel. Please upgrade you Laravel app or try with a fresh new installation
