### ISSUE TITLE
Yarja Laravel-DataTables with Acacha Adminlte-laravel

### ISSUE THREAD

**Issue by karmendra** [acacha/adminlte-laravel#323]
Basically, how do we make yajra/laravel-datatables work with acacha/adminlte-laravel?
where do I place the <script src="/vendor/datatables/buttons.server-side.js"></script> and {!! $dataTable->scripts() !!}.

When I place these scripts in resources/views/vendor/adminlte/layouts/partials/scripts.blade.php I get following error

users:389 Uncaught TypeError: $(...).DataTable is not a function
I need to place these scripts after adminlte loads datatables plugin.

Any help appreciated.

I am using Laravel 5.5

**Comment by acacha** [comment]
Hey,

I'm not an expert in adminlte template and I don't know anything about Yarja so maybe it's better you use adminlte forums of github or stackoverflow to ask questions:

https://stackoverflow.com/questions/tagged/adminlte
