### ISSUE TITLE
Login issue 

### ISSUE THREAD

**Issue by afoysal** [acacha/adminlte-laravel#325]
I developed an application using Laravel adminLTE. I can login that application using `php artisan serve` command. But I can't login without using `php artisan serve` command. Below is the screen shot. 

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/CZlQs.png

How can I debug this situation ?

**Comment by shiroamada** [comment]
You have a wrong Laravel setup. You should set a proper hostname for your project. e.g laraveladmin.dev/, your public/ path should not be visible.

https://laravel.com/docs/5.5#installing-laravel
This is nothing do with adminlte-laravel. Please learn some basic of Laravel. How to setup a proper Laravel environment. You can use homestead for you to easy kick start.

**Comment by afoysal** [comment]
Thanks @shiroamada for your reply .I would not like to use HomeStead or VirtualHost. I would like to browse my project like this. Is it possible to browse like this ? Thanks

**Comment by VictorAlagwu** [comment]
I guess you are using  XAMPP{ or another server}, read on "Virtual Host"

**Comment by afoysal** [comment]
Thanks @VictorAlagwu  for your reply.
I would not like to use VirtualHost. 
Now I am getting below output

![notfound](https://user-images.githubusercontent.com/1283998/31047693-31318598-a631-11e7-8f03-a0ca3bf71ffd.png)

**Comment by shiroamada** [comment]
@afoysal since you do not want to use VirtualHost, and you have to modify the .htaccess.
Default .htaccess in public/.htaccess. This is the content

```
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
```
You have to modify it. 
I have no idea why you so insist want to go different Laravel setup way. I guess you can to find out the way to meet your requirement.

and public/login <- your web server can't resolve
by default Laravel .htaccess will be able to access projectmy.dev/login.

I suggest you understand how .htaccess works, how webserver work and how Laravel works then only come to this adminlte-laravel.

**Comment by afoysal** [comment]
Thanks @shiroamada  for your reply. 

I installed mod_rewrite

![mdo](https://user-images.githubusercontent.com/1283998/31052906-a218b7aa-a6b2-11e7-88f2-f30f7bd66c59.png)

I made changes in .htaccess

![htaccess](https://user-images.githubusercontent.com/1283998/31052935-44ef2450-a6b3-11e7-856b-9a4ae0f31c2f.png)


I made change in apache2.conf
![apache2](https://user-images.githubusercontent.com/1283998/31052961-aa1f3afe-a6b3-11e7-9e1d-a22aeab49061.png)


I restarted apache server.

But the result is as like before

![apache2](https://user-images.githubusercontent.com/1283998/31052967-ce15b8c0-a6b3-11e7-93d0-80a31528741d.png)

![notfound](https://user-images.githubusercontent.com/1283998/31052976-e1210762-a6b3-11e7-9917-316c494f4575.png)

I did all these in a newly install Linux Mint System. 

Thanks
