### ISSUE TITLE
Overwriting of SCSS / LESS / CSS Hierarchy 

### ISSUE THREAD

**Issue by lee-mustard** [acacha/adminlte-laravel#328]
Hey Guys, 

Firstly Great package & helped me save abit of time in setup phase.

A few questions : 

**Is this still supported?** -  I see a few question go unanswered.  

**Styling Hierarchy / overwriting** 

Currently, Im stuck in the situation where id like my styles to overwrite the default AdminLTE / Bootstrap themes styles but its seeming quite difficult (having to use !important). 

Is there a way (without editing default in node_modules / bower_comps to use your overrides. Might be a noobish question but any direction would be appreciated  

This is my webpack.mix.js file  (i've commented out & removed so fo the copied files and re-coiled npm-dev but still nothing : 

** **************** Code start ****************** ** 
`mix.js('resources/assets/js/app.js', 'public/js')
   .js('resources/assets/js/app-landing.js', 'public/js/app-landing.js')

   .less('node_modules/bootstrap-less/bootstrap/bootstrap.less', 'public/css/bootstrap.css')
   .less('resources/assets/less/adminlte-app.less','public/css/adminlte-app.css')
   .less('node_modules/toastr/toastr.less','public/css/toastr.css')
    .sass('resources/assets/sass/app.scss', 'public/css')

   .combine([
       'public/css/app.css',
       'node_modules/admin-lte/dist/css/skins/light-blue.css',
       'public/css/adminlte-app.css',
       'node_modules/icheck/skins/square/blue.css',
       'public/css/toastr.css'
   ], 'public/css/all.css')

   .combine([
       'public/css/bootstrap.css',
       'resources/assets/css/main.css'
   ], 'public/css/all-landing.css');

   //APP RESOURCES
   //.copy('resources/assets/img/*.*','public/img')
   //VENDOR RESOURCES
   //.copy('node_modules/font-awesome/fonts/*.*','public/fonts/')
   //.copy('node_modules/ionicons/dist/fonts/*.*','public/fonts/')
   //.copy('node_modules/admin-lte/bootstrap/fonts/*.*','public/fonts/bootstrap')
   //.copy('node_modules/admin-lte/dist/css/skins/*.*','public/css/skins')
   //.copy('node_modules/admin-lte/dist/img','public/img')
   //.copy('node_modules/admin-lte/plugins','public/plugins')
   //.copy('node_modules/icheck/skins/square/blue.png','public/css')
   //.copy('node_modules/icheck/skins/square/blue@2x.png','public/css');

if (mix.config.inProduction) {
  mix.version();
}

mix.browserSync('xxxx');`
** **************** Code end ****************** ** 

Will def continuing using AdminLTE -laravel going forward

_Bests_

**Comment by neomobil** [comment]
Hi! I'm using this package a while in more projects. Today I have installed it for a new project and unfortunately got the same issue.

**Comment by lee-mustard** [comment]
Any feedback on this one: ?

**Comment by neomobil** [comment]
My solution was that I have installed the previous adminlte node packages. 2.3.4.

**Comment by lee-mustard** [comment]
ahh thanks, Would give it a try but I've made quite abit of progress since then. Dont want to revert the entire install. Going to what i can find will post solution here.

**Comment by acacha** [comment]
Is this still supported? 

Yes as much as I can. I welcome any help anyone can provide for example resolving issues or proposing PR...

**Comment by acacha** [comment]
@neomobil 2.3.4? As far as I know 2.3.11 worked before but now this versions has problems also

I'm working to know what happens to adminlte node package because I amb facing problems with new version 2.4 and 2.3.11

**Comment by lee-mustard** [comment]
@acacha In terms of overwriting your LESS & SASS Styles in webpack.mix.js. Whats the recommended hierarchy or how would i add your node module imports to my webpack.mix.js.

**Comment by neomobil** [comment]
@acacha sorry, i didn't remember correctly. It was 2.3.11. This package works

**Comment by neomobil** [comment]
In the new version are path problems, i think because of the missing bootstrap directory

**Comment by acacha** [comment]
@neomobil new version 5.0.4 is released today trying to patch lot of problems with adminlte 2.4.2 version. See last changes

**Comment by neomobil** [comment]
Thank you. I will test it.

**Comment by acacha** [comment]
@lee-mustard Umm I'm not sure if I understand you: node_modules/admin-lte package is not mine is from Almasaaed https://github.com/almasaeed2010/AdminLTE

**Comment by acacha** [comment]
@neomobil be nice ;-) the new release version contains ugly patches I have not find better solution until AdminLTE solves some issues I report in their Github repo. Feel free to propose any changes or PR!

**Comment by neomobil** [comment]
@acacha Thanks. Good idea.
