### ISSUE TITLE
Sidebar collapse stops working after running `npm run dev`

### ISSUE THREAD

**Issue by AmruthPillai** [acacha/adminlte-laravel#329]
It's weird. I even checked the Javascript Console, and there are no errors registered. I even ran a log to check if JS is still running at the end of page load, and it worked. But the sidebar collapse just doesn't seem to be working right after I run `npm run dev`.

Steps to Reproduce Error:
1) run `adminlte-laravel install`
1.5) login to the dashboard to check the sidebar, it would be working as expected now.
2) run `npm install`
3) run `npm run dev`
3.5) login to the dashboard again, and the sidebar doesn't work at all. Not even on mobile, which makes it unusable on mobile screens.

Please help me fix this error. Thank you so much!

**Comment by AmruthPillai** [comment]
Fixed in #330

**Comment by acacha** [comment]
Ok as commented in PR I lock adminlte version to 2.3.11
