### ISSUE TITLE
Location of Registration Form

### ISSUE THREAD

**Issue by afoysal** [acacha/adminlte-laravel#331]
I need the Location of the Registration form.  Thanks

![register](https://user-images.githubusercontent.com/1283998/31167735-e1db2bfc-a914-11e7-99f2-176f73f1508b.png)

**Comment by lee-mustard** [comment]
Thats a Vue module. I think its within the resources/views/vendor/adminlte/...

**Comment by afoysal** [comment]
Thanks @lee-mustard  for your reply. Yes, the location of my file `register.blade.php` is resources/views/vendor/adminlte/... But I need the location of the Vue module. Thanks

**Comment by lee-mustard** [comment]
Ahh. You'll find it under : resources/js/components/auth/RegisterForm.vue

**Comment by lee-mustard** [comment]
@afoysal get it sorted ?

**Comment by acacha** [comment]
Yes location is: resources/js/components/auth/RegisterForm.vue
