### ISSUE TITLE
Npm run dev error

### ISSUE THREAD

**Issue by acacha** [acacha/adminlte-laravel#334]
npm run dev
``` 
ERROR  Failed to compile with 2 errors                                                                    21:59:36

 error  in ./resources/assets/less/adminlte-app.less

Module build failed: 

//google fonts
@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic);
^
Can't resolve './https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic' in '/home/sergi/Code/Tasks/node_modules/admin-lte/build/less'
      in /home/sergi/Code/Tasks/node_modules/admin-lte/build/less/AdminLTE.less (line 9, column 0)

 @ ./resources/assets/less/adminlte-app.less 4:14-215
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss ./node_modules/bootstrap-less/bootstrap/bootstrap.less ./resources/assets/less/adminlte-app.less ./node_modules/toastr/toastr.less

 error  in ./resources/assets/less/adminlte-app.less

Module build failed: ModuleBuildError: Module build failed: 

//google fonts
@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic);
^
```

**Comment by rjfortis7** [comment]
I have this error:

`npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rfortis/.npm/_logs/2017-10-09T21_37_09_102Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rfortis/.npm/_logs/2017-10-09T21_37_09_269Z-debug.log
`
