### ISSUE TITLE
Bower components error when running npm run dev

### ISSUE THREAD

**Issue by acacha** [acacha/adminlte-laravel#335]
See:

https://github.com/almasaeed2010/AdminLTE/issues/1665

Updated on master pending adminlte laravel tag

**Comment by acacha** [comment]
Temporary solution:

```
cd node_modules\admin-lte
bower install
```

**Comment by afoysal** [comment]
Thanks @acacha. But I could not find the location `node_modules\admin-lte`.Where is it ? Thanks.

**Comment by acacha** [comment]
Run npm install before. See https://docs.npmjs.com/

**Comment by afoysal** [comment]
Thanks @acacha. I run `npm isntall`. Thanks

**Comment by afoysal** [comment]
Thanks @acacha. I installed `npm install` and get `admin-lte` folder. Thanks
