### ISSUE TITLE
Laravel Dusk is active in production

### ISSUE THREAD

**Issue by starcraft66** [acacha/adminlte-laravel#337]
Laravel Dusk is included in the regular composer dependencies which causes it to load when the app environment is set to production. This is a major security risk and composer doesn't let you proceed with this configuration anyway and dumps the following error message:

  [Exception]                              
  It is unsafe to run Dusk in production. 

My recommended fix for this is to add that dependency to the "require-dev" section of the composer.json instead of in the "require" section.

**Comment by shiroamada** [comment]
I also having the same issue when I try to push to Laravel Forge.
What you can temp. do is change your .env set APP_ENV=local or testing.
At least to allow you to run.

**Comment by acacha** [comment]
Changed composer.json in last commit. Thanks!

**Comment by acacha** [comment]
As seen in other Laravel issues lie https://github.com/laravel/dusk/issues/289 it seems a problem in other packages after upgrading from Laravel 5.4 to Laravel 5.5.

The best options seems to add composer.json:

```
"extra": {
        "laravel": {
            "dont-discover": [
                "laravel/dusk"
            ]
        }
    },
```

**Comment by dmitry-ivanov** [comment]
Hi, @acacha! Can you please create new release to solve this issue for stable versions?

**Comment by acacha** [comment]
@dmitry-ivanov Done.release 5.0.5 created

**Comment by MohammedAlzard** [comment]
The best options seems to add composer.json:

```
"extra": {
        "laravel": {
            "dont-discover": [
                "laravel/dusk"
            ]
        }
    },
```

**Comment by davide-casiraghi** [comment]
In this way works but I cannot manage to test with Dusk on Travis CI.
Because TravisCI install all the composer packages every time, so if dusk is in "dont-discover" it cannot find it.

**Comment by davide-casiraghi** [comment]
I've solved adding to the default deploy script on Laravel forge the string **--no-dev**

```
cd /home/forge/ciglobalcalendar.net
git pull origin master
composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
echo "" | sudo -S service php7.3-fpm reload

if [ -f artisan ]
then
    php artisan migrate --force
fi
```

**Comment by sumeet11991** [comment]
test

**Comment by suisun2015** [comment]
cd /home/forge/..my domain..
git pull origin master
composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
echo "" | sudo -S service php7.3-fpm reload

if [ -f artisan ]
then
    php artisan migrate --force
fi

**Comment by ComeBey** [comment]
> composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

Thank you @suisun2015

**Comment by RPrasad72** [comment]
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Segmentation fault (core dumped)
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 139

I'm getting above when i was install composer

**Comment by MohammedAlzard** [comment]
use this command: 
composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

**Comment by RPrasad72** [comment]
> use this command: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

used this command but Same, error showing. please give solution for this problem
