### ISSUE TITLE
Accessing font-awesome

### ISSUE THREAD

**Issue by afoysal** [acacha/adminlte-laravel#338]
I am facing below issues due to font-awesome.

![lte1](https://user-images.githubusercontent.com/1283998/31479509-9685155c-af39-11e7-9b5b-59d0c2dab247.png)

![lte2](https://user-images.githubusercontent.com/1283998/31479516-a23a9566-af39-11e7-8d1b-dd79891c2e27.png)

![lte3](https://user-images.githubusercontent.com/1283998/31479529-ae314c20-af39-11e7-89be-5ce41a36bb0e.png)

Could anyone help me in this regard ?

**Comment by acacha** [comment]
Please be sure you have the font awesome fonts at fonts folder. See:

https://github.com/acacha/adminlte-laravel/tree/master/public/fonts

I'm not sure how you achieve to produce this problem but copying files to you public folder could solve your problem.

**Comment by afoysal** [comment]
Thanks @acacha for your reply. Here is my public folder.

![font](https://user-images.githubusercontent.com/1283998/31615186-9d5c3968-b2aa-11e7-9b14-ecefc9a6dc88.png)
