### ISSUE TITLE
I want to update the menu using the Vue.

### ISSUE THREAD

**Issue by swapnil-patel** [acacha/adminlte-laravel#339]
## Detailed description

I had installed the adminlte-laravel using your readme instruction and now i want to update the menu but i don't know how i can update that. As you use the Vue i want to stick with that only. Can you help me out in this. please tell me in which file i can add the dynamic menu so the Vue can take care of it.

**Comment by acacha** [comment]
We use spatie menu package:

https://github.com/spatie/laravel-menu

Change ou menu at config file config/menu.php:

https://github.com/acacha/adminlte-laravel/blob/master/config/menu.php

As far as I know vue is not related in any way.
