### ISSUE TITLE
Remove Bower dependencies as soon ad adminlte package is arranged to not depends on

### ISSUE THREAD

**Issue by acacha** [acacha/adminlte-laravel#345]
Temporarily (I expect) this package depends on Bower. A new npm script:

```
npm run bower
```

Install bower components in adminlte node_modules package! Yes a very ugly cheat :-(
 
Remove this ass soon as adminlte is arranged.

**Comment by Bonobomagno** [comment]
use && instead of ;

**Comment by acacha** [comment]
Now we use adminlte dist files so no need to "compile" with Laravel mix adminlte files and no more problems with bower. So I close this issue.
