### ISSUE TITLE
Login 419 (unknown status)

### ISSUE THREAD

**Issue by CicciMTS** [acacha/adminlte-laravel#347]
## Detailed description

I cloned my project, but when i try to login, ajax request returns POST error 419 (unknown status). In production login works, but in my local machine not. Can someone help me?

## My environment

* Version used: PHP 7.0
* Operating system and version: MacOS 10.12.6

**Comment by acacha** [comment]
You have to provide us with more info please and exact steps to reproduce your problem.

**Comment by acacha** [comment]
Please feel free to reopen the issue/open new issue once you can provide us with more info, Thanks!
