### ISSUE TITLE
laravel 5.5 ?

### ISSUE THREAD

**Issue by Bonobomagno** [acacha/adminlte-laravel#349]
any guide for install with laravel 5.5?

llum is not updated to 5.5
adminlte-installer is stuck to 5.4 too.

how to install it?

**Comment by Freizello** [comment]
+1 for 5.5 install instructions

**Comment by afoysal** [comment]
I installed it in Laravel 5.5.14.

**Comment by acacha** [comment]
Version 5 of this package is compatible with Laravel 5.5.

Installation instructions are the same:

```
laravel new laravel-with-admin-lte
cd laravel-with-admin-lte
adminlte-laravel install
```
Are you having any concrete problems installing this package for Laravel 5.5?

**Comment by Bonobomagno** [comment]
i cant install with adminlte-laravel installer. 
I did it by "hand". This becouse the installer dont work if you have laravel 5.5 installer.

**Comment by afoysal** [comment]
@Bonobomagno , I did not find any issue to install with Laravel 5.5.14 so far.

**Comment by martijnpr** [comment]
I'm having composer issues as well with Laravel 5.5 (composer require global for adminlte-laravel)
    - Can only install one of: illuminate/contracts[v5.4.27, v5.5.17].
    - Can only install one of: illuminate/contracts[v5.4.36, v5.5.17].
    - Can only install one of: illuminate/contracts[v5.4.9, v5.5.17].
    - Installation request for illuminate/contracts (locked at v5.5.17) -> satisfiable by illuminate/contracts[v5.5.17].

**Comment by acacha** [comment]
Have you tried composer global update? Please can you open a issue with the full error/procedure because I cannot reproduce the error in my environment no problems arise.

**Comment by acacha** [comment]
Please also remove composer cache or try to remove all tyour composer environment (try with a fresh clen new one)

**Comment by NKJ-Coders** [comment]
Salut svp comment installer la version 5.5 de laravel alors que nous sommes déjà à la version 8 ?

**Comment by manelgavalda** [comment]
@NKJ-Coders Hello, you can use the `6.0` branch of this package to install it on laravel 5.5. You just need to install the composer package with the right version and publish the views:
```
composer require "acacha/admin-lte-template-laravel:6.*"
php artisan vendor:publish --tag=adminlte --force
```
