### ISSUE TITLE
AdminLTETemplateServiceProvider' not found 

### ISSUE THREAD

**Issue by kcbikram** [acacha/adminlte-laravel#350]
## Detailed description
 I have finished following steps:
 1. composer require "acacha/admin-lte-template-laravel:4.*"
2. edit config/app.php file
Acacha\AdminLTETemplateLaravel\Providers\AdminLTETemplateServiceProvider::class,
3.  edit config/app.php file and add to alias array:
'AdminLTE' => Acacha\AdminLTETemplateLaravel\Facades\AdminLTE::class,
4. Publish files with :php artisan vendor:publish --tag=adminlte --force
 All steps done sucessfuly. while runnung server I get error like: 
[Symfony\Component\Debug\Exception\FatalThrowableError]                      
  Class 'Acacha\AdminLTETemplateLaravel\Providers\AdminLTETemplateServiceProvider' not found 

## My environment

* Version used :- PHP 7, Laravel 5.4:
* Operating system and version:-  Ubuntu 16.04):

**Comment by acacha** [comment]
Are you aware you are using 4.* version?

**Comment by acacha** [comment]
Class not found error normally are related with composer autoload, please see vendor/composer/autoload_psr4.php (show us your contents) and look here for a line:

```
    'Acacha\\AdminLTETemplateLaravel\\' => array($vendorDir . '/acacha/admin-lte-template-laravel/src'),
```

If this line is no available please remove vendor an rerun composer install. Also please try to remove composer cache.

**Comment by kcbikram** [comment]
Thanks. This solve my problem.
