### ISSUE TITLE
adminlte-laravel does not appear to remember menu state

### ISSUE THREAD

**Issue by eugenevdm** [acacha/adminlte-laravel#352]
## Detailed description

This is an enhancement request. In the adminlte demo here https://adminlte.io/themes/AdminLTE/index2.html menu state is remembered. What that means if if you click on any menu in die sidebar, e.g. Calendar, or Table/Simple Tables, the menu expands, and the content of page loads. Even if you click to any other link, the sidebar menu does not reload.

This has the effect of the sidebar always being open and the page loads seem really fast.

## Context

It would be great to reproduce this behavior. I managed to get it working in another project using pjax (https://laracasts.com/lessons/faster-page-loads-with-pjax) but I imagine we would have to see how the official AdminLTE does it and try and reproduce.

## Possible implementation

The best way would be to figure out how AdminLTE does it but I guess a Pjax implementation could work.

## Your environment

I am running Homestead on a Macbook Pro and Laravel 5.5 with a new project.

**Comment by acacha** [comment]
The same occurs on default adminlte demo page. Sorry this package now doesn't support managing menu state you have to implement that yourself or feel free to propose a PR.
