### ISSUE TITLE
XAMP - problem with paths in all.css, fonts and sign in links

### ISSUE THREAD

**Issue by marcustan138** [acacha/adminlte-laravel#353]
Tried as new install of this in ubuntu LTS 14.04 /var/www/html/myproject (eg. 192.168.1.8/myproject). 

After installation, found the problems (highlighted by some others) of wrong links of css/all.css and links to fonts.  Fixed that and managed to see the first page & can get a proper login box to enter username & password.  However, after clicking the Sign In box, it will bring you to http://192.168.1.8/login, instead of http://192.168.1.8/myproject/public/login.   

In which file is the route for Sign In box determined?

How and which file to edit to correct this error?  Tks.

**Comment by satriax** [comment]
Got same issue. I've created a virtual host for my site to make it works.

**Comment by acacha** [comment]
This project is not intended to be used with domain.com/projectname it works with domain.com . I though is not easy to make code work with both cases. You can make easy changes in your template to adapt to changes. Feel free to submit a PR if you know how to successfully suport both aproaches.
