### ISSUE TITLE
Installation Failure in Laravel 5.5 | Class 'AcachaAdminLTETemplateLaravelProvidersAdminLTETemplateServiceProvider' not found

### ISSUE THREAD

**Issue by Freizello** [acacha/adminlte-laravel#355]
## Update
i realize `adminlte-laravel install` create wrong format providers class in `config/app.php` like this :
`AcachaAdminLTETemplateLaravelProvidersAdminLTETemplateServiceProvider::class,`
instead : 
`Acacha\AdminLTETemplateLaravel\Providers\AdminLTETemplateServiceProvider::class,`

## Issue

Installation using this step provided in readme : 

`composer global require "acacha/adminlte-laravel-installer=~3.0"`
`laravel new laravel-with-admin-lte`
`cd laravel-with-admin-lte`
`adminlte-laravel install`

## Detailed Screenshot

![image](https://user-images.githubusercontent.com/12061206/32155930-14dba2b8-bd6d-11e7-8efc-c40a2571c1e2.png)

## Versions
* PHP 7.1.7
* Windows 10 Pro
* Laravel 5.5

**Comment by umairiftikhar-ca** [comment]
Seems like you're using an old command, Try this: 
 composer require "acacha/admin-lte-template-laravel:4.*"
Referring to https://github.com/acacha/adminlte-laravel#laravel-54

**Comment by acacha** [comment]
Umm I have to remove need to add Provider i config/app.php file manually because this package nows support autodiscovery

**Comment by acacha** [comment]
Also Windows problems are know because this package is using sed:

https://github.com/acacha/llum/blob/eeebe2b24ecb6371d6d16d323a117e742daf4ef1/src/Traits/LaravelConfigFile.php

So please do a manual install
