### ISSUE TITLE
Vue Login Form "remember" checkbox state ignored

### ISSUE THREAD

**Issue by Grexeo** [acacha/adminlte-laravel#356]
Checking the form.remember checkbox on the login page (LoginForm.vue) does nothing.

The AJAX request always sends remember: "", even when checked.

My environment: MacOS Sierra, Chrome 61.

**Comment by ph4r05** [comment]
I am having the same issue. Click event does not get to the checkbox, `v-model` does not change on click.

**Comment by ph4r05** [comment]
I figured out the problem, the time of `icheck` initialization matters. I assume the `icheck` is initialized before it should be. If you wrap initialization in `setTimeout(fnc, 1000)` is starts working. 

My dirty workaround:

1. I've added nextTick() to `LoginForm.vue`:

```vue
    mounted () {
        this.$nextTick(() => {
            this.initialitzeICheck('remember');
        });
    },
```

2. `InitializeIcheck.js` - wrap to document ready, set timeout.

```javascript
export default {
  methods: {
    initialitzeICheck (field) {
        const component = this;
        const compObj = $('input[name=' + field + ']');

        $(document).ready(() => {
            setTimeout(() => {
                compObj.iCheck({
                    checkboxClass: 'icheckbox_square-blue',
                    radioClass: 'iradio_square-blue',
                    increaseArea: '20%'
                });
            }, 10);

            setTimeout(() => {
                compObj.on('ifChecked', function (event) {
                    component.form.setField(field, true);
                    component.form.errors.clear(field);
                });

                compObj.on('ifUnchecked', function (event) {
                    component.form.setField(field, '');
                });

            }, 10);

        });
    }
  }
}
```

**Comment by acacha** [comment]
Thanks @ph4r05 for the report and for possible solution. There are other issues related with icheck (https://github.com/acacha/adminlte-laravel/issues/363) so I think that instead of solving this issue I will reimplement the Login component without icheck.

**Comment by ph4r05** [comment]
@acacha thanks I did the same. I used vue-toggle component
