### ISSUE TITLE
Problems working in tandem with Laravel 5.2 new "auth" stuff

### ISSUE THREAD

**Issue by rawzone** [acacha/adminlte-laravel#36]
Hello,

Just tried to spin up a new project with adminlte-laravel and the latest Laravel 5.2.

Seems like there might be some problems with the way that this package registers its routes as with the 5.2 the new web middleware is used it inject the needed classes such as \Illuminate\View\Middleware\ShareErrorsFromSession::class (see app/Http/Kernel.php).

**Comment by acacha** [comment]
I'm in progress on a new release for Laravel 5.2...

**Comment by rawzone** [comment]
Nice one @acacha - Let me know if and when you need some testing.
Until then ill simply roll my own setup with adminLTE.

And thanks for keeping the project alive!

**Comment by acacha** [comment]
@rawzone today I finally released 2.0 version with some amazing new features:

- Support Laravel 5.2
- And installer
- New Landing Page

**Comment by bahman2216** [comment]
good news. Thanks

**Comment by midium** [comment]
I think this is still not working with the very latest release of laravel as I've updated it today and now suddenly I'm facing **TokenMismatchException in VerifyCsrfToken.php line 67:** when I try to login. This also starting from a complete blank setup.

**Comment by midium** [comment]
Please forget my comment as it was due to problems with browser caching.
