### ISSUE TITLE
Laravel adminLTE given problem during installation setup

### ISSUE THREAD

**Issue by allengold** [acacha/adminlte-laravel#360]
HI I have follwed the following instructions or steps
1. composer create-project --prefer-dist laravel/laravel laravelLTE
	**cd web directory**
2. php artisan migrate

3. modified **laravel/app/Providers/AppServiceProvider.php** changing it to
    public function boot()   
    { 
      Schema::defaultStringLength(191); //added this line
    }

4. composer global require "acacha/admin-lte-template-laravel:4.*" in bash command line

5. composer update
	
6. **added** Acacha\AdminLTETemplateLaravel\Providers\AdminLTETemplateServiceProvider::class, to providers array
	and 
   **added** 'AdminLTE' => Acacha\AdminLTETemplateLaravel\Facades\AdminLTE::class, to aliases array
 to **config/app.php**

----> I got this error 
	[Symfony\Component\Debug\Exception\FatalErrorException]
	  Class 'App\Providers\Schema' not found
	
	followed by this error
        
	Script php artisan optimize handling the post-update-cmd event returned with error code 255

4. Then from the bash command line 
 php artisan vendor:publish --tag=adminlte -force

 and I got this error

 [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Acacha\AdminLTETemplateLaravel\Providers\AdminLTETemplateServiceProvider' not found
	

Please what are my doing wrong. Any help would be appreciated.
I am using laravel 5.4.36
I am using php 5.6.25

and I am also having problem setting the domain or url to e.g. laravel.dev

**Comment by nieka** [comment]
Have you imported the `Schema` class in /AppServiceProvider.php because the error your getting says it cant find that class.

**Comment by acacha** [comment]
It seems to me that your problem is not related with this package? Maybe you want to ask for support about Laravel in https://stackoverflow.com/questions/tagged/laravel
