### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by hermesfelipe** [acacha/adminlte-laravel#364]
## Detailed description

I have the exact same issue as described here: https://github.com/acacha/adminlte-laravel/issues/254
and here: https://github.com/acacha/adminlte-laravel/issues/273

*********** part of the error: ***************
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - acacha/adminlte-laravel-installer 3.1.6 requires acacha/admin-lte-template-laravel dev-master -> satisfiable by acacha/admin-lte-template-laravel[dev-master] but these conflict with your requirements or minimum-stability.
    - acacha/adminlte-laravel-installer 3.1.5 requires acacha/admin-lte-template-laravel dev-master -> satisfiable by acacha/admin-lte-template-laravel[dev-master] but these conflict with your requirements or minimum-stability.
    - acacha/adminlte-laravel-installer 3.1.4 requires acacha/admin-lte-template-laravel dev-master -> satisfiable by acacha/admin-lte-template-laravel[dev-master] but these conflict with your requirements or minimum-stability.

(...)
*****************************

## Context

I am using a Homestead environment, laravel works fine. I've already tried the solutions on both issues above (composer global update), still no luck :(

## Possible implementation

Not obligatory, but suggest an idea for implementing addition or change.

## Your environment
PHP 7.1.10-1+ubuntu16.04.1+deb.sury.org+1

**Comment by acacha** [comment]
As I say in the ohter issues I was unable to reproduce the problem. I don't see any dev-master references in the packages involved. Please could somebody provide acces to an environment on exactly steps to reproduce the problem?
