### ISSUE TITLE
Route Auth should be optional for better route management

### ISSUE THREAD

**Issue by shiroamada** [acacha/adminlte-laravel#366]
I would like to have different login screen for my different sub-domain.

In normal Laravel, I just put my login route above the `Auth::routes();` then Laravel routes will be organized based on the priority of matching.

However, for adminlte-laravel  is included package together.
In `vendor/acacha/admin-lte-template-laravel/src/Http/routes.php:9` added `Route::auth();`.

In this way, I can't manually set the priorities in route.

What I suggest is remove `Route::auth();`.

And added in manually, added in `web.php`

```
Route::group(['middleware' => 'web'], function () {

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes

    Auth::routes();

    Route::get('/home', 'HomeController@index');
```
In my case, I have to remove it in order to archive my goal.

* Version used (e.g. PHP 5.6, HHVM 3): PHP 7.1
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): MacOS
* Laravel 5.5.21

**Comment by Hornet-Wing** [comment]
Can this please be fixed/merged?

**Comment by acacha** [comment]
It could be but please submit a PR for every single feature you want to change. to many files are modified!

**Comment by acacha** [comment]
New config option added to enable users disable package routes.
