### ISSUE TITLE
How to use datepicker/ckeditor/etc ?

### ISSUE THREAD

**Issue by JurjenRoels** [acacha/adminlte-laravel#369]
Hello,

I am using adminlte-laravel but I am completely stuck on how to use datepicker or CKeditor.

It is within the package, but how do you enable them. I have searched hours.

I am new to vue and laravel-mix.

Can someone point me to the right tutorial?

Thanks in advance.

**Comment by acacha** [comment]
This github project is for Laravel Project not the original adminlte theme. Sorry I don't know the anwer to your question. Please ask on stackoverflow or maybe https://github.com/acacha/adminlte-laravel

**Comment by JurjenRoels** [comment]
Acacha,

I assume you included all the necessary JS an CSS in the adminLTE for Laravel in webpage/Laravel mix.

When I try to add my own JS to the blades I get errors and I have issues understanding how to incorporate my own additions.

I was hoping to get some pointers on how this was setup in the acacia package and how to include my own CSS an JS to the webpack?
