### ISSUE TITLE
Class 'AcachaAdminLTETemplateLaravelProvidersAdminLTETemplateServiceProvider' not found

### ISSUE THREAD

**Issue by cuihuanhuan** [acacha/adminlte-laravel#370]
* Version used (PHP7):
* Operating system and version (Windows 7):

## Detailed description

In ProviderRepository.php line 208:
                                                                                
  Class 'AcachaAdminLTETemplateLaravelProvidersAdminLTETemplateServiceProvider' not found

**Comment by acacha** [comment]
This problem occurss with Windows environments. I don't use this environment please can anyone using this environment can propose a PR to solves this problem?
