### ISSUE TITLE
Warning: mb_strtolower(): Unknown encoding "(null)" in D:\xampp\htdocs\lte\laravel-with-admin-lte\vendor\laravel\framework\src\Illuminate\Support\Str.php on line 427

### ISSUE THREAD

**Issue by pwnkmrsh** [acacha/adminlte-laravel#372]
Warning: mb_strtolower(): Unknown encoding "(null)" in D:\xampp\htdocs\lte\laravel-with-admin-lte\vendor\laravel\framework\src\Illuminate\Support\Str.php on line 427

Warning: mb_strtolower(): Unknown encoding "(null)" in D:\xampp\htdocs\lte\laravel-with-admin-lte\vendor\laravel\framework\src\Illuminate\Support\Str.php on line 427

**Comment by acacha** [comment]
I don't use Windows so I can reproduce the problem. As commented in the docs this projectes use sed an other tools that can behave different in different platforms. If somebody knows how to adapt the project to Windows please feel pree to propose a PR.
