### ISSUE TITLE
Interface error during installation

### ISSUE THREAD

**Issue by tientongfm** [acacha/adminlte-laravel#375]
## Detailed description
I followed the instructions on the page  https://github.com/acacha/adminlte-laravel  and got the following error:

+ icon is not displayed
![screenshot 15](https://user-images.githubusercontent.com/28670662/34318446-236d4c02-e7fa-11e7-9445-3783a1c88ee0.png)
![screenshot 16](https://user-images.githubusercontent.com/28670662/34318448-2c96f7ce-e7fa-11e7-9775-98df45cc7a0a.png)

## Your environment
laravel --version => Laravel Framework 5.5.27
php artisan --version => PHP 7.1.12
composer --version => Composer version 1.5.6 2017-12-18 12:09:18

#I look forward to receiving the support. Thankyou!

**Comment by acacha** [comment]
Please check at network tab if you have any 404 error. Sometimes this error occurs when no fonts are found: it could be many thinks but most usually you are not using a domain (using domain.com/app instead of domain.com) or maybe you have some problems connecting to Internet?
