### ISSUE TITLE
Sidebar-toggle and sidebar trees not working

### ISSUE THREAD

**Issue by cayvowcorir** [acacha/adminlte-laravel#377]
## Detailed description
The sidebar is not collapsible. Clicking the menu button doesn't respond. 

##Replication
1. laravel new project
2. cd project && adminlte-laravel install
3. composer install
4. npm install
5. npm run dev
6. php artisan serve

I have traced the problem to app.js being overwritten by npm run dev, and copying it again from vendor folder solves it. But problem is, every time I npm run dev, after adding a vue component maybe, i cannot dare delete app.js in the public/js folder.

**Comment by fedeverdi** [comment]
Same Issue here

**Comment by mvishu405** [comment]
<ul class="sidebar-menu" data-widget="tree">



update this into sidebar.blade.php for sidebar collapsing

**Comment by fretelweb** [comment]
Works but Sidebar dont hide when hit the ham,burger icon.

**Comment by fretelweb** [comment]
data-toggle="offcanvas" changed to data-toggle="push-menu"

**Comment by AmrEmara** [comment]
i'm facing the same issue with the multilevel dropdown, did you find a solution for the problem ? @acacha

**Comment by acacha** [comment]
Last commit simplified Laravel mix compilation and I updated all.css and app.js files in public folder. Now I don't have any problems. As soon as I release version 6.0 this issue will be solved!

**Comment by acacha** [comment]
@fretelweb proposed solution is already submmited to the project. Thanks!

**Comment by acacha** [comment]
@mvishu405 proposed solutions is already submmited to the project. Thanks!
