### ISSUE TITLE
When logged in home.blade.php not showing

### ISSUE THREAD

**Issue by RymndMl** [acacha/adminlte-laravel#38]
Hi,

First of all, thanks for the great work you put together!

I did a basic install for Laravel 5.2 as described.
The php file home.blade.php is NOT showing it's content.

From app.blade.php I see: @yield('main-content')
So changed @section('content') to @section('main-content') en it works.

Thanks,
Ray.

**Comment by acacha** [comment]
Thanks! Changed: https://github.com/acacha/adminlte-laravel/commit/bb47984eb8405a252c923003c01e85352e399527

**Comment by acacha** [comment]
New release 2.0.1 solves this problem
