### ISSUE TITLE
Routes login/register not working

### ISSUE THREAD

**Issue by davidblasco** [acacha/adminlte-laravel#380]
I just follow all the steps for installing this package from scratch and I can't manage to enter the register or login page. Not found error.

I did the migrate and make:auth as well and didn't work for me. Any idea why?

**Comment by shiroamada** [comment]
Are you having a blank page?
You might inspect and check what is the error. It could be JS error that Vue component not able initialise.

**Comment by acacha** [comment]
@davidblasco please provide more info at least the exact steps you follow and the errors you see
