### ISSUE TITLE
webpack build fail for app.js

### ISSUE THREAD

**Issue by shiroamada** [acacha/adminlte-laravel#382]
https://github.com/acacha/adminlte-laravel/blob/0c7733213dfd11155b65849b9c7a9c16e8e7b775/webpack.mix.js#L20

from the above webpack.mix.js, there is require app.js, however, in your git repo, that file is missing.

I would want to run `npm run dev` to debug the vue component. But I am not able to run so.

2. How do I able to swap Vue production js to Vue full js for debug purpose?

**Comment by codetheorist** [comment]
Have you run `adminlte-laravel install` in a terminal at the root of your Laravel App?

This command should setup all of the required files for you.

**Comment by shiroamada** [comment]
@codetheorist, I am not using adminlte-laravel package to install. 

I create new laravel project (version 5.5), then use `composer require acacha/admin-lte-template-laravel:^5`

It has all the required file. 

1. I tried to create a new project and run the step again. I notice it will not run error. If I have run `php artisan vendor:publish"
It is because it has prompt:-
```bash
Copied Directory [/vendor/acacha/admin-lte-template-laravel/public/js] To [/public/js]
```
By doing this, it actually copied the app.js to /public/js folder

**Comment by acacha** [comment]
Last commits solves this errors!

**Comment by davenorthcreek** [comment]
Had to manually copy that file over on a new commit.
