### ISSUE TITLE
Any plan to Support for Laravel 5.6?

### ISSUE THREAD

**Issue by shiroamada** [acacha/adminlte-laravel#383]
Any plan to Support for Laravel 5.6?

**Comment by ahinkle** [comment]
I'm sure there will be pull requests to assist. 5.6 doesn't have too many ground breaking updates to break this app.

**Comment by acacha** [comment]
Yes of course as soon as 5.6 has been released we will see if any breaking changes applies and I will be open to PR

**Comment by AmrEmara** [comment]
@acacha so can i use laravel 5.6 for a fresh installation or should i use the 5.4 version for me to use this package ?

**Comment by shiroamada** [comment]
@AmrEmara latest version can be used in Laravel 5.5. The ReadMe file didn't up to date.

**Comment by AmrEmara** [comment]
okay thank you so much @shiroamada
