### ISSUE TITLE
Sidebar-push menu, doesn't work

### ISSUE THREAD

**Issue by cfmorales** [acacha/adminlte-laravel#384]
I have a fresh install of adminlte in laravel and this buttom doesnt work, it doesnt collapse the sidebar
Im working on laravel 5.5 using php 7,
Any suggestiong about how to fix it? I've tried with this [fa9c16c ](https://github.com/acacha/adminlte-laravel/commit/fa9c16cc0245aae41fc11498110099e4aaa2bc5a)but i dont have the menu.php

**Comment by martijnpr** [comment]
The JS still handles it under its original name, offcanvas. The easiest fix is by changing push-menu to offcanvas in mainheader.blade.php (data-toggle).

**Comment by cfmorales** [comment]
Wow it works when I change it in the inspector in google chrome, but I dont have the mainheader.blade.php in my proyect, is there any way to publish all the views?

**Comment by cfmorales** [comment]
Nvm You've fixed it

**Comment by acacha** [comment]
Thanks @martijnpr changed in https://github.com/acacha/adminlte-laravel/blob/master/resources/views/layouts/partials/mainheader.blade.php
