### ISSUE TITLE
Unable to create any vue components in resources file

### ISSUE THREAD

**Issue by ahinkle** [acacha/adminlte-laravel#386]
## Detailed description

I'm unable to create any vue components. I've created a stackoverflow question at https://stackoverflow.com/questions/48726173/vue-js-issue-adding-multiple-components. I've only used this base laravel 5.4 with this package and nothing more. Does this package move those components?

## Possible implementation

Not obligatory, but suggest an idea for implementing addition or change.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used (e.g. PHP 5.6, HHVM 3): PHP 7.2
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): MacOS
* ...

**Comment by acacha** [comment]
I close this issue cause I think you have aswers in StackOverflow.
