### ISSUE TITLE
Problem with jquery 

### ISSUE THREAD

**Issue by cfmorales** [acacha/adminlte-laravel#387]
Hi guys I have a big question, I'm trying to use the @section('scripts') in one of my pages, but I got the error with jquery It doesnt load it in the page, so I've created a new section in 

> scripts.blade.php with @yield('js') 

`

<script src="{{ url (mix('/js/app.js')) }}" type="text/javascript"></script>

@yield('js')`

And using this new section on each page of my system, Am i doing the right thing?

**Comment by acacha** [comment]
Maybe you will obtain more feedback using stackoverflow https://stackoverflow.com/?
