### ISSUE TITLE
Class 'AcachaAdminLTETemplateLaravelProvidersAdminLTETemplateServiceProvider' not found

### ISSUE THREAD

**Issue by KwameTuga** [acacha/adminlte-laravel#388]
During my installation using git bash its said

In ProviderRepository.php line 208:

  Class 'AcachaAdminLTETemplateLaravelProvidersAdminLTETemplateServiceProvider' not found

* Version used  Laravel 5.2; PHP 7.2.
* Operating system : Windows 7

**Comment by shiroamada** [comment]
what version of AdminLTE-Laravel u r using?

**Comment by acacha** [comment]
Please see other issues. It seems a problem with Windows Environment I'm not able to reproduce.

**Comment by acacha** [comment]
Note:

See https://github.com/laravel/installer/blob/master/src/NewCommand.php

It seems laravel use:

 if ('\\' !== DIRECTORY_SEPARATOR && file_exists('/dev/tty') && is_readable('/dev/tty')) {
            $process->setTty(true);
        }

What is the reason? Could be related? Also check for --non-ansi option?

**Comment by acacha** [comment]
Ok, I'm working in a new version of installer not using llum and using Laravel Package Auto discover instead so this issue would be arranged!
