### ISSUE TITLE
Problem when run npm run dev or watch

### ISSUE THREAD

**Issue by fretelweb** [acacha/adminlte-laravel#389]
## Detailed description
 near lines:
   @import (reference) "../../bower_components/bootstrap/less/mixins";
   @import (reference) "../../bower_components/bootstrap/less/variables";
   @import (reference) "variables";
    at runLoaders (D:\Usuarios\FretelWEB\Desarrollo\webapps\gTravel\node_modules\webpack\lib\NormalModule.js:192:19)

## Context

I dont work with bower so the lines

// @import (reference) "../../bower_components/bootstrap/less/mixins";
// @import (reference) "../../bower_components/bootstrap/less/variables";

dont work

## Possible implementation

works when I comment these lines in 

bootstrap-social
fullcalendar
select2

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used (e.g. PHP 5.6, HHVM 3):
* Operating system and version (e.g. Ubuntu 16.04, Windows 7):
* Link to your project:
* ...
* ...

**Comment by jake-harris** [comment]
This issue has been ongoing for a while. A few months ago the adminlte project changed or introduced a new way of referencing dependencies.

I gave up on having it run through npm and just installed via bower.

**Comment by acacha** [comment]
Yes is like @jake-harris say. I'm wondering to not compile adminlte by default maybe in following releases...
