### ISSUE TITLE
could not find auth.partials.social_login and register files

### ISSUE THREAD

**Issue by deep80** [acacha/adminlte-laravel#398]
Hi,

I am not able to find the login and register blade files. in fact the auth folder isn't there at the views section. i installed it in a homestead virtual machine and the laravel version is 5.6. please advise

**Comment by acacha** [comment]
Hi,

Views are installed by the package, please read https://laravel.com/docs/5.6/packages#views

So if you want to modify the package views you have to override the view templates using resources/views/vendor/adminlte folder as explained in docs.
