### ISSUE TITLE
Problem with <meta name="og:image" content="...."/>

### ISSUE THREAD

**Issue by AlexisHolyoak** [acacha/adminlte-laravel#399]
So I am trying to remove adminlte laravel default image in meta deleting the meta line <meta name="og:image" content="...."/>, but It doesnt seem to work, I also clear cache in facebook, this is more a question than an issue, please help is an important fail by my side.(also need to remove description, just deleting the line of meta doesnt work)

![image](https://user-images.githubusercontent.com/21972563/38902787-9ed02794-4267-11e8-9e97-0896831e6079.png)

**Comment by nieka** [comment]
If you look in your head there still some meta tags with the display image. I think if you remove them also the image isn't shown.
![image](https://user-images.githubusercontent.com/6199914/38940713-26d284ac-432b-11e8-85d2-b77bbd1cf0cb.png)

**Comment by AlexisHolyoak** [comment]
Hello Nieka, thanks for answering
![captura de pantalla de 2018-04-18 10-26-57](https://user-images.githubusercontent.com/21972563/38941909-34104b50-42f3-11e8-9c26-23450464c083.png)

As you can see in the ss I've already change what is in meta, I still Haven't figured out what is happening but image and default description still appears when I paste the url on facebook for example.

I hope you can help me there.
Many thanks.

**Comment by AlexisHolyoak** [comment]
Well I Fixed, it seems that facebook saves information, I needed to go to
http://developers.facebook.com/tools/debug 
paste my url and delete that information. Hope it helps someone
