### ISSUE TITLE
Change Menu::new() function name

### ISSUE THREAD

**Issue by Phil795** [acacha/adminlte-laravel#400]
Hello,

use your repo for many projects. For my PHP obfuscator and linter it would be better if the static functions of the Menu class were not called "new()". Can you please rename them for future versions?

Problem in acacha/admin-lte-template-laravel/config/menu.php

**Comment by nieka** [comment]
The menu class used in  acacha/admin-lte-template-laravel/config/menu.php is a class from `patie\Menu\Laravel\Menu` and so we can't change the class methode name.

**Comment by Phil795** [comment]
Okay, then I'll have to ask Sparti.
