### ISSUE TITLE
How to register first user

### ISSUE THREAD

**Issue by Dunrar** [acacha/adminlte-laravel#403]
I've installed the package on WampServer. The landing page works as it's supposed to, but I don't know how to register the first user. Is that supposed to work via the normal register form? Because for me it doesn't, the register form is not displayed correctly (HTML only) and throws a 404 error on the console if I try to use it to register.

![screenshot_1](https://user-images.githubusercontent.com/23218622/41895868-652ffcb0-7923-11e8-9349-6c229e8180a9.png)

**Environment:**

* Version used: PHP 7.2.4, MySQL 5.7.21, WAMPSERVER 3.1.3
* Operating system and version: Windows 10

**Comment by ahinkle** [comment]
Your assets should be in the public folder, so move css and javascript folders with all the contents into public.

**Comment by manelgavalda** [comment]
I close the issue as it seems that you already got the solution.
