### ISSUE TITLE
error 404 all.css login and register

### ISSUE THREAD

**Issue by JohnCubides** [acacha/adminlte-laravel#407]
How can I solve this problem?

project url = 192.168.100.100/pruebas/public/login

search css in = 192.168.100.100/css/all.css

login in to = 192.168.100.100/login.

in the installation of laravel does not generate this error

![error adminlte](https://user-images.githubusercontent.com/6472310/44997481-44caab00-af74-11e8-9139-3c3c9afe19c2.png)

![laravel](https://user-images.githubusercontent.com/6472310/44997571-01247100-af75-11e8-818e-ffdd112709a7.png)

**Comment by davenorthcreek** [comment]
You have your site being served out of a subdirectory.  You'll need to change the links to relative links or serve out of a vhost (I would use pruebas.local) if you have control over the server.

**Comment by manelgavalda** [comment]
As @davenorthcreek pointed out, you need to change the links path. Your css must be in the `public` directory, so you need to update the link to point `/pruebas/public/css/all.css`.
