### ISSUE TITLE
Error 404 500 and 503 

### ISSUE THREAD

**Issue by manshu** [acacha/adminlte-laravel#41]
These views are displaying the content. I think you guys missed something there.

**Comment by achillesp** [comment]
Hi,
I've noticed the same issue. These views load the full admin interface without checking if the user is logged in.
I would suggest to change the template to something like the login page, with no menu or sidebar.

**Comment by manshu** [comment]
@acacha @achillesp I've decided to delete those pages completely for now.

**Comment by acacha** [comment]
Last commit solves this problem
