### ISSUE TITLE
Login Issue: Username not posting as String

### ISSUE THREAD

**Issue by tantanito** [acacha/adminlte-laravel#411]
Hello, 

I'm stuck with this problem in my debugger;

message: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause' (SQL: select * from `users` where `username` = admin limit 1)"

I'm expecting the query to be this;

select * from `users` where `username` = "admin" limit 1

the username admin did not have the "" on it.

**Comment by eleazarbr** [comment]
Hello, can you confirm that the username column exists in your users table?

**Comment by tantanito** [comment]
Wew. This is embarassing. I was using the old database, with no username

Thanks.
