### ISSUE TITLE
How install adminlte 3 with composer in laravel?

### ISSUE THREAD

**Issue by paraguayo7** [acacha/adminlte-laravel#414]
How do I install adminlte version 3 in laravel 5.8 with composer? version 2 I installed it with:
    
> composer require acacha/admin-lte-template-laravel

and version 3 I try with:

> composer require acacha/admin-lte-template-laravel:3.*

but version 3 doesn't generate the template files, thanks.

**Comment by manelgavalda** [comment]
Sorry for the late reply, but this package only works with AdminLTE 2 version as it is difficult to keep 2 different AdminLTE versions in the same package.
