### ISSUE TITLE
Laravel 6 support?

### ISSUE THREAD

**Issue by davenorthcreek** [acacha/adminlte-laravel#417]
## Detailed description

Just a question and perhaps a place to bookmark updates/changes for Laravel 6, specifically the laravel-ui package and how this package can piggyback off of that major change in Laravel.

## Context

As we move to Laravel 6 and further, Taylor et al are making it easier to use their preferred setups.  My comfort level with adminlte and my experience using this package on multiple projects means I am hoping this package evolves with Laravel and provides an alternative to the paid offerings that Laravel pushes us towards.

## Possible implementation

I can't really help here except with possible bug reports when you have something you want tested.  I am interested in your take on php artisan ui:auth and whether we will need to change our install process.

## Your environment

* I'm building on Ubuntu with various versions of PHP 7.1+, and I haven't jumped to Laravel 6 yet, and won't for new projects until AdminLTE is ready for me :-)

**Comment by padre** [comment]
@acacha do you plan to make the package compatible with laravel 6?

Thank you.

**Comment by wono77** [comment]
If process "composer update" with laravel 6.0 configuraion in composer.json, errors occured like below in php 7.2.14.
It looks like need patch acacha/adminlte-laravel.

\adminlte>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove acacha/user 0.2.2
    - Conclusion: don't install acacha/user 0.2.2
    - Conclusion: don't install acacha/user 0.2.1
    - Conclusion: don't install laravel/framework v6.0.3
    - Conclusion: don't install laravel/framework v6.0.2
    - Installation request for acacha/user ~0.2 -> satisfiable by acacha/user[0.2.0, 0.2.1, 0.2.2].
    - Conclusion: don't install laravel/framework v6.0.1
    - acacha/user 0.2.0 requires laravel/framework ^5.3 -> satisfiable by laravel/framework[5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - Can only install one of: laravel/framework[v6.0.0, 5.3.x-dev].
    - Can only install one of: laravel/framework[v6.0.0, 5.4.x-dev].
    - Can only install one of: laravel/framework[v6.0.0, 5.5.x-dev].
    - Can only install one of: laravel/framework[v6.0.0, 5.6.x-dev].
    - Can only install one of: laravel/framework[v6.0.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v6.0.0, 5.8.x-dev].
    - Installation request for laravel/framework 6.0.* -> satisfiable by laravel/framework[v6.0.0, v6.0.1, v6.0.2, v6.0.3].

**Comment by alexflorea2** [comment]
Laravel 5.8 to 6 update
getting this err on PHP 7.3

composer.json 
```
 "require": {
        "php": ">=5.5.9",
        "laravel/framework": "^6.0",
        "acacha/admin-lte-template-laravel": "^6.0",
```

console output
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - acacha/admin-lte-template-laravel 6.0 requires laravel/framework ^5.4 -> satisfiable by laravel/framework[5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev, v5.4.0, v5.4.1, v5.4.10, v5.4.11, v5.4.12, v5.4.13, v5.4.14, v5.4.15, v5.4.16, v5.4.17, v5.4.18, v5.4.19, v5.4.2, v5.4.20, v5.4.21, v5.4.22, v5.4.23, v5.4.24, v5.4.25, v5.4.26, v5.4.27, v5.4.28, v5.4.29, v5.4.3, v5.4.30, v5.4.31, v5.4.32, v5.4.33, v5.4.34, v5.4.35, v5.4.36, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8, v5.4.9, v5.5.0, v5.5.1, v5.5.10, v5.5.11, v5.5.12, v5.5.13, v5.5.14, v5.5.15, v5.5.16, v5.5.17, v5.5.18, v5.5.19, v5.5.2, v5.5.20, v5.5.21, v5.5.22, v5.5.23, v5.5.24, v5.5.25, v5.5.26, v5.5.27, v5.5.28, v5.5.29, v5.5.3, v5.5.30, v5.5.31, v5.5.32, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.38, v5.5.39, v5.5.4, v5.5.40, v5.5.41, v5.5.42, v5.5.43, v5.5.44, v5.5.45, v5.5.46, v5.5.47, v5.5.48, v5.5.5, v5.5.6, v5.5.7, v5.5.8, v5.5.9, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.12, v5.7.13, v5.7.14, v5.7.15, v5.7.16, v5.7.17, v5.7.18, v5.7.19, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.24, v5.7.25, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.1, v5.8.10, v5.8.11, v5.8.12, v5.8.13, v5.8.14, v5.8.15, v5.8.16, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.21, v5.8.22, v5.8.23, v5.8.24, v5.8.25, v5.8.26, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.5, v5.8.6, v5.8.7, v5.8.8, v5.8.9] but these conflict with your requirements or minimum-stability.
    - acacha/admin-lte-template-laravel 6.0 requires laravel/framework ^5.4 -> satisfiable by laravel/framework[5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev, v5.4.0, v5.4.1, v5.4.10, v5.4.11, v5.4.12, v5.4.13, v5.4.14, v5.4.15, v5.4.16, v5.4.17, v5.4.18, v5.4.19, v5.4.2, v5.4.20, v5.4.21, v5.4.22, v5.4.23, v5.4.24, v5.4.25, v5.4.26, v5.4.27, v5.4.28, v5.4.29, v5.4.3, v5.4.30, v5.4.31, v5.4.32, v5.4.33, v5.4.34, v5.4.35, v5.4.36, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8, v5.4.9, v5.5.0, v5.5.1, v5.5.10, v5.5.11, v5.5.12, v5.5.13, v5.5.14, v5.5.15, v5.5.16, v5.5.17, v5.5.18, v5.5.19, v5.5.2, v5.5.20, v5.5.21, v5.5.22, v5.5.23, v5.5.24, v5.5.25, v5.5.26, v5.5.27, v5.5.28, v5.5.29, v5.5.3, v5.5.30, v5.5.31, v5.5.32, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.38, v5.5.39, v5.5.4, v5.5.40, v5.5.41, v5.5.42, v5.5.43, v5.5.44, v5.5.45, v5.5.46, v5.5.47, v5.5.48, v5.5.5, v5.5.6, v5.5.7, v5.5.8, v5.5.9, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.12, v5.7.13, v5.7.14, v5.7.15, v5.7.16, v5.7.17, v5.7.18, v5.7.19, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.24, v5.7.25, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.1, v5.8.10, v5.8.11, v5.8.12, v5.8.13, v5.8.14, v5.8.15, v5.8.16, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.21, v5.8.22, v5.8.23, v5.8.24, v5.8.25, v5.8.26, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.5, v5.8.6, v5.8.7, v5.8.8, v5.8.9] but these conflict with your requirements or minimum-stability.
    - Installation request for acacha/admin-lte-template-laravel ^6.0 -> satisfiable by acacha/admin-lte-template-laravel[6.0].

```

Any advice ? 
Thank you

**Comment by fredroo** [comment]
@acacha this project will support LARAVEL 6 or will be stoped in 5.8?

**Comment by lucasrothamel** [comment]
@acacha assuming no Laravel 6 or 7 support will be coming at all? Means this package is abandoned?

**Comment by manelgavalda** [comment]
Sorry for the delay, this week I will try to update this project to make it compatible with Laravel 6 version.

The problem is that we needed to remove some dependencies that require the laravel 5 version, so this week I will try to remove them and thus make the project easier to update in the future.

Once this is compatible with Laravel 6, I will see how to make it compatible with Laravel 7 and the laravel / ui package.

**Comment by manelgavalda** [comment]
You can finally use this package with Laravel 6 #430
