### ISSUE TITLE
Not Working Composer Install "acacha/admin-lte-template-laravel": "5.0.5"

### ISSUE THREAD

**Issue by JoseLuis21** [acacha/adminlte-laravel#434]
Error 15-10-2020!

The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
    Failed to download acacha/admin-lte-template-laravel from dist: The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems): ZipArchive::extractTo(/var/www/vendor/composer/7189160f/acacha-adminlte-laravel-0c77332/public/plugins/License.txt): failed to open stream: File exists
    Now trying to download from source
  - Installing acacha/admin-lte-template-laravel (5.0.5): Cloning 0c7733213d from cache
    0c7733213dfd11155b65849b9c7a9c16e8e7b775 is gone (history was rewritten?)

**Comment by manelgavalda** [comment]
Hello Jose,
What version of Laravel are you using? Can you try clearing the composer cache and run `composer install` it again:
```
composer clearcache
```

**Comment by JoseLuis21** [comment]
> Hello Jose,
> What version of Laravel are you using? Can you clear composer cache and try it again:
> 
> ```
> composer clearcache
> ```

Not working thanks

**Comment by manelgavalda** [comment]
Sorry, but I'm unable to reproduce the error. What version of Laravel are you using?
