### ISSUE TITLE
Routes not working

### ISSUE THREAD

**Issue by intositeme** [acacha/adminlte-laravel#47]
in my own routes.php file i have 
```
Route::group(['middleware' => 'web'], function () {
    Route::auth();
    Route::get('/', 'IndexController@index');
});
```
But it keeps going to the Pratt Landing Page

**Comment by acacha** [comment]
Hello @intositeme,

Could you give us more info please? I can reproduce the problem. Wich version of Laravel are you using?

**Comment by schealex** [comment]
same here the routes from vendor override the routes from the app itself

**Comment by acacha** [comment]
Ok now I understand! Two thinks to take into account:

1) In file config/app.php put App\Providers\RouteServiceProvider::class after AdminLTETemplateServiceProvider service provider

2) Change RouteServiceProvider map method to:

```php
public function map(Router $router)
    {
        $this->app->booted(function () use ($router) {
            $router->group(['namespace' => $this->namespace], function ($router) {
                require app_path('Http/routes.php');
            });
        });
    }
```

**Comment by schealex** [comment]
i just completly removed the AdminLTE Service provider, as i really don't see any need for it :)

but the posted fix works too

**Comment by acacha** [comment]
Yes once package publish files you can remove AdminLTE service provider so it's an option ;-)

**Comment by spurdow** [comment]
Same issue, but having a hard time debugging when the answer is here. I knew that it overrided the routing stuff, but its really helpful if you put a 'warning message' in the readme file. thanks

**Comment by aliefmaksum** [comment]
Yeah, I also confused with these issues, I think it's worth to notify in the main page.

**Comment by acacha** [comment]
Added to README.

**Comment by GSheltonIII** [comment]
I am facing this issue as well. Changing the order of the classes in app.php and changing the code in RouteServiceProvider did not fix it. And oddly enough if I remove the service provider as @schealex stated, it fails to load the home.

The only way I could fix it was to move all routes from the vendor routes file to the main one. Seems to be working for me so far.

**Comment by minedun6** [comment]
not a solution as anyone that tries to use ur project is goiung to be downloading the vendor with prefilled routes.
