### ISSUE TITLE
Redirect to login

### ISSUE THREAD

**Issue by marioene** [acacha/adminlte-laravel#49]
Hi,

How to redirect to login page?

I was trying with this code  in my routes.php file, but not working (Pratt Landing page showing).

```
`
Route::get('/', function () {
    return view('auth.login');
});

Route::group(['middleware' => ['web']], function () { ...
`




```

**Comment by acacha** [comment]
See:

 https://github.com/acacha/adminlte-laravel/issues/47

or

https://github.com/acacha/adminlte-laravel#laravel-routes
