### ISSUE TITLE
Suggestion - Admin theme

### ISSUE THREAD

**Issue by ChristianGiupponi** [acacha/adminlte-laravel#5]
AdminLTE is and admin theme, so why don't create and admin or backend folders in which save all the assets and the view?

Something like:

~~~
views/
    - backend/
        - home.blade.php

public/
    - backend/
         - js/
         - css/
         - img/
~~~

I think that this will create a cleaner project, what do you think?

**Comment by acacha** [comment]
Thank you I'll take you suggestion on consideration but I'm not yet sure about the roadmap of this package. One think I have to consider is if I completely separate backend from frontend (like many tools as sleeping-owl/admin) or merge frontend/backend and using roles to control what to show to users or may letting package users decide and let users decide.So give some time to think about it!
