### ISSUE TITLE
Published files and elixir versions.

### ISSUE THREAD

**Issue by achillesp** [acacha/adminlte-laravel#50]
Hello!
One issue I faced is with published files when using the version feature of elixir.
Elixir creates a /public/build path and puts versioned css and js files in there.
But this breaks the relative paths that these files have for calling other files.

**Comment by achillesp** [comment]
I think this is easily fixed by changing paths to absolute instead of relative when calling fonts and images in the following .less files. 

bootstrap/variables.less
adminlte/variables.less

**Comment by acacha** [comment]
Hi @achillesp I think bootstrap/variables.less and adminlte/variables.less in this projecte are the same files from parent/upstream project Adminlte, see https://github.com/almasaeed2010/AdminLTE

So maybe the issue would be submitted to this project?

I also think you can configure Elixir to adjust with adminlte.
