### ISSUE TITLE
Implement ACL

### ISSUE THREAD

**Issue by davejal** [acacha/adminlte-laravel#54]
Hi I'm trying to implement ACL.

I followed [this tutorial](http://heera.it/laravel-5-1-x-acl-middleware#.Vtj-j5wrKhc) some time ago and got it to work.
But this uses different auth then yours.

How can I implement acl to AdminLTE.

I hope you can define the steps required.

**Comment by acacha** [comment]
I have in mind to create a Package with name "alacarta" for managing menus with acl but I've no time :-(
But i recommend you using Laravel ACL/Authoritzation support see https://laravel.com/docs/master/authorization. And maybe combine this with some library like entrust to provide some persistance support for acls 

https://github.com/Zizaco/entrust

**Comment by wpouseele** [comment]
I've used a combination of https://github.com/spatie/laravel-permission and https://github.com/spatie/laravel-authorize to successfully implement this feature

**Comment by davejal** [comment]
@wpouseele could you give the steps you took to do this?

**Comment by vesper8** [comment]
> @wpouseele could you give the steps you took to do this?
+1

**Comment by anethum** [comment]
@wpouseele +1

**Comment by wpouseele** [comment]
@davejal @anethum Just follow the installation steps for the laravel-permission and laravel-authorize packages. I've used the default @can directives to check access in the navigation. Routes are protected by the middleware feature of the laravel-authorize package.

**Comment by acacha** [comment]
Thanks @wpouseele
