### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by fabnoe** [acacha/adminlte-laravel#55]
I am not sure if I got this right. adminlte-laravel offers "just" the boilerplate, doesn't it?

The installation worked fine, but I miss some generators or templates for form, tables etc.
I am not sure how to proceed now. Where is the documentation for the views etc.?

Thanks

**Comment by acacha** [comment]
This package does not install all demo pages of adminlte because I think apps rarely needs all the templates in the same app. But you can easy install any page of adminlte demo copying body template and combining with basic laravel blade layout provided with this package

**Comment by fabnoe** [comment]
Thanks. Maybe you could implement a simple Laravel CRUD/Scaffolding example at some point.
