### ISSUE TITLE
Error converting exising Laravel project

### ISSUE THREAD

**Issue by fabnoe** [acacha/adminlte-laravel#58]
I tried to install adminlte to an existing 5.2 laravel project

Command:
`adminlte-laravel install
`

Result:
```
Running llum package AdminLTE...
Running composer require acacha/admin-lte-template-laravel
Using version ^2.0 for acacha/admin-lte-template-laravel
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing acacha/admin-lte-template-laravel (2.0.7)
    Downloading: 100%         

Writing lock file
Generating autoload files
> php artisan optimize
Generating optimized class loader
sed: 1: "/]/{=;q};": extra characters at the end of q command
sed: stdout: Broken pipe
sed: 1: "/Users/some.user/OM ...": invalid command code f
sed: 1: "/]/{=;q};": extra characters at the end of q command
sed: 1: "/Users/some.user/OM ...": invalid command code f
File /Users/some.user/OMG/openfuse/config/app.php updated correctly
sed: 1: "/Users/some.user/OM ...": invalid command code f
File /Users/some.user/OMG/openfuse/config/services.php updated correctly
Adding Acacha\AdminLTETemplateLaravel\Providers\AdminLTETemplateServiceProvider::class to Laravel config app.php file
sed: 1: "/Users/some.user/OM ...": invalid command code f
Adding Acacha\AdminLTETemplateLaravel\Facades\AdminLTE::class to Laravel config app.php file
sed: 1: "/Users/some.user/OM ...": invalid command code f
Nothing to publish for tag [adminlte].

```

**Comment by acacha** [comment]
Hi @fabnoe

Can you give more info to reproduce the problem? Which operating system are you using?

**Comment by acacha** [comment]
I ask for the operating system because I think it will be a problem with sed version because I use Ubuntu with gnu sed but i think MAC us another version of sed. http://stackoverflow.com/questions/16745988/sed-command-works-fine-on-ubuntu-but-not-mac

**Comment by fabnoe** [comment]
It's OSX 10.10.5 (14F27). It worked without llum ;-)

**Comment by acacha** [comment]
Ok thanks @fabnoe the option --no-llum.is for this cases.... I don't have a osx to try it but as soon as I can I will check if I can find a more multiplatform solution

**Comment by acacha** [comment]
@fanoe could you check if installing gnu-sed in OSX solves your problem?

 brew install gnu-sed


see http://apple.stackexchange.com/questions/195590/is-it-possible-to-get-gnu-sed-for-osx

Thanks!

**Comment by acacha** [comment]
Or maybe you have to use:

brew install gnu-sed --with-default-names

**Comment by pdavila13** [comment]
professor-3:app professor$ ls -la /usr/bin/sed
-rwxr-xr-x  1 root  wheel  38016 10 sep  2014 /usr/bin/sed
professor-3:app professor$ brew install gnu-sed --with-default-names
==> Downloading http://ftpmirror.gnu.org/sed/sed-4.2.2.tar.bz2
==> Downloading from http://ftp.rediris.es/mirror/GNU/gnu/sed/sed-4.2.2.tar.bz2
######################################################################## 100,0%
==> ./configure --prefix=/usr/local/Cellar/gnu-sed/4.2.2
==> make install
🍺  /usr/local/Cellar/gnu-sed/4.2.2: 9 files, 421.4K, built in 52 seconds
professor-3:app professor$ which sed
/usr/local/bin/sed
professor-3:app professor$ ls -la /usr/local/bin/sed
lrwxr-xr-x  1 professor  admin  31 31 mar 17:07 /usr/local/bin/sed -> ../Cellar/gnu-sed/4.2.2/bin/sed
professor-3:app professor$ man sed
professor-3:app professor$ 
professor-3:app professor$ llum boot
Running composer require barryvdh/laravel-ide-helper
Using version ^2.1 for barryvdh/laravel-ide-helper
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
File /Users/professor/Code/app/config/app.php updated correctly
File /Users/professor/Code/app/config/services.php updated correctly
Adding Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class to Laravel config app.php file
A new helper file was written to _ide_helper.php
Running composer require barryvdh/laravel-debugbar
Using version ^2.2 for barryvdh/laravel-debugbar
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
File /Users/professor/Code/app/config/app.php already supports llum.
Llum is already installed. Skipping...
Adding Barryvdh\Debugbar\ServiceProvider::class to Laravel config app.php file
Adding Barryvdh\Debugbar\Facade::class to Laravel config app.php file
Copied File [/vendor/barryvdh/laravel-debugbar/config/debugbar.php] To [/config/debugbar.php]
Publishing complete for tag []!
File database/database.sqlite created successfully
.env file updated successfully
Running php artisan migrate...
Migration table created successfully.
Migrated: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_100000_create_password_resets_table
Running php artisan serve --port=8000

**Comment by acacha** [comment]
So confirmed that it works with gnu seed on MAC OS. Updated README.md https://github.com/acacha/adminlte-laravel#gnu-sed-on-mac-os
