### ISSUE TITLE
Routes still not being overriden 

### ISSUE THREAD

**Issue by minedun6** [acacha/adminlte-laravel#59]
The default routes are stil not being overriden properly evn after completely removing the AdminLTEServiceProvider from my app.php file and even after changing the code inside the map function in the RouteServiceProvider

`public function map(Router $router)
    {
        $this->app->booted(function () use ($router) {
            $router->group(['namespace' => $this->namespace], function ($router) {
                require app_path('Http/routes.php');
            });
        });
    }`
Please is there any fix to this ?

**Comment by acacha** [comment]
@minedun6 Have you seen issue https://github.com/acacha/adminlte-laravel/issues/47 ? I think it could helps you
