### ISSUE TITLE
global installation screw up laravel on windows

### ISSUE THREAD

**Issue by steenrabol** [acacha/adminlte-laravel#60]
Hi

After I did this:
composer global require "acacha/adminlte-laravel-installer=~2.0"

Installing a new Laravel project is not possible any more

Crafting application...

  [Symfony\Component\Process\Exception\RuntimeException]
  TTY mode is not supported on Windows platform.

new [--dev] [--] <name>

**Comment by acacha** [comment]
It seems is a Laravel installer package issue: https://github.com/laravel/installer/pull/48 don't blame laravel adminlte 😈

**Comment by steenrabol** [comment]
Hi
yes, I found out late the same day... I'm SO SORRY that I blamed you guys!
