### ISSUE TITLE
'sed' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by steenrabol** [acacha/adminlte-laravel#61]
Hi
After fixing the Laravel installer issue I tried again:

adminlte-laravel install
Running llum package AdminLTE...
Running composer require acacha/admin-lte-template-laravel
Using version ^2.0 for acacha/admin-lte-template-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing acacha/admin-lte-template-laravel (2.0.7)
    Loading from cache

Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
'sed' is not recognized as an internal or external command,
operable program or batch file.
Adding Acacha\AdminLTETemplateLaravel\Providers\AdminLTETemplateServiceProvider::class to Laravel config app.php file
Adding Acacha\AdminLTETemplateLaravel\Facades\AdminLTE::class to Laravel config app.php file
The filename, directory name, or volume label syntax is incorrect.
Nothing to publish for tag [adminlte].

**Comment by steenrabol** [comment]
And using a BASH on windows:

$ adminlte-laravel install
Running llum package AdminLTE...
Running composer require acacha/admin-lte-template-laravel
Using version ^2.0 for acacha/admin-lte-template-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing acacha/admin-lte-template-laravel (2.0.7)
    Loading from cache

Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
Adding Acacha\AdminLTETemplateLaravel\Providers\AdminLTETemplateServiceProvider::class to Laravel config app.php file
The filename, directory name, or volume label syntax is incorrect.
Adding Acacha\AdminLTETemplateLaravel\Facades\AdminLTE::class to Laravel config app.php file


  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'AcachaAdminLTETemplateLaravelProvidersAdminLTETemplateServiceProvide
  r' not found

**Comment by acacha** [comment]
@steenrabol You can use this package with option --no-llum for a full backward compatible version without using llum package or any external command dependency like llum.

Anyway thanks for your time to post issues asap I will try to make package more multiplatform but now is only tested with Ubuntu ans systems using GNU sed.

**Comment by acacha** [comment]
See https://github.com/acacha/adminlte-laravel#gnu-sed-on-mac-os and https://github.com/acacha/adminlte-laravel/issues/58

**Comment by pmirandaarias** [comment]
Same problem in windows

**Comment by oghenez** [comment]
any solution for windows, same problem here
