### ISSUE TITLE
Routes breaking under Laravel 5.2.29

### ISSUE THREAD

**Issue by GSheltonIII** [acacha/adminlte-laravel#63]
(Fairly new to laravel, please be gentle.)

Fresh install of laravel 5.2.29. Following instructions for manual 5.2 installation.

Once I edit app.php to include:
To register the Service Provider edit config/app.php file and add to providers array:
```
/*
* Acacha AdminLTE template provider
 */
Acacha\AdminLTETemplateLaravel\Providers\AdminLTETemplateServiceProvider::class,
```
To Register Alias edit config/app.php file and add to alias array:
```
/*
* Acacha AdminLTE template alias
*/
'AdminLTE' => Acacha\AdminLTETemplateLaravel\Facades\AdminLTE::class,
```

I can no longer change the / and /home routes. Regardless of what is in my routes file, '/' always directs to welcome.blade.php.

I was running under 5.2.16 with no problems. When I updated to 5.2.29, my routes broke. I started a fresh copy and began to add things in one at a time until the issue happened.

To recreate this, install a fresh copy of Laravel. Change '/' route to something else (welcome2) and create a blade for it. Ensure you are seeing the new page. Begin the installation of adminlte-laravel. As soon as app.php is updated, '/' will return to welcome.blade.php again with no changes to the routes.

Please let me know if there is more information needed.

**Comment by SatoshiDark** [comment]
Hi, take a look at **https://github.com/acacha/adminlte-laravel#laravel-routes**

**Comment by GSheltonIII** [comment]
Thank you.

This: https://github.com/acacha/adminlte-laravel/issues/47 is where I found the answer.

In the installation instructions, it should say:
"Yes once package publish files you can remove AdminLTE service provider so it's an option ;-)"

Thank you again SatoshiDark
