### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by jzmwebdevelopment** [acacha/adminlte-laravel#64]
Why am I getting the following error on Install?

`Running composer require acacha/admin-lte-template-laravel
Using version ^2.0 for acacha/admin-lte-template-laravel
./composer.json has been updated
PHP Fatal error:  Cannot declare class PackageVersions\Installer, because the name is already in use in phar:///usr/local/Cellar/composer/1.0.0-alpha11/libexec/composer.phar/src/Composer/Plugin/PluginManager.php(246) : eval()'d code on line 17

Fatal error: Cannot declare class PackageVersions\Installer, because the name is already in use in phar:///usr/local/Cellar/composer/1.0.0-alpha11/libexec/composer.phar/src/Composer/Plugin/PluginManager.php(246) : eval()'d code on line 17
sed: 1: "/]/{=;q};": extra characters at the end of q command
sed: 1: "/Users/jessmckenzie/Sit ...": invalid command code j
sed: 1: "/]/{=;q};": extra characters at the end of q command
sed: 1: "/Users/jessmckenzie/Sit ...": invalid command code j
File /Users/jessmckenzie/Sites/MEP/config/app.php updated correctly
sed: 1: "/Users/jessmckenzie/Sit ...": invalid command code j
File /Users/jessmckenzie/Sites/MEP/config/services.php updated correctly
Adding Acacha\AdminLTETemplateLaravel\Providers\AdminLTETemplateServiceProvider::class to Laravel config app.php file
sed: 1: "/Users/jessmckenzie/Sit ...": invalid command code j
Adding Acacha\AdminLTETemplateLaravel\Facades\AdminLTE::class to Laravel config app.php file
sed: 1: "/Users/jessmckenzie/Sit ...": invalid command code j
Nothing to publish for tag [adminlte].`

**Comment by acacha** [comment]
Umm you found the error or solution I suppose!
