### ISSUE TITLE
Install overwrites other providers and aliases in config/app.php

### ISSUE THREAD

**Issue by johncarlson21** [acacha/adminlte-laravel#67]
I installed Entrust package got that working then installed Adminlte and it removed my Entrust service provider and alias entries and added the new Adminlte ones

very inconvenient

**Comment by acacha** [comment]
Hi @johncarlson21,

Acacha/adminlte-laravel is a scaffolding projecte meaning it has been created to be executed in fresh laravel projects.  A lot of Laravel projects use stubs and stubs could overwrite some files maybe I will document this on the readme.

Anyway are you using adminlte-laravel with acacha/llum? This package does not use stubs so tour existing service providers will be untouched... Can you give me more info to debug the problem?









Kind Regards
