### ISSUE TITLE
Login... I know...

### ISSUE THREAD

**Issue by dovy** [acacha/adminlte-laravel#7]
I'm not new to PHP but I'm new to laravel, and man I can't figure out how to login to save my life! haha.

/auth does nothing...

Can't find docs to save my life on this. Help?

**Comment by dovy** [comment]
So I do think something is off. I'm getting tons of 

```
Trying to get property of non-object (View: /Users/dovy/Development/Sites/wpupdate.dev/resources/views/partials/mainheader.blade.php) (View: 
```

Any suggestions would be greatly appreciated.

**Comment by jadesenberg** [comment]
I got the same problem too...

**Comment by heypaxton** [comment]
You need to set up the authentication routes before logging in.

```php
// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');
```

Here's more documentation on getting the Authentication for Laravel set up: http://laravel.com/docs/5.1/authentication

**Comment by acacha** [comment]
Thanks @heypaxton. I will publish a new release to adapt to this laravel 5.1 changes.

**Comment by Valonix** [comment]
i am new in Laravel , i created app, database, migrate table users, install ur plugin via composer and he is doesn`t work

i add routes
// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

go to site.com/auth/login and see empty page :(

go to site.com/auth/login and see empty page :(

**Comment by Valonix** [comment]
after i add views by the tutorial i have simple page with form. Where i can see ur admin lte views? :)

**Comment by Valonix** [comment]
all works. but after login i am redirected to site/home and see blank page. 

Route::get('home', ['uses' => 'AdminController@index', 'as' => 'homeurl']);

public function index(){
        return view('home');
    }

where iam wrong? :)

**Comment by acacha** [comment]
See new README.md comments maybe it helps you. Blank page often happens because and error. See the logs. Are you using homestead? You can see log errors at /var/log/nginx in your homestead machine

**Comment by Valonix** [comment]
all fine.
i see new version, for update i must just paste composer update? or all code in readme?

**Comment by acacha** [comment]
Composer update only make changes in vendor folder. To change files in you app you have to start from scratch or reexecute:

 $ php artisan vendor:publish --force --provider="Acacha\AdminLTETemplateLaravel\app\Providers\AdminLTETemplateServiceProvider"

Be careful your views will be overwritten!
