### ISSUE TITLE
Suggestion- remove CDN files and replace them with local files

### ISSUE THREAD

**Issue by salarAsadi** [acacha/adminlte-laravel#71]
I searched my view files and found that these files are downloaded from remote hosts
https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js
https://oss.maxcdn.com/respond/1.4.2/respond.min.js
https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css
https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css

files from remote servers(CDN) will slow down the load time of my web pages. please
replace these files with local files and put them in /public/libs/
thanks for your wonderful images.

**Comment by acacha** [comment]
@salarAsadi thanks for your suggestion. CDN files would be faster in some cases as you can read on Internet

http://www.cdnreviews.com/cdn-advantages-disadvantages/

In development I agree it could be faster not to use CDNs but in explotation it could be very useful.

Anyway you could change the URLs in your project changing the templates.
