### ISSUE TITLE
Upgrade to latest adminLTE version and use select2

### ISSUE THREAD

**Issue by RicardovanTongeren** [acacha/adminlte-laravel#8]
I would like to upgrade adminLTE to it's latest version. It has support for select2 that I would like to use. I updated/added all the less files in the resource directory and rebuilded my assets with gulp. Unfortunately when I enable select2 with javascript all the styling of those dropdown are to small. When I disable select2 the styling is good but officiously the inputs are just regular dropdowns then.

Is there an easy way to update to the latest version or to avoid the styling problem that I have after running $(".classname").select2();?

**Comment by acacha** [comment]
Do you mean version 2.2.0?

Yes now this package use 2.1.0. I will try tomorrow to upgrade...

**Comment by acacha** [comment]
Ok I have released new version 0.1.5 with AdminLTE 2.2.0. Update package with:

 $ composer update

Please let me now if your problems with select2 are solved.

**Comment by RicardovanTongeren** [comment]
I'll try them out this afternoon. Thanks for the fast response.

**Comment by Valonix** [comment]
i need update views files after composer update? from 2.1 to 2.2 ?

**Comment by acacha** [comment]
Republish files with php artisan vendor:publish as indicated in README.md file in installation section or if you wish reinstall package from scratch

**Comment by Valonix** [comment]
i think my notebook dimension is not for adminlte :)
![image](https://cloud.githubusercontent.com/assets/8511169/8944280/711e9bf8-3588-11e5-81fa-58df72e8c65c.png)

or all clear?  maybe I just think that the container must be in center, not go out to right

**Comment by RicardovanTongeren** [comment]
I'am going to close this issue. It is not really solved for me in my current project but i've decided to start from scratch to see if it works. Thanks for the support.
