### ISSUE TITLE
sh: 1: llum: not found

### ISSUE THREAD

**Issue by reeslo** [acacha/adminlte-laravel#82]
I have installed llum `composer global require "acacha/llum=~0.1"` 
then adminlte-laravel `composer global require "acacha/adminlte-laravel-installer=~2.0"`

But 
```
adminlte-laravel install
Running llum package AdminLTE...
sh: 1: llum: not found
```

I don't know why doesn't I try composer clearcache and composer global update. Without changes.

**Comment by acacha** [comment]
Maybe you have to add a composer bin folder to your PATH? Add this line

```bash
 export PATH=${PATH}:~/.composer/vendor/bin
``

to file:

```
~/.bashrc
```

**Comment by reeslo** [comment]
I do this yet laravel and work well
