### ISSUE TITLE
Some trouble with html layout

### ISSUE THREAD

**Issue by EugeneVdovenko** [acacha/adminlte-laravel#87]
I have some trouble with html-block height in layout. 
![screenshot](http://joxi.ru/82Qe3oaiK8B72d.jpg)
Do you fix it? Or it common trouble with template?

**Comment by EugeneVdovenko** [comment]
I need wrap each block
```
<div class="row">
    <div class="col-xs-12">
        <div class="box">...</div>
    </div>
</div>
```
then view template ok

**Comment by acacha** [comment]
Thanks for the info!
