### ISSUE TITLE
Problem skin color

### ISSUE THREAD

**Issue by oscarjoya** [acacha/adminlte-laravel#88]
I am implementing the subject , now I would like to use the SkinBlack but I can not place, not where I set

**Comment by slozano95** [comment]
You should change the body tag class in  > resources>views>layouts>app.blade.php
`<body class="skin-yellow sidebar-mini">`
And also the reference to the skin color in  > resources>views>layouts>partials>htmlheader.blade.php
`<link href="{{ asset('/css/skins/skin-yellow.css') }}" rel="stylesheet" type="text/css" />`
    
Hope it helps
