### ISSUE TITLE
Login page does not load Jquery

### ISSUE THREAD

**Issue by cstpraveen** [acacha/adminlte-laravel#9]
Change login pages into 

    
    <script src="{{ asset('/plugins/jQuery/jQuery-2.1.4.min.js') }}"></script>
    
    <script src="{{ asset('/js/bootstrap.min.js') }}" type="text/javascript"></script>
    
    <script src="{{ asset('/plugins/iCheck/icheck.min.js') }}" type="text/javascript"></script>

**Comment by acacha** [comment]
Sorry for the delay I was on holydays and I didn't see your issue? Could you give me more info? I don't understand the issue

**Comment by cstpraveen** [comment]
I have added the above links to the base login page... Please add them...

**Comment by acacha** [comment]
Aghh ok I catch it! In my case sames all works ok (jquery is loading) bu I understand it could not work in all cases without asset!

Solved in new release 1.0.2
