### ISSUE TITLE
[Improvement] What if a user want to alter current route system?

### ISSUE THREAD

**Issue by Modelizer** [acacha/adminlte-laravel#90]
Hi,
   Currently, home controller [route](https://github.com/acacha/adminlte-laravel/blob/master/src/Http/routes.php#L11) is hard coded... If I want to rename it to dashboard then only thing remain is to register a new route... But looking to our `app.php` file which is loading adminlte service provide which will result in two routes registered with the same action but with different URL... 
Example `home` which will be loaded by adminlte service provider and `dashboard` route which is been registered in `routes.php` file.

**Comment by acacha** [comment]
Hi @Modelizer !

Feel free to send a Pull Request o let me know how you would change the code.

Thnsk!

**Comment by Modelizer** [comment]
I'll try once i get free I'll do so :)

Thanks :+1:
