### ISSUE TITLE
gulp file replacement

### ISSUE THREAD

**Issue by Pezhvak** [acacha/adminlte-laravel#93]
I just used your package on my existing project, thanks it's very good, a lot should be done but for now, that's very unpleasant to see that my gulpfile.js is replaced without any warning in your documentation.. i lost all of my configuration without any backup.

Mention it or at least backup that file before replacing it.
![screen shot 2016-08-19 at 4 09 12 pm](https://cloud.githubusercontent.com/assets/3134479/17808784/5406fb5c-6627-11e6-9500-78d25dd4222d.png)

**Comment by acacha** [comment]
A lot of files are replaced using force. I design this package for fresh projects but I try to do my best for respecting existing code so If you want to suggest a concrete change feel free to send me a pull request.

Thanks!
