### ISSUE TITLE
Routes got overided. Don't know to get it work.

### ISSUE THREAD

**Issue by CHOMNANP** [acacha/adminlte-laravel#99]
I'm so confused. Just add the admintlet-laravel to my app.
My routes doesn't work anymore.

Any clean solution for that?
Thanks.

**Comment by acacha** [comment]
Cloud you give us more info please?

I tested adding for exemple:

```
Route::get('/test', function () {
    echo "TEST!";
});
```

in routes/web.php and works nice.
